DELETE FROM SYS_DICT;
Insert into SYS_DICT
   (DIC_CODE, 
    DIC_DES, 
    DIC_TBLNAME, 
    DIC_ID_COLNAME, 
    DIC_IDVALUE, 
    DIC_VAL_COLNAME, 
    DIC_DES_COLNAME
   )
 Values
   ('menuType', 
    '菜单类型', 
    'SYS_DICTIONARIES', 
    'PARENT_ID', 
    '45e0a34f25ca4f72b0d8b643fa2ace03', 
    'DICT_CODE', 
    'NAME');
Insert into SYS_DICT
   (DIC_CODE, 
    DIC_DES, 
    DIC_TBLNAME, 
    DIC_ID_COLNAME, 
    DIC_IDVALUE, 
    DIC_VAL_COLNAME, 
    DIC_DES_COLNAME
   )
 Values
   ('DbType', 
    '数据库类型', 
    'SYS_DICTIONARIES', 
    'PARENT_ID', 
    '729f3ad1db984226b6a921e3df2dadcb', 
    'DICT_CODE', 
    'NAME');
Insert into SYS_DICT
   (DIC_CODE, 
    DIC_DES, 
    DIC_TBLNAME, 
    DIC_ID_COLNAME, 
    DIC_IDVALUE, 
    DIC_VAL_COLNAME, 
    DIC_DES_COLNAME
   )
 Values
   ('ConWay', 
    '连接方式', 
    'SYS_DICTIONARIES', 
    'PARENT_ID', 
    '6b7d4036fb3747f28e28a3e24081f5c6', 
    'DICT_CODE', 
    'NAME');
Insert into SYS_DICT
   (DIC_CODE, 
    DIC_DES, 
    DIC_TBLNAME, 
    DIC_ID_COLNAME, 
    DIC_IDVALUE, 
    DIC_VAL_COLNAME, 
    DIC_DES_COLNAME
   )
 Values
   ('menuChannel', 
    '菜单渠道', 
    'SYS_DICTIONARIES', 
    'PARENT_ID', 
    '7c0b914f3f104f2c9c9e14b527057dd9', 
    'DICT_CODE', 
    'NAME');
Insert into SYS_DICT
   (DIC_CODE, 
    DIC_DES, 
    DIC_TBLNAME, 
    DIC_VAL_COLNAME, 
    DIC_DES_COLNAME
   )
 Values
   ('menuGroup', 
    '菜单功能组', 
    'SYS_MENU_FUN_GROUP', 
    'FUN_GROUP_ID', 
    'FUN_GROUP_NAME');
Insert into SYS_DICT
   (DIC_CODE, 
    DIC_DES, 
    DIC_TBLNAME, 
    DIC_ID_COLNAME, 
    DIC_IDVALUE, 
    DIC_VAL_COLNAME, 
    DIC_DES_COLNAME
   )
 Values
   ('DeptCode', 
    '部门编号', 
    'SYS_DICTIONARIES', 
    'PARENT_ID', 
    'f271619c4e3c453cb795a720e28861aa', 
    'DICT_CODE', 
    'NAME');
Insert into SYS_DICT
   (DIC_CODE, 
    DIC_DES, 
    DIC_TBLNAME, 
    DIC_ID_COLNAME, 
    DIC_IDVALUE, 
    DIC_VAL_COLNAME, 
    DIC_DES_COLNAME
   )
 Values
   ('IDType', 
    '证件类型', 
    'SYS_DICTIONARIES', 
    'PARENT_ID', 
    '3fa59275066842ad8daf54bb8959d24a', 
    'DICT_CODE', 
    'NAME');
COMMIT;
