DROP TABLE FIN_SYS_ORG_HIERARCHY CASCADE CONSTRAINTS;

CREATE TABLE FIN_SYS_ORG_HIERARCHY
(
  SUMM_FUNC  NVARCHAR2(6)                       NOT NULL,
  FIR_CODE   NVARCHAR2(18),
  FIR_NAME   NVARCHAR2(100),
  SEC_CODE   NVARCHAR2(18),
  SEC_NAME   NVARCHAR2(100),
  THR_CODE   NVARCHAR2(18),
  THR_NAME   NVARCHAR2(100),
  FOR_CODE   NVARCHAR2(18),
  FOR_NAME   NVARCHAR2(100),
  FIV_CODE   NVARCHAR2(18),
  FIV_NAME   NVARCHAR2(100)
);

COMMENT ON TABLE FIN_SYS_ORG_HIERARCHY IS '机构标准汇总关系表';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.SUMM_FUNC IS '汇总关系类型';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.FIR_CODE IS '一级机构代码，机构层级中的最底层机构';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.FIR_NAME IS '一级机构名称，机构层级中的最底层机构';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.SEC_CODE IS '二级机构代码';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.SEC_NAME IS '二级机构名称';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.THR_CODE IS '四级机构代码';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.THR_NAME IS '四级机构名称';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.FOR_CODE IS '四级机构代码';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.FOR_NAME IS '四级机构名称';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.FIV_CODE IS '五级机构代码';

COMMENT ON COLUMN FIN_SYS_ORG_HIERARCHY.FIV_NAME IS '五级机构名称';
