DROP TABLE FIN_SYS_BUTTON_AUTH CASCADE CONSTRAINTS;

CREATE TABLE FIN_SYS_BUTTON_AUTH
(
  BUTTONAUTH_CODE  NVARCHAR2(32)                NOT NULL,
  COMPANY          NVARCHAR2(20)                NOT NULL,
  RESO_ID          NVARCHAR2(20)                NOT NULL,
  RESO_NAME        NVARCHAR2(100)               NOT NULL,
  FUN_CODE         NVARCHAR2(20)                NOT NULL,
  FUN_NAME         NVARCHAR2(100)               NOT NULL,
  TYPE_CODE        NVARCHAR2(1),
  TYPE_VALUE       NVARCHAR2(20),
  STATUS           NVARCHAR2(1),
  CREATE_USER      NVARCHAR2(20),
  CREATE_DATE      NVARCHAR2(10),
  UPDATE_USER      NVARCHAR2(20),
  UPDATE_DATE      NVARCHAR2(10),
  DELETE_USER      NVARCHAR2(20),
  DELETE_DATE      NVARCHAR2(10),
  RESERVED         NVARCHAR2(100),
  REMARK           NVARCHAR2(100)
);

COMMENT ON TABLE FIN_SYS_BUTTON_AUTH IS '用于下载导出绑定机器的权限设置';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.BUTTONAUTH_CODE IS '权限设置代码';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.COMPANY IS '法人机构代码';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.RESO_ID IS '菜单ID';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.RESO_NAME IS '菜单名称';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.FUN_CODE IS '功能代码';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.FUN_NAME IS '功能名称';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.TYPE_CODE IS '1-机器名、2-MAC地址、3-IP地址';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.TYPE_VALUE IS 'TYPE_CODE对应值';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.STATUS IS '是否有效 0-有效 1-无效';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.CREATE_USER IS '创建人';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.UPDATE_USER IS '修改人';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.UPDATE_DATE IS '修改日期';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.DELETE_USER IS '删除人';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.DELETE_DATE IS '删除日期';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.RESERVED IS '预留字段';

COMMENT ON COLUMN FIN_SYS_BUTTON_AUTH.REMARK IS '备注';
