ALTER TABLE SYS_ROLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYS_ROLE CASCADE CONSTRAINTS;

CREATE TABLE SYS_ROLE
(
  ROLE_ID       NVARCHAR2(32)                   NOT NULL,
  ROLE_NAME     NVARCHAR2(50),
  ROLE_NAME_EN  NVARCHAR2(50),
  ROLE_DESC     NVARCHAR2(100),
  COMPANY       NVARCHAR2(32)
);

COMMENT ON TABLE SYS_ROLE IS '角色定义表';

COMMENT ON COLUMN SYS_ROLE.ROLE_ID IS '角色编码';

COMMENT ON COLUMN SYS_ROLE.ROLE_NAME IS '角色名称';

COMMENT ON COLUMN SYS_ROLE.ROLE_DESC IS '角色描述';

COMMENT ON COLUMN SYS_ROLE.COMPANY IS '法人代码';


ALTER TABLE SYS_ROLE ADD (
  PRIMARY KEY
  (ROLE_ID));
