ALTER TABLE SYS_POSITION
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYS_POSITION CASCADE CONSTRAINTS;

CREATE TABLE SYS_POSITION
(
  POSITI_ID       NVARCHAR2(32)                 NOT NULL,
  POSITI_NAME     NVARCHAR2(50),
  POSITI_NAME_EN  NVARCHAR2(50),
  POSITI_DESC     NVARCHAR2(50)
);

COMMENT ON TABLE SYS_POSITION IS '用户职位 表';

COMMENT ON COLUMN SYS_POSITION.POSITI_ID IS '职位编码';

COMMENT ON COLUMN SYS_POSITION.POSITI_NAME IS '职位名称';

COMMENT ON COLUMN SYS_POSITION.POSITI_DESC IS '职位名称描述';

ALTER TABLE SYS_POSITION ADD (
  PRIMARY KEY
  (POSITI_ID));
