DROP TABLE SYS_CREATECODE CASCADE CONSTRAINTS;

CREATE TABLE SYS_CREATECODE
(
  CREATECODE_ID  NVARCHAR2(100)                 NOT NULL,
  PACKAGENAME    NVARCHAR2(50),
  OBJECTNAME     NVARCHAR2(50),
  TABLENAME      NVARCHAR2(50),
  FIELDLIST      NCLOB,
  CREATETIME     NVARCHAR2(100),
  TITLE          NVARCHAR2(255),
  MODELNAME      NVARCHAR2(199)
);

COMMENT ON COLUMN SYS_CREATECODE.PACKAGENAME IS '包名';

COMMENT ON COLUMN SYS_CREATECODE.OBJECTNAME IS '类名';

COMMENT ON COLUMN SYS_CREATECODE.TABLENAME IS '表名';

COMMENT ON COLUMN SYS_CREATECODE.FIELDLIST IS '属性集';

COMMENT ON COLUMN SYS_CREATECODE.CREATETIME IS '创建时间';

COMMENT ON COLUMN SYS_CREATECODE.TITLE IS '描述';

COMMENT ON COLUMN SYS_CREATECODE.MODELNAME IS '模块名';
