DROP TABLE SYS_MENU_FUN_GROUP CASCADE CONSTRAINTS;

CREATE TABLE SYS_MENU_FUN_GROUP
(
  FUN_GROUP_ID       NVARCHAR2(32)              NOT NULL,
  FUN_GROUP_NAME     NVARCHAR2(50),
  FUN_GROUP_NAME_EN  NVARCHAR2(50),
  FUN_GROUP_DESC     NVARCHAR2(100)
);

COMMENT ON TABLE SYS_MENU_FUN_GROUP IS '菜单功能组表';

COMMENT ON COLUMN SYS_MENU_FUN_GROUP.FUN_GROUP_ID IS '功能组编码';

COMMENT ON COLUMN SYS_MENU_FUN_GROUP.FUN_GROUP_DESC IS '功能组描述';
