DROP TABLE SYS_ORG CASCADE CONSTRAINTS;

CREATE TABLE SYS_ORG
(
  ORG_ID     NVARCHAR2(100)                     NOT NULL,
  NAME       NVARCHAR2(30),
  NAME_EN    NVARCHAR2(50),
  ORG_LEVEL  NUMBER(11),
  ORG_CODE   NVARCHAR2(50),
  PARENT_ID  NVARCHAR2(100),
  ORG_DESC   NVARCHAR2(255),
  HEADMAN    NVARCHAR2(30),
  TEL        NVARCHAR2(50),
  FUNCTIONS  NVARCHAR2(255),
  ADDRESS    NVARCHAR2(255),
  STATUS     NVARCHAR2(2),
  ORG_ORDER  NUMBER(11),
  COMPANY    NVARCHAR2(10)
);

COMMENT ON TABLE SYS_ORG IS '机构表';

COMMENT ON COLUMN SYS_ORG.ORG_ID IS '唯一标识';

COMMENT ON COLUMN SYS_ORG.NAME IS '名称';

COMMENT ON COLUMN SYS_ORG.NAME_EN IS '英文';

COMMENT ON COLUMN SYS_ORG.ORG_LEVEL IS '机构层级';

COMMENT ON COLUMN SYS_ORG.ORG_CODE IS '机构编码';

COMMENT ON COLUMN SYS_ORG.PARENT_ID IS '上级ID';

COMMENT ON COLUMN SYS_ORG.ORG_DESC IS '备注';

COMMENT ON COLUMN SYS_ORG.HEADMAN IS '负责人';

COMMENT ON COLUMN SYS_ORG.TEL IS '电话';

COMMENT ON COLUMN SYS_ORG.FUNCTIONS IS '部门职能';

COMMENT ON COLUMN SYS_ORG.ADDRESS IS '地址';
