DROP TABLE SYS_MENU_FUN CASCADE CONSTRAINTS;

CREATE TABLE SYS_MENU_FUN
(
  FUN_GROUP_ID  NVARCHAR2(32)                   NOT NULL,
  FUN_ID        NVARCHAR2(32)                   NOT NULL,
  FUN_NAME      NVARCHAR2(50),
  FUN_NAME_EN   NVARCHAR2(50),
  FUN_DESC      NVARCHAR2(100)
);

COMMENT ON TABLE SYS_MENU_FUN IS '菜单功能明细表';

COMMENT ON COLUMN SYS_MENU_FUN.FUN_GROUP_ID IS '功能组编码';

COMMENT ON COLUMN SYS_MENU_FUN.FUN_ID IS '功能编码';

COMMENT ON COLUMN SYS_MENU_FUN.FUN_NAME IS '功能名称';

COMMENT ON COLUMN SYS_MENU_FUN.FUN_NAME_EN IS '功能英文名称';
