DROP TABLE SYS_HOME_MANAGEMENT CASCADE CONSTRAINTS;

CREATE TABLE SYS_HOME_MANAGEMENT
(
  MODULE_ID       NVARCHAR2(32),
  MODULE_NAME     NVARCHAR2(50),
  MODULE_PICTURE  NVARCHAR2(50)
);

COMMENT ON TABLE SYS_HOME_MANAGEMENT IS '首页管理';

COMMENT ON COLUMN SYS_HOME_MANAGEMENT.MODULE_ID IS '模块Id';

COMMENT ON COLUMN SYS_HOME_MANAGEMENT.MODULE_NAME IS '模块名称';

COMMENT ON COLUMN SYS_HOME_MANAGEMENT.MODULE_PICTURE IS '模块图片';
