DROP TABLE SYS_MODULE_APP CASCADE CONSTRAINTS;

CREATE TABLE SYS_MODULE_APP
(
  MODULE_ID  NVARCHAR2(32),
  SYS_IND    NVARCHAR2(50),
  ORDER_BY   NVARCHAR2(50)
);

COMMENT ON TABLE SYS_MODULE_APP IS '模块与系统对应关系';

COMMENT ON COLUMN SYS_MODULE_APP.MODULE_ID IS '模块Id';

COMMENT ON COLUMN SYS_MODULE_APP.SYS_IND IS '系统编码';

COMMENT ON COLUMN SYS_MODULE_APP.ORDER_BY IS '序号';
