DROP TABLE SYS_MENU CASCADE CONSTRAINTS;

CREATE TABLE SYS_MENU
(
  MENU_ID        NUMBER(11)                     NOT NULL,
  MENU_NAME      NVARCHAR2(50),
  MENU_NAME_EN   NVARCHAR2(50),
  MENU_URL       NVARCHAR2(100),
  PARENT_ID      NUMBER(11),
  ORDER_BY       NVARCHAR2(5),
  MENU_ICON      NVARCHAR2(50),
  MENU_TYPE      NVARCHAR2(50),
  MENU_STATE     NUMBER(11),
  MENU_GROUP_ID  NVARCHAR2(32),
  TRAN_CODE      NVARCHAR2(10),
  SYS_IND        NVARCHAR2(10),
  COMPANY        NVARCHAR2(10),
  MENU_CHANNEL   NVARCHAR2(10)
);

COMMENT ON TABLE SYS_MENU IS '菜单表';

COMMENT ON COLUMN SYS_MENU.MENU_ID IS '菜单编码';

COMMENT ON COLUMN SYS_MENU.MENU_NAME IS '菜单名称';

COMMENT ON COLUMN SYS_MENU.MENU_URL IS '菜单地址';

COMMENT ON COLUMN SYS_MENU.PARENT_ID IS '上级菜单';

COMMENT ON COLUMN SYS_MENU.ORDER_BY IS '菜单排序';

COMMENT ON COLUMN SYS_MENU.MENU_ICON IS '菜单图片';

COMMENT ON COLUMN SYS_MENU.MENU_TYPE IS '菜单类型';

COMMENT ON COLUMN SYS_MENU.MENU_STATE IS '菜单状态';

COMMENT ON COLUMN SYS_MENU.MENU_GROUP_ID IS '菜单组';

COMMENT ON COLUMN SYS_MENU.TRAN_CODE IS '交易码';

COMMENT ON COLUMN SYS_MENU.SYS_IND IS '所属系统';

COMMENT ON COLUMN SYS_MENU.COMPANY IS '法人机构代码';

COMMENT ON COLUMN SYS_MENU.MENU_CHANNEL IS '菜单渠道 PC ,MOBILE等';
