ALTER TABLE SYS_SMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYS_SMS CASCADE CONSTRAINTS;

CREATE TABLE SYS_SMS
(
  SMS_ID         NVARCHAR2(100)                 NOT NULL,
  CONTENT        NVARCHAR2(1000),
  TYPE           NVARCHAR2(5),
  TO_USERNAME    NVARCHAR2(255),
  FROM_USERNAME  NVARCHAR2(255),
  SEND_TIME      NVARCHAR2(100),
  STATUS         NVARCHAR2(5),
  SANME_ID       NVARCHAR2(100)
);

COMMENT ON COLUMN SYS_SMS.CONTENT IS '内容';

COMMENT ON COLUMN SYS_SMS.TYPE IS '类型';

COMMENT ON COLUMN SYS_SMS.TO_USERNAME IS '收信人';

COMMENT ON COLUMN SYS_SMS.FROM_USERNAME IS '发信人';

COMMENT ON COLUMN SYS_SMS.SEND_TIME IS '发信时间';

COMMENT ON COLUMN SYS_SMS.STATUS IS '状态';



ALTER TABLE SYS_SMS ADD (
  PRIMARY KEY
  (SMS_ID));
