DROP TABLE SYS_DICT CASCADE CONSTRAINTS;

CREATE TABLE SYS_DICT
(
  DIC_CODE          NVARCHAR2(50)               NOT NULL,
  DIC_DES           NVARCHAR2(100),
  DIC_TYPE          NVARCHAR2(1),
  DIC_TBLNAME       NVARCHAR2(30),
  DIC_ID_COLNAME    NVARCHAR2(30),
  DIC_IDVALUE       NVARCHAR2(35),
  DIC_VAL_COLNAME   NVARCHAR2(50),
  DIC_DES_COLNAME   NVARCHAR2(50),
  REMARK            NVARCHAR2(100),
  DIC_SORT_COLNAME  NVARCHAR2(30),
  DIC_DYNAMIC_SIGN  NVARCHAR2(1)
);

COMMENT ON TABLE SYS_DICT IS '系统字典表';

COMMENT ON COLUMN SYS_DICT.DIC_CODE IS '字典编码';

COMMENT ON COLUMN SYS_DICT.DIC_DES IS '字典名称';

COMMENT ON COLUMN SYS_DICT.DIC_TYPE IS '字典类型,0-独立表作为字典;1-字典来源于共同表中定义的特定数据';

COMMENT ON COLUMN SYS_DICT.DIC_TBLNAME IS '字典来源表';

COMMENT ON COLUMN SYS_DICT.DIC_ID_COLNAME IS '字典对应的过滤条件列';

COMMENT ON COLUMN SYS_DICT.DIC_IDVALUE IS '字典列对应的过滤条件列取值';

COMMENT ON COLUMN SYS_DICT.DIC_VAL_COLNAME IS '字典列对应的取值列';

COMMENT ON COLUMN SYS_DICT.DIC_DES_COLNAME IS '字典列对应的描述列';

COMMENT ON COLUMN SYS_DICT.REMARK IS '备注';

COMMENT ON COLUMN SYS_DICT.DIC_SORT_COLNAME IS '排序字段';

COMMENT ON COLUMN SYS_DICT.DIC_DYNAMIC_SIGN IS '是否动态获取，默认为0。0-非动态获取；1-动态获取；';
