DROP TABLE SYS_OPERATION_LOG CASCADE CONSTRAINTS;

CREATE TABLE SYS_OPERATION_LOG
(
  LOG_ID          NVARCHAR2(50)                 NOT NULL,
  USER_ID         NVARCHAR2(100),
  USERNAME        NVARCHAR2(20),
  NAME            NVARCHAR2(50),
  ORG             NVARCHAR2(50),
  IP              NVARCHAR2(20),
  MAC             NVARCHAR2(50),
  OPERATION_URL   NVARCHAR2(200),
  OPERATION_TIME  NVARCHAR2(20),
  OPERATION_DESC  NVARCHAR2(500)
);

COMMENT ON TABLE SYS_OPERATION_LOG IS '平台操作日志表，记录操作平台各功能的信息';

COMMENT ON COLUMN SYS_OPERATION_LOG.LOG_ID IS '日志流水号';

COMMENT ON COLUMN SYS_OPERATION_LOG.USER_ID IS '访问者用户Key';

COMMENT ON COLUMN SYS_OPERATION_LOG.USERNAME IS '访问者用户编码';

COMMENT ON COLUMN SYS_OPERATION_LOG.NAME IS '访问者用户名称';

COMMENT ON COLUMN SYS_OPERATION_LOG.ORG IS '访问者所属机构';

COMMENT ON COLUMN SYS_OPERATION_LOG.IP IS '访问者IP地址';

COMMENT ON COLUMN SYS_OPERATION_LOG.MAC IS '访问者MAC地址';

COMMENT ON COLUMN SYS_OPERATION_LOG.OPERATION_URL IS '访问URL';

COMMENT ON COLUMN SYS_OPERATION_LOG.OPERATION_TIME IS '操作时间，年月日 时分秒';

COMMENT ON COLUMN SYS_OPERATION_LOG.OPERATION_DESC IS '具体操作的描述';
