DROP TABLE SYS_PICTURES CASCADE CONSTRAINTS;

CREATE TABLE SYS_PICTURES
(
  PICTURES_ID  NVARCHAR2(100)                   NOT NULL,
  TITLE        NVARCHAR2(255),
  NAME         NVARCHAR2(255),
  PATH         NVARCHAR2(255),
  CREATETIME   NVARCHAR2(100),
  MASTER_ID    NVARCHAR2(255),
  BZ           NVARCHAR2(255)
);

COMMENT ON COLUMN SYS_PICTURES.TITLE IS '标题';

COMMENT ON COLUMN SYS_PICTURES.NAME IS '文件名';

COMMENT ON COLUMN SYS_PICTURES.PATH IS '路径';

COMMENT ON COLUMN SYS_PICTURES.CREATETIME IS '创建时间';

COMMENT ON COLUMN SYS_PICTURES.MASTER_ID IS '属于';

COMMENT ON COLUMN SYS_PICTURES.BZ IS '备注';
