DROP TABLE SYS_COMPANY CASCADE CONSTRAINTS;

CREATE TABLE SYS_COMPANY
(
  COMP_CODE   NVARCHAR2(10)                     NOT NULL,
  COMP_SHORT  NVARCHAR2(20),
  COMP_NAME   NVARCHAR2(50),
  USER_CODE   NVARCHAR2(20),
  LOGO_PATH   NVARCHAR2(100)
);

COMMENT ON TABLE SYS_COMPANY IS '法人机构表';

COMMENT ON COLUMN SYS_COMPANY.COMP_CODE IS '法人代码';

COMMENT ON COLUMN SYS_COMPANY.COMP_SHORT IS '法人简称';

COMMENT ON COLUMN SYS_COMPANY.COMP_NAME IS '法人名称';

COMMENT ON COLUMN SYS_COMPANY.USER_CODE IS '法人管理员';

COMMENT ON COLUMN SYS_COMPANY.LOGO_PATH IS '法人logo';
