ALTER TABLE SYS_POLICY
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYS_POLICY CASCADE CONSTRAINTS;

CREATE TABLE SYS_POLICY
(
  ROLE_ID       NVARCHAR2(32)                   NOT NULL,
  MENU_ID       NVARCHAR2(10)                   NOT NULL,
  FUN_GROUP_ID  NVARCHAR2(32)                   NOT NULL,
  FUN_ID        NVARCHAR2(32)                   NOT NULL
);

COMMENT ON TABLE SYS_POLICY IS '角色对应菜单及操作权限表';

COMMENT ON COLUMN SYS_POLICY.ROLE_ID IS '角色编码';

COMMENT ON COLUMN SYS_POLICY.MENU_ID IS '菜单编码';

COMMENT ON COLUMN SYS_POLICY.FUN_GROUP_ID IS '功能组编码';

COMMENT ON COLUMN SYS_POLICY.FUN_ID IS '功能编码';


ALTER TABLE SYS_POLICY ADD (
  PRIMARY KEY
  (ROLE_ID, MENU_ID, FUN_GROUP_ID, FUN_ID));
