ALTER TABLE SYS_USER
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYS_USER CASCADE CONSTRAINTS;

CREATE TABLE SYS_USER
(
  USER_ID         NVARCHAR2(100)                NOT NULL,
  USERNAME        NVARCHAR2(255),
  PASSWORD        NVARCHAR2(255),
  NAME            NVARCHAR2(255),
  LAST_LOGIN      NVARCHAR2(255),
  IP              NVARCHAR2(100),
  SKIN            NVARCHAR2(100),
  EMAIL           NVARCHAR2(32),
  TELLER_NUMBER   NVARCHAR2(100),
  PHONE           NVARCHAR2(32),
  PWD_ALTER_TIME  NVARCHAR2(20),
  DEPT_CODE       NVARCHAR2(32),
  STATE           NVARCHAR2(2),
  ERR_TIMES       NUMBER(11),
  LOCK_STATUS     NVARCHAR2(2),
  COMPANY         NVARCHAR2(10)
);

COMMENT ON TABLE SYS_USER IS '用户表';

COMMENT ON COLUMN SYS_USER.USER_ID IS '用户编码';

COMMENT ON COLUMN SYS_USER.USERNAME IS '登录编码';

COMMENT ON COLUMN SYS_USER.PASSWORD IS '密码';

COMMENT ON COLUMN SYS_USER.NAME IS '用户名称';

COMMENT ON COLUMN SYS_USER.LAST_LOGIN IS '最近登录时间';

COMMENT ON COLUMN SYS_USER.IP IS '最近登录ip';

COMMENT ON COLUMN SYS_USER.SKIN IS '皮肤';

COMMENT ON COLUMN SYS_USER.EMAIL IS 'email';

COMMENT ON COLUMN SYS_USER.TELLER_NUMBER IS '柜员号';

COMMENT ON COLUMN SYS_USER.PHONE IS '电话号码';

COMMENT ON COLUMN SYS_USER.PWD_ALTER_TIME IS '密码修改日期';

COMMENT ON COLUMN SYS_USER.DEPT_CODE IS '部门编码';

COMMENT ON COLUMN SYS_USER.STATE IS '有效状态';

COMMENT ON COLUMN SYS_USER.ERR_TIMES IS '出错次数';

COMMENT ON COLUMN SYS_USER.LOCK_STATUS IS '锁定状态 ;0 正常 1 锁定';

COMMENT ON COLUMN SYS_USER.COMPANY IS '法人编码';


ALTER TABLE SYS_USER ADD (
  PRIMARY KEY
  (USER_ID));
