DROP TABLE COM_SM_BRANCH CASCADE CONSTRAINTS;

CREATE TABLE COM_SM_BRANCH
(
  BRANCH_NO      NVARCHAR2(4)                   NOT NULL,
  REPORT_BRANCH  NVARCHAR2(4)                   NOT NULL,
  FINANCE_ENT    NVARCHAR2(11)                  NOT NULL,
  FINANCE_PER    NVARCHAR2(16),
  MEMO           NVARCHAR2(100),
  FLAG           NVARCHAR2(1)                   NOT NULL,
  DEL_FLAG       NVARCHAR2(1)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN COM_SM_BRANCH.BRANCH_NO IS '事业部行号';

COMMENT ON COLUMN COM_SM_BRANCH.REPORT_BRANCH IS '分行号';

COMMENT ON COLUMN COM_SM_BRANCH.FINANCE_ENT IS '企业金融机构编码';

COMMENT ON COLUMN COM_SM_BRANCH.FINANCE_PER IS '个人金融机构编码';

COMMENT ON COLUMN COM_SM_BRANCH.MEMO IS '备注';

COMMENT ON COLUMN COM_SM_BRANCH.FLAG IS '分行为1，其他为0';

COMMENT ON COLUMN COM_SM_BRANCH.DEL_FLAG IS '删除标识';
