DROP TABLE COMPLIANCE_COMMITMENT CASCADE CONSTRAINTS;

CREATE TABLE COMPLIANCE_COMMITMENT
(
  USER_ID      NVARCHAR2(36)                    NOT NULL,
  USER_CODE    NVARCHAR2(100),
  USER_NAME    NVARCHAR2(100),
  ORG_CODE     NVARCHAR2(100),
  ORG_NAME     NVARCHAR2(100),
  CREATE_TIME  NVARCHAR2(10)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE COMPLIANCE_COMMITMENT IS '合规承诺书';

COMMENT ON COLUMN COMPLIANCE_COMMITMENT.USER_ID IS '用户ID';

COMMENT ON COLUMN COMPLIANCE_COMMITMENT.USER_CODE IS '用户编号';

COMMENT ON COLUMN COMPLIANCE_COMMITMENT.USER_NAME IS '姓名';

COMMENT ON COLUMN COMPLIANCE_COMMITMENT.ORG_CODE IS '机构号';

COMMENT ON COLUMN COMPLIANCE_COMMITMENT.ORG_NAME IS '机构名称';

COMMENT ON COLUMN COMPLIANCE_COMMITMENT.CREATE_TIME IS '创建时间';
