DROP TABLE COMPLIANCE_COMMITMENT_CONTENT CASCADE CONSTRAINTS;

CREATE TABLE COMPLIANCE_COMMITMENT_CONTENT
(
  CONTENT_ID  NVARCHAR2(36)                     NOT NULL,
  CONTENT     NVARCHAR2(2000)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN COMPLIANCE_COMMITMENT_CONTENT.CONTENT IS 'ÄÚÈÝ';
