DROP TABLE CQ_SM_BRANCH CASCADE CONSTRAINTS;

CREATE TABLE CQ_SM_BRANCH
(
  CDB_BRANCH_NO     NVARCHAR2(4)                NOT NULL,
  FINANCE_CODE_ENT  VARCHAR2(11 BYTE)           NOT NULL,
  FINANCE_CODE_PER  VARCHAR2(16 BYTE),
  MEMO              NVARCHAR2(100),
  FLAG              NVARCHAR2(1)                NOT NULL,
  DEL_FLAG          NVARCHAR2(1)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
