DROP TABLE CREDIT_RPT_EXCP_LOG CASCADE CONSTRAINTS;

CREATE TABLE CREDIT_RPT_EXCP_LOG
(
  CREDIT_RPT_EXCP_LOG_ID  NVARCHAR2(32)         NOT NULL,
  DATA_DATE               NVARCHAR2(10)         NOT NULL,
  LOG_KIND                NVARCHAR2(10)         NOT NULL,
  LOG_KIND_SUBTYPE        NVARCHAR2(10)         NOT NULL,
  LOG_NUM                 NVARCHAR2(10)         NOT NULL,
  LOG_INFO                NVARCHAR2(2000)       NOT NULL,
  CREATE_TIME             NVARCHAR2(10)         NOT NULL,
  LAST_UPDATE_TIME        NVARCHAR2(10)         NOT NULL
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CREDIT_RPT_EXCP_LOG IS '征信报送异常日志表';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.CREDIT_RPT_EXCP_LOG_ID IS '征信报送异常日志主键';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.DATA_DATE IS '日志对应的数据时间';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.LOG_KIND IS '日志信息种类';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.LOG_KIND_SUBTYPE IS '日志信息种类细分';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.LOG_NUM IS '日志编号';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.LOG_INFO IS '日志信息';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.CREATE_TIME IS '日志创建时间';

COMMENT ON COLUMN CREDIT_RPT_EXCP_LOG.LAST_UPDATE_TIME IS '最后更新时间';
