DROP TABLE CREDIT_RPT_EXCP_CODE CASCADE CONSTRAINTS;

CREATE TABLE CREDIT_RPT_EXCP_CODE
(
  CREDIT_RPT_EXCP_CODE  NVARCHAR2(32)           NOT NULL,
  EXCP_CODE             NVARCHAR2(32)           NOT NULL,
  EXCP_NUM              NVARCHAR2(10)           NOT NULL,
  EXCP_INFO             NVARCHAR2(2000)         NOT NULL,
  CREATE_TIME           NVARCHAR2(10)           NOT NULL,
  CREAT_USER            NVARCHAR2(20)           NOT NULL
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE CREDIT_RPT_EXCP_CODE IS '征信报送异常代码表';

COMMENT ON COLUMN CREDIT_RPT_EXCP_CODE.CREDIT_RPT_EXCP_CODE IS '征信报送异常日志主键';

COMMENT ON COLUMN CREDIT_RPT_EXCP_CODE.EXCP_CODE IS '异常代码';

COMMENT ON COLUMN CREDIT_RPT_EXCP_CODE.EXCP_NUM IS '异常标号';

COMMENT ON COLUMN CREDIT_RPT_EXCP_CODE.EXCP_INFO IS '异常信息';

COMMENT ON COLUMN CREDIT_RPT_EXCP_CODE.CREATE_TIME IS '日志创建时间';

COMMENT ON COLUMN CREDIT_RPT_EXCP_CODE.CREAT_USER IS '创建人员';
