DROP TABLE DATA_PERMISSIONS_SCOPE CASCADE CONSTRAINTS;

CREATE TABLE DATA_PERMISSIONS_SCOPE
(
  DATA_PERMISSIONS_SCOPE_ID  NVARCHAR2(36)      NOT NULL,
  DATA_PERMISSIONS_TYPE_ID   NVARCHAR2(36)      NOT NULL,
  DATA_VALUE                 NVARCHAR2(100)     NOT NULL
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DATA_PERMISSIONS_SCOPE IS '数据类型范围值（每一个类型的值得范围）';

COMMENT ON COLUMN DATA_PERMISSIONS_SCOPE.DATA_PERMISSIONS_SCOPE_ID IS '主键ID';

COMMENT ON COLUMN DATA_PERMISSIONS_SCOPE.DATA_VALUE IS '值';
