DROP TABLE E_ACTU_COTRL_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_ACTU_COTRL_INF_HIST
(
  EAF_ACTU_COTRL_INF_SGMT_ID  NCHAR(32)         NOT NULL,
  ACTU_COTRL_CERT_TYPE        NCHAR(1),
  ACTU_COTRL_NAME             NVARCHAR2(80),
  ACTU_COTRL_ID_TYPE          NVARCHAR2(2),
  ACTU_COTRL_ID_NUM           NVARCHAR2(40),
  ACTU_COTRL_INFO_UPDATE      NCHAR(10),
  EAA_BS_SGMT_ID              NCHAR(32)         NOT NULL,
  RPT_DATE                    NCHAR(10),
  EXTEND1                     NVARCHAR2(100),
  EXTEND2                     NVARCHAR2(100),
  EXTEND3                     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_ACTU_COTRL_INF_HIST IS '310-企业基本信息实际控制人';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.EAF_ACTU_COTRL_INF_SGMT_ID IS '310-企业基本信息实际控制人段主键';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.ACTU_COTRL_CERT_TYPE IS '实际控制人身份类别';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.ACTU_COTRL_NAME IS '实际控制人名称';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.ACTU_COTRL_ID_TYPE IS '实际控制人身份标识类型';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.ACTU_COTRL_ID_NUM IS '实际控制人身份标识号码';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.ACTU_COTRL_INFO_UPDATE IS '信息更新日期';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.EAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_ACTU_COTRL_INF_HIST.EXTEND3 IS '预留字段3';
