DROP TABLE E_ACCT_BS_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_ACCT_BS_INF_HIST
(
  EDB_ACCT_BS_INF_SGMT_ID  NCHAR(32)            NOT NULL,
  BUSI_LINES               NCHAR(2),
  BUSI_DTL_LINES           NCHAR(2),
  OPEN_DATE                NVARCHAR2(10),
  CY                       NCHAR(3),
  ACCT_CRED_LINE           NUMBER,
  LOAN_AMT                 NUMBER,
  FLAG                     NCHAR(1),
  DUE_DATE                 NVARCHAR2(10),
  REPAY_MODE               NCHAR(2),
  REPAY_FREQCY             NCHAR(2),
  APPLY_BUSI_DIST          NCHAR(6),
  GUAR_MODE                NCHAR(1),
  OTH_REPY_GUAR_WAY        NCHAR(1),
  LOAN_TIME_LIM_CAT        NCHAR(2),
  LOA_FRM                  NCHAR(1),
  ACT_INVEST               NCHAR(5),
  FUND_SOU                 NVARCHAR2(2),
  ASSET_TRAND_FLAG         NCHAR(1),
  EDA_ACCT_BS_SGMT_ID      NCHAR(32)            NOT NULL,
  RPT_DATE                 NVARCHAR2(10),
  EXTEND1                  NVARCHAR2(100),
  EXTEND2                  NVARCHAR2(100),
  EXTEND3                  NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_ACCT_BS_INF_HIST IS '410-企业借贷账户交易基本信息段';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.EDB_ACCT_BS_INF_SGMT_ID IS '410-企业借贷账户交易基本信息段主键';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.BUSI_LINES IS '借贷业务大类';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.BUSI_DTL_LINES IS '借贷业务种类细分';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.OPEN_DATE IS '开户日期';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.CY IS '币种';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.ACCT_CRED_LINE IS '信用额度';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.LOAN_AMT IS '借款金额';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.FLAG IS '分次放款标志';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.DUE_DATE IS '到期日期';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.REPAY_MODE IS '还款方式';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.REPAY_FREQCY IS '还款频率';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.APPLY_BUSI_DIST IS '业务申请地行政区划代码';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.GUAR_MODE IS '担保方式';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.OTH_REPY_GUAR_WAY IS '其他还款保证方式';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.LOAN_TIME_LIM_CAT IS '借款期限分类';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.LOA_FRM IS '贷款发放形式';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.ACT_INVEST IS '贷款实际投向';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.FUND_SOU IS '业务经营类型';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.ASSET_TRAND_FLAG IS '资产转让标志';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.EDA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_ACCT_BS_INF_HIST.EXTEND3 IS '预留字段3';
