DROP TABLE E_ACT_LBLTY_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_ACT_LBLTY_INF_HIST
(
  EDG_ACT_LBLTY_INF_SGMT_ID  NCHAR(32)          NOT NULL,
  ACCT_STATUS                NCHAR(2),
  ACCT_BAL                   NUMBER,
  BAL_CHG_DATE               NVARCHAR2(10),
  FIVE_CATE                  NCHAR(1),
  FIVE_CATE_ADJ_DATE         NVARCHAR2(10),
  PYMT_PRD                   NUMBER,
  TOT_OVERD                  NUMBER,
  OVERD_PRINC                NUMBER,
  OVERD_DY                   NUMBER,
  LAT_RPY_DATE               NVARCHAR2(10),
  LAT_RPY_AMT                NUMBER,
  LAT_RPY_PRINC_AMT          NUMBER,
  RPMT_TYPE                  NCHAR(2),
  LAT_AGRR_RPY_DATE          NVARCHAR2(10),
  LAT_AGRR_RPY_AMT           NUMBER,
  NXT_AGRR_RPY_DATE          NVARCHAR2(10),
  CLOSE_DATE                 NVARCHAR2(10),
  EDA_ACCT_BS_SGMT_ID        NCHAR(32)          NOT NULL,
  RPT_DATE                   NVARCHAR2(10),
  EXTEND1                    NVARCHAR2(100),
  EXTEND2                    NVARCHAR2(100),
  EXTEND3                    NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_ACT_LBLTY_INF_HIST IS '410-企业借贷账户交易还款表现信息段';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.EDG_ACT_LBLTY_INF_SGMT_ID IS '410-企业借贷账户交易还款表现信息段主键';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.ACCT_STATUS IS '账户状态';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.ACCT_BAL IS '余额';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.BAL_CHG_DATE IS '余额变化日期';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.FIVE_CATE IS '五级分类';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.FIVE_CATE_ADJ_DATE IS '五级分类认定日期';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.PYMT_PRD IS '剩余还款月数';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.TOT_OVERD IS '当前逾期总额';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.OVERD_PRINC IS '当前逾期本金';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.OVERD_DY IS '当前逾期天数';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.LAT_RPY_DATE IS '最近一次实际还款日期';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.LAT_RPY_AMT IS '最近一次实际还款金额';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.LAT_RPY_PRINC_AMT IS '最近一次实际归还本金';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.RPMT_TYPE IS '还款形式';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.LAT_AGRR_RPY_DATE IS '最近一次约定还款日';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.LAT_AGRR_RPY_AMT IS '最近一次应还款金额';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.NXT_AGRR_RPY_DATE IS '下一次约定还款日期';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.CLOSE_DATE IS '账户关闭日期';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.EDA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_ACT_LBLTY_INF_HIST.EXTEND3 IS '预留字段3';
