DROP TABLE E_ACCT_SPEC_TRST_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_ACCT_SPEC_TRST_HIST
(
  EDH_ACCT_SPEC_TRST_DSPN_SG_ID  NCHAR(32)      NOT NULL,
  CHAN_TRAN_TYPE                 NCHAR(2),
  TRAN_DATE                      NVARCHAR2(10),
  TRAN_AMT                       NUMBER,
  DUE_TRAN_MON                   NUMBER,
  DET_INFO                       NVARCHAR2(200),
  EDA_ACCT_BS_SGMT_ID            NCHAR(32)      NOT NULL,
  RPT_DATE                       NVARCHAR2(10),
  EXTEND1                        NVARCHAR2(100),
  EXTEND2                        NVARCHAR2(100),
  EXTEND3                        NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_ACCT_SPEC_TRST_HIST IS '410-企业借贷账户交易特定交易说明段';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.EDH_ACCT_SPEC_TRST_DSPN_SG_ID IS '410-企业借贷账户交易特定交易说明段主键';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.CHAN_TRAN_TYPE IS '交易类型';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.TRAN_DATE IS '交易日期';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.TRAN_AMT IS '交易金额';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.DUE_TRAN_MON IS '到期日期变更月数';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.DET_INFO IS '交易明细信息';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.EDA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_ACCT_SPEC_TRST_HIST.EXTEND3 IS '预留字段3';
