DROP TABLE E_BALANCE_SHEET02 CASCADE CONSTRAINTS;

CREATE TABLE E_BALANCE_SHEET02
(
  EHB_BALANCE_SHEET2002_SGMT_ID   NCHAR(32)     NOT NULL,
  CURRENCY_FUNDS                  NUMBER,
  SHORT_TERM_INVESTMENTS          NUMBER,
  NOTES_RECEIVABLE                NUMBER,
  DIVIDENDS_RECEIVABLE            NUMBER,
  INTEREST_RECEIVABLE             NUMBER,
  ACCOUNTS_RECEIVABLE             NUMBER,
  OTHER_RECEIVABLES               NUMBER,
  PREPAYMENTS                     NUMBER,
  FUTURE_GUARANTEE                NUMBER,
  ALLOWANCE_RECEIVABLE            NUMBER,
  EXPORT_DRAWBACK_RECEIVABLE      NUMBER,
  INVENTORIES                     NUMBER,
  RAW_MATERIALS                   NUMBER,
  FINISHED_PRODUCTS               NUMBER,
  DEFERRED_EXPENSES               NUMBER,
  UNSETTLED_GLON_CURRENT_ASSETS   NUMBER,
  LONG_TERM_DEBENTURE_INVESTMENT  NUMBER,
  OTHER_CURRENT_ASSETS            NUMBER,
  TOTAL_CURRENT_ASSETS            NUMBER,
  LONG_TERM_INVESTMENT            NUMBER,
  LONG_TERM_EQUITY_INVESTMENT     NUMBER,
  LONG_TERM_SECURITIES_INVESTMEN  NUMBER,
  INCORPORATING_PRICE_DIFFERENCE  NUMBER,
  TOTAL_LONG_TERM_INVESTMENT      NUMBER,
  ORIGINAL_COST_OF_FIXED_ASSET    NUMBER,
  FIXED_ASSET_ACCUMULATED_DEPREC  NUMBER,
  FIXED_ASSETS_NET_VALUE          NUMBER,
  PROVISION_FORIMPAIRMENT_OF_FIX  NUMBER,
  NET_VALUE_OF_FIXED_ASSETS       NUMBER,
  FIXED_ASSETS_PENDING_FOR_DISPO  NUMBER,
  CONSTRUCTION_MATERIALS          NUMBER,
  CONSTRUCTIONIN_PROGRESS         NUMBER,
  UNSETTLED_GL_ON_FIXED_ASSETS    NUMBER,
  TOTAL_FIXED_ASSETS              NUMBER,
  INTANGIBLE_ASSETS               NUMBER,
  LAND_USE_RIGHTS                 NUMBER,
  DEFERRED_ASSETS                 NUMBER,
  INCLUDING_FIXED_ASSETS_REPAIR   NUMBER,
  IMPROVEMENT_EXPENDITURE_OF_FIX  NUMBER,
  OTHER_LONG_TERM_ASSETS          NUMBER,
  AMONG_IT_SPECIALLY_APPROVED_RE  NUMBER,
  TOTALINTANGIBLE_ASSETS_AND_OTH  NUMBER,
  DEFERRED_ASSETS_DEBITS          NUMBER,
  TOTAL_ASSETS                    NUMBER,
  SHORT_TERM_BORROWINGS           NUMBER,
  NOTES_PAYABLE                   NUMBER,
  ACCOUNTS_PAYABLE                NUMBER,
  RECEIPTSIN_ADVANCE              NUMBER,
  WAGES_OR_SALARIES_PAYABLES      NUMBER,
  EMPLOYEE_BENEFITS               NUMBER,
  INCOME_PAYABLE                  NUMBER,
  TAXES_PAYABLE                   NUMBER,
  OTHER_PAYABLE_TO_GOVERNMENT     NUMBER,
  OTHER_PAYABLE                   NUMBER,
  PROVISION_FOR_EXPENSES          NUMBER,
  PROVISIONS                      NUMBER,
  LONG_TERM_LIABILITIES_DUE_WITH  NUMBER,
  OTHER_CURRENT_LIABILITIES       NUMBER,
  TOTAL_CURRENT_LIABILITIES       NUMBER,
  LONG_TERM_BORROWINGS            NUMBER,
  BONDS_PAYABLE                   NUMBER,
  LONG_TERM_PAYABLES              NUMBER,
  GRANTS_PAYABLE                  NUMBER,
  OTHER_LONG_TERM_LIABILITIES     NUMBER,
  SPECIAL_RESERVE_FUND            NUMBER,
  TOTAL_LONG_TERM_LIABILITIES     NUMBER,
  DEFERRED_TAXATION_CREDIT        NUMBER,
  TOTALLIABILITIES                NUMBER,
  MINORITY_INTEREST               NUMBER,
  PAIDIN_CAPITAL                  NUMBER,
  NATIONAL_CAPITAL                NUMBER,
  COLLECTIVE_CAPITAL              NUMBER,
  LEGAL_PERSONS_CAPITAL           NUMBER,
  STATE_OWNED_LEGAL_PERSONS_CAPI  NUMBER,
  COLLECTIVE_LEGAL_PERSONS_CAPIT  NUMBER,
  PERSONAL_CAPITAL                NUMBER,
  FOREIGN_BUSINESSMENS_CAPITAL    NUMBER,
  CAPITALR_RSERVE                 NUMBER,
  SURPLUS_RESERVE                 NUMBER,
  STATUTORY_SURPLUS_RESERVE       NUMBER,
  PUBLIC_WELFARE_FUND             NUMBER,
  SUPPLERMENTARY_CURRENT_CAPITAL  NUMBER,
  UNAFFIRMEDINVESTMENT_LOSS       NUMBER,
  UNAPPROPRIATED_PROFIT           NUMBER,
  DIFFERENCE_ON_TRANSLATION_OF_F  NUMBER,
  TOTAL_EQUITY                    NUMBER,
  TOTAL_EQUITY_AND_LIABILITIES    NUMBER,
  EHA_BALANCE_SHEET_BS_SGMT_ID    NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_BALANCE_SHEET02 IS '610-企业资产负债表02资产负债表段';

COMMENT ON COLUMN E_BALANCE_SHEET02.EHB_BALANCE_SHEET2002_SGMT_ID IS '610-企业资产负债表02资产负债表段主键';

COMMENT ON COLUMN E_BALANCE_SHEET02.CURRENCY_FUNDS IS '货币资金';

COMMENT ON COLUMN E_BALANCE_SHEET02.SHORT_TERM_INVESTMENTS IS '短期投资';

COMMENT ON COLUMN E_BALANCE_SHEET02.NOTES_RECEIVABLE IS '应收票据';

COMMENT ON COLUMN E_BALANCE_SHEET02.DIVIDENDS_RECEIVABLE IS '应收股利';

COMMENT ON COLUMN E_BALANCE_SHEET02.INTEREST_RECEIVABLE IS '应收利息';

COMMENT ON COLUMN E_BALANCE_SHEET02.ACCOUNTS_RECEIVABLE IS '应收账款';

COMMENT ON COLUMN E_BALANCE_SHEET02.OTHER_RECEIVABLES IS '其他应收款';

COMMENT ON COLUMN E_BALANCE_SHEET02.PREPAYMENTS IS '预付账款';

COMMENT ON COLUMN E_BALANCE_SHEET02.FUTURE_GUARANTEE IS '期货保证金';

COMMENT ON COLUMN E_BALANCE_SHEET02.ALLOWANCE_RECEIVABLE IS '应收补贴款';

COMMENT ON COLUMN E_BALANCE_SHEET02.EXPORT_DRAWBACK_RECEIVABLE IS '应收出口退税';

COMMENT ON COLUMN E_BALANCE_SHEET02.INVENTORIES IS '存货';

COMMENT ON COLUMN E_BALANCE_SHEET02.RAW_MATERIALS IS '存货原材料';

COMMENT ON COLUMN E_BALANCE_SHEET02.FINISHED_PRODUCTS IS '存货产成品 ';

COMMENT ON COLUMN E_BALANCE_SHEET02.DEFERRED_EXPENSES IS '待摊费用';

COMMENT ON COLUMN E_BALANCE_SHEET02.UNSETTLED_GLON_CURRENT_ASSETS IS '待处理流动资产净损失';

COMMENT ON COLUMN E_BALANCE_SHEET02.LONG_TERM_DEBENTURE_INVESTMENT IS '一年内到期的长期债权投资';

COMMENT ON COLUMN E_BALANCE_SHEET02.OTHER_CURRENT_ASSETS IS '其他流动资产';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_CURRENT_ASSETS IS '流动资产合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.LONG_TERM_INVESTMENT IS '长期投资';

COMMENT ON COLUMN E_BALANCE_SHEET02.LONG_TERM_EQUITY_INVESTMENT IS '长期股权投资';

COMMENT ON COLUMN E_BALANCE_SHEET02.LONG_TERM_SECURITIES_INVESTMEN IS '长期债权投资';

COMMENT ON COLUMN E_BALANCE_SHEET02.INCORPORATING_PRICE_DIFFERENCE IS '合并价差';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_LONG_TERM_INVESTMENT IS '长期投资合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.ORIGINAL_COST_OF_FIXED_ASSET IS '固定资产原价';

COMMENT ON COLUMN E_BALANCE_SHEET02.FIXED_ASSET_ACCUMULATED_DEPREC IS '累计折旧';

COMMENT ON COLUMN E_BALANCE_SHEET02.FIXED_ASSETS_NET_VALUE IS '固定资产净值';

COMMENT ON COLUMN E_BALANCE_SHEET02.PROVISION_FORIMPAIRMENT_OF_FIX IS '固定资产值减值准备';

COMMENT ON COLUMN E_BALANCE_SHEET02.NET_VALUE_OF_FIXED_ASSETS IS '固定资产净额';

COMMENT ON COLUMN E_BALANCE_SHEET02.FIXED_ASSETS_PENDING_FOR_DISPO IS '固定资产清理';

COMMENT ON COLUMN E_BALANCE_SHEET02.CONSTRUCTION_MATERIALS IS '工程物资';

COMMENT ON COLUMN E_BALANCE_SHEET02.CONSTRUCTIONIN_PROGRESS IS '在建工程';

COMMENT ON COLUMN E_BALANCE_SHEET02.UNSETTLED_GL_ON_FIXED_ASSETS IS '待处理固定资产净损失';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_FIXED_ASSETS IS '固定资产合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.INTANGIBLE_ASSETS IS '无形资产';

COMMENT ON COLUMN E_BALANCE_SHEET02.LAND_USE_RIGHTS IS '（无形资产科目下）土地使用权';

COMMENT ON COLUMN E_BALANCE_SHEET02.DEFERRED_ASSETS IS '递延资产';

COMMENT ON COLUMN E_BALANCE_SHEET02.INCLUDING_FIXED_ASSETS_REPAIR IS '（递延资产科目下）固定资产修理';

COMMENT ON COLUMN E_BALANCE_SHEET02.IMPROVEMENT_EXPENDITURE_OF_FIX IS '（递延资产科目下）固定资产改良支出';

COMMENT ON COLUMN E_BALANCE_SHEET02.OTHER_LONG_TERM_ASSETS IS '其他长期资产';

COMMENT ON COLUMN E_BALANCE_SHEET02.AMONG_IT_SPECIALLY_APPROVED_RE IS '（其他长期资产科目下）特准储备物资';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTALINTANGIBLE_ASSETS_AND_OTH IS '无形及其他资产合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.DEFERRED_ASSETS_DEBITS IS '递延税款借项';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_ASSETS IS '资产总计';

COMMENT ON COLUMN E_BALANCE_SHEET02.SHORT_TERM_BORROWINGS IS '短期借款';

COMMENT ON COLUMN E_BALANCE_SHEET02.NOTES_PAYABLE IS '应付票据';

COMMENT ON COLUMN E_BALANCE_SHEET02.ACCOUNTS_PAYABLE IS '应付账款';

COMMENT ON COLUMN E_BALANCE_SHEET02.RECEIPTSIN_ADVANCE IS '预收账款';

COMMENT ON COLUMN E_BALANCE_SHEET02.WAGES_OR_SALARIES_PAYABLES IS '应付工资';

COMMENT ON COLUMN E_BALANCE_SHEET02.EMPLOYEE_BENEFITS IS '应付福利费';

COMMENT ON COLUMN E_BALANCE_SHEET02.INCOME_PAYABLE IS '应付利润';

COMMENT ON COLUMN E_BALANCE_SHEET02.TAXES_PAYABLE IS '应交税金';

COMMENT ON COLUMN E_BALANCE_SHEET02.OTHER_PAYABLE_TO_GOVERNMENT IS '其他应交款';

COMMENT ON COLUMN E_BALANCE_SHEET02.OTHER_PAYABLE IS '其他应付款';

COMMENT ON COLUMN E_BALANCE_SHEET02.PROVISION_FOR_EXPENSES IS '预提费用';

COMMENT ON COLUMN E_BALANCE_SHEET02.PROVISIONS IS '预计负债';

COMMENT ON COLUMN E_BALANCE_SHEET02.LONG_TERM_LIABILITIES_DUE_WITH IS '一年内到期的长期负债';

COMMENT ON COLUMN E_BALANCE_SHEET02.OTHER_CURRENT_LIABILITIES IS '其他流动负债';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_CURRENT_LIABILITIES IS '流动负债合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.LONG_TERM_BORROWINGS IS '长期借款';

COMMENT ON COLUMN E_BALANCE_SHEET02.BONDS_PAYABLE IS '应付债券';

COMMENT ON COLUMN E_BALANCE_SHEET02.LONG_TERM_PAYABLES IS '长期应付款';

COMMENT ON COLUMN E_BALANCE_SHEET02.GRANTS_PAYABLE IS '专项应付款';

COMMENT ON COLUMN E_BALANCE_SHEET02.OTHER_LONG_TERM_LIABILITIES IS '其他长期负债';

COMMENT ON COLUMN E_BALANCE_SHEET02.SPECIAL_RESERVE_FUND IS '（其他长期负债科目下）特准储备基金';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_LONG_TERM_LIABILITIES IS '长期负债合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.DEFERRED_TAXATION_CREDIT IS '递延税款贷项';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTALLIABILITIES IS '负债合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.MINORITY_INTEREST IS '少数股东权益';

COMMENT ON COLUMN E_BALANCE_SHEET02.PAIDIN_CAPITAL IS '实收资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.NATIONAL_CAPITAL IS '国家资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.COLLECTIVE_CAPITAL IS '集体资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.LEGAL_PERSONS_CAPITAL IS '法人资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.STATE_OWNED_LEGAL_PERSONS_CAPI IS '（法人资本科目下）国有法人资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.COLLECTIVE_LEGAL_PERSONS_CAPIT IS '（法人资本科目下）集体法人资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.PERSONAL_CAPITAL IS '个人资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.FOREIGN_BUSINESSMENS_CAPITAL IS '外商资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.CAPITALR_RSERVE IS '资本公积';

COMMENT ON COLUMN E_BALANCE_SHEET02.SURPLUS_RESERVE IS '盈余公积';

COMMENT ON COLUMN E_BALANCE_SHEET02.STATUTORY_SURPLUS_RESERVE IS '（盈余公积科目下）法定盈余公积';

COMMENT ON COLUMN E_BALANCE_SHEET02.PUBLIC_WELFARE_FUND IS '（盈余公积科目下）公益金';

COMMENT ON COLUMN E_BALANCE_SHEET02.SUPPLERMENTARY_CURRENT_CAPITAL IS '（盈余公积科目下）补充流动资本';

COMMENT ON COLUMN E_BALANCE_SHEET02.UNAFFIRMEDINVESTMENT_LOSS IS '未确认的投资损失';

COMMENT ON COLUMN E_BALANCE_SHEET02.UNAPPROPRIATED_PROFIT IS '未分配利润';

COMMENT ON COLUMN E_BALANCE_SHEET02.DIFFERENCE_ON_TRANSLATION_OF_F IS '外币报表折算差额';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_EQUITY IS '所有者权益合计';

COMMENT ON COLUMN E_BALANCE_SHEET02.TOTAL_EQUITY_AND_LIABILITIES IS '负债和所有者权益总计';

COMMENT ON COLUMN E_BALANCE_SHEET02.EHA_BALANCE_SHEET_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_BALANCE_SHEET02.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_BALANCE_SHEET02.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_BALANCE_SHEET02.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_BALANCE_SHEET02.EXTEND3 IS '预留字段3';
