DROP TABLE E_BALANCE_SHEET07 CASCADE CONSTRAINTS;

CREATE TABLE E_BALANCE_SHEET07
(
  EHC_BALANCE_SHEET2007_SGMT_ID   NCHAR(32)     NOT NULL,
  CURRENCY_FUNDS                  NUMBER,
  FINANCIAL_ASSETS_HELD_FOR_TRAD  NUMBER,
  NOTES_RECEIVABLE                NUMBER,
  ACCOUNTS_RECEIVABLE             NUMBER,
  PREPAYMENTS                     NUMBER,
  INTEREST_RECEIVABLE             NUMBER,
  DIVIDENDS_RECEIVABLE            NUMBER,
  OTHER_RECEIVABLES               NUMBER,
  INVENTORIES                     NUMBER,
  CURRENT_PORTION_OF_NON_CURRENT  NUMBER,
  OTHER_CURRENT_ASSETS            NUMBER,
  TOTAL_CURRENT_ASSETS            NUMBER,
  FINANCIAL_ASSETS_AVAILABLE_FOR  NUMBER,
  HELD_TO_MATURITY_INVESTMENTS    NUMBER,
  LONG_TERM_EQUITY_INVESTMENT     NUMBER,
  LONG_TERM_RECEIVABLES           NUMBER,
  INVESTMENT_PROPERTIES           NUMBER,
  FIXED_ASSETS                    NUMBER,
  CONSTRUCTION_IN_PROGRESS        NUMBER,
  CONSTRUCTION_MATERIALS          NUMBER,
  FIXED_ASSETS_PENDING_FOR_DISPO  NUMBER,
  NON_CURRENT_BIOLOGICAL_ASSETS   NUMBER,
  OIL_AND_GAS_ASSETS              NUMBER,
  INTANGIBLE_ASSETS               NUMBER,
  DEVELOPMENT_DISBURSEMENTS       NUMBER,
  GOOD_WILL                       NUMBER,
  LONG_TERM_DEFERRED_EXPENSES     NUMBER,
  DEFERRED_TAX_ASSETS             NUMBER,
  OTHER_NON_CURRENT_ASSETS        NUMBER,
  TOTAL_NON_CURRENT_ASSETS        NUMBER,
  TOTAL_ASSETS                    NUMBER,
  SHORT_TERM_BORROWINGS           NUMBER,
  FINANCIAL_LIABILITIES_HELD_FOR  NUMBER,
  NOTES_PAYABLE                   NUMBER,
  ACCOUNTS_PAYABLE                NUMBER,
  RECEIPTSIN_ADVANCE              NUMBER,
  INTEREST_PAYABLE                NUMBER,
  EMPLOYEE_BENEFITS_PAYABLE       NUMBER,
  TAXS_PAYABLE                    NUMBER,
  DIVIDENDS_PAYABLE               NUMBER,
  OTHER_PAYABLES                  NUMBER,
  CURRENT_PORTION_OF_LONG_TERM_L  NUMBER,
  OTHER_CURRENT_LIABILITIES       NUMBER,
  TOTAL_CURRENT_LIABILITIES       NUMBER,
  LONG_TERM_BORROWINGS            NUMBER,
  BONDS_PAYABLES                  NUMBER,
  LONG_TERM_PAYABLES              NUMBER,
  GRANTS_PAYABLE                  NUMBER,
  PROVISIONS                      NUMBER,
  DEFERRED_TAX_LIABILITIES        NUMBER,
  OTHER_NON_CURRENT_LIABILITIES   NUMBER,
  TOTAL_NON_CURRENT_LIABILITIES   NUMBER,
  TOTAL_LIABILITIES               NUMBER,
  PAIDIN_CAPITAL_OR_SHARE_CAPITA  NUMBER,
  CAPITALR_RSERVE                 NUMBER,
  LESS_TREASURY_STOCKS            NUMBER,
  SURPLUS_RESERVE                 NUMBER,
  UNAPPROPRIATED_PROFIT           NUMBER,
  TOTAL_EQUITY                    NUMBER,
  TOTAL_EQUITY_AND_LIABILITIES    NUMBER,
  EHA_BALANCE_SHEET_BS_SGMT_ID    NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_BALANCE_SHEET07 IS '610-企业资产负债表07资产负债表段';

COMMENT ON COLUMN E_BALANCE_SHEET07.EHC_BALANCE_SHEET2007_SGMT_ID IS '610-企业资产负债表07资产负债表段主键';

COMMENT ON COLUMN E_BALANCE_SHEET07.CURRENCY_FUNDS IS '货币资金';

COMMENT ON COLUMN E_BALANCE_SHEET07.FINANCIAL_ASSETS_HELD_FOR_TRAD IS '交易性金融资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.NOTES_RECEIVABLE IS '应收票据';

COMMENT ON COLUMN E_BALANCE_SHEET07.ACCOUNTS_RECEIVABLE IS '应收账款';

COMMENT ON COLUMN E_BALANCE_SHEET07.PREPAYMENTS IS '预付账款';

COMMENT ON COLUMN E_BALANCE_SHEET07.INTEREST_RECEIVABLE IS '应收利息';

COMMENT ON COLUMN E_BALANCE_SHEET07.DIVIDENDS_RECEIVABLE IS '应收股利';

COMMENT ON COLUMN E_BALANCE_SHEET07.OTHER_RECEIVABLES IS '其他应收款';

COMMENT ON COLUMN E_BALANCE_SHEET07.INVENTORIES IS '存货';

COMMENT ON COLUMN E_BALANCE_SHEET07.CURRENT_PORTION_OF_NON_CURRENT IS '一年内到期的非流动资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.OTHER_CURRENT_ASSETS IS '其他流动资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_CURRENT_ASSETS IS '流动资产合计';

COMMENT ON COLUMN E_BALANCE_SHEET07.FINANCIAL_ASSETS_AVAILABLE_FOR IS '可供出售的金融资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.HELD_TO_MATURITY_INVESTMENTS IS '持有至到期投资';

COMMENT ON COLUMN E_BALANCE_SHEET07.LONG_TERM_EQUITY_INVESTMENT IS '长期股权投资';

COMMENT ON COLUMN E_BALANCE_SHEET07.LONG_TERM_RECEIVABLES IS '长期应收款';

COMMENT ON COLUMN E_BALANCE_SHEET07.INVESTMENT_PROPERTIES IS '投资性房地产';

COMMENT ON COLUMN E_BALANCE_SHEET07.FIXED_ASSETS IS '固定资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.CONSTRUCTION_IN_PROGRESS IS '在建工程';

COMMENT ON COLUMN E_BALANCE_SHEET07.CONSTRUCTION_MATERIALS IS '工程物资';

COMMENT ON COLUMN E_BALANCE_SHEET07.FIXED_ASSETS_PENDING_FOR_DISPO IS '固定资产清理';

COMMENT ON COLUMN E_BALANCE_SHEET07.NON_CURRENT_BIOLOGICAL_ASSETS IS '生产性生物资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.OIL_AND_GAS_ASSETS IS '油气资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.INTANGIBLE_ASSETS IS '无形资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.DEVELOPMENT_DISBURSEMENTS IS '开发支出';

COMMENT ON COLUMN E_BALANCE_SHEET07.GOOD_WILL IS '商誉';

COMMENT ON COLUMN E_BALANCE_SHEET07.LONG_TERM_DEFERRED_EXPENSES IS '长期待摊费用';

COMMENT ON COLUMN E_BALANCE_SHEET07.DEFERRED_TAX_ASSETS IS '递延所得税资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.OTHER_NON_CURRENT_ASSETS IS '其他非流动资产';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_NON_CURRENT_ASSETS IS '非流动资产合计';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_ASSETS IS '资产总计';

COMMENT ON COLUMN E_BALANCE_SHEET07.SHORT_TERM_BORROWINGS IS '短期借款';

COMMENT ON COLUMN E_BALANCE_SHEET07.FINANCIAL_LIABILITIES_HELD_FOR IS '交易性金融负债';

COMMENT ON COLUMN E_BALANCE_SHEET07.NOTES_PAYABLE IS '应付票据';

COMMENT ON COLUMN E_BALANCE_SHEET07.ACCOUNTS_PAYABLE IS '应付账款';

COMMENT ON COLUMN E_BALANCE_SHEET07.RECEIPTSIN_ADVANCE IS '预收账款';

COMMENT ON COLUMN E_BALANCE_SHEET07.INTEREST_PAYABLE IS '应付利息';

COMMENT ON COLUMN E_BALANCE_SHEET07.EMPLOYEE_BENEFITS_PAYABLE IS '应付职工薪酬';

COMMENT ON COLUMN E_BALANCE_SHEET07.TAXS_PAYABLE IS '应交税费';

COMMENT ON COLUMN E_BALANCE_SHEET07.DIVIDENDS_PAYABLE IS '应付股利';

COMMENT ON COLUMN E_BALANCE_SHEET07.OTHER_PAYABLES IS '其他应付款';

COMMENT ON COLUMN E_BALANCE_SHEET07.CURRENT_PORTION_OF_LONG_TERM_L IS '一年内到期的非流动负债';

COMMENT ON COLUMN E_BALANCE_SHEET07.OTHER_CURRENT_LIABILITIES IS '其他流动负债';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_CURRENT_LIABILITIES IS '流动负债合计';

COMMENT ON COLUMN E_BALANCE_SHEET07.LONG_TERM_BORROWINGS IS '长期借款';

COMMENT ON COLUMN E_BALANCE_SHEET07.BONDS_PAYABLES IS '应付债券';

COMMENT ON COLUMN E_BALANCE_SHEET07.LONG_TERM_PAYABLES IS '长期应付款';

COMMENT ON COLUMN E_BALANCE_SHEET07.GRANTS_PAYABLE IS '专项应付款';

COMMENT ON COLUMN E_BALANCE_SHEET07.PROVISIONS IS '预计负债';

COMMENT ON COLUMN E_BALANCE_SHEET07.DEFERRED_TAX_LIABILITIES IS '递延所得税负债';

COMMENT ON COLUMN E_BALANCE_SHEET07.OTHER_NON_CURRENT_LIABILITIES IS '其他非流动负债';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_NON_CURRENT_LIABILITIES IS '非流动负债合计';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_LIABILITIES IS '负债合计';

COMMENT ON COLUMN E_BALANCE_SHEET07.PAIDIN_CAPITAL_OR_SHARE_CAPITA IS '实收资本（或股本）';

COMMENT ON COLUMN E_BALANCE_SHEET07.CAPITALR_RSERVE IS '资本公积';

COMMENT ON COLUMN E_BALANCE_SHEET07.LESS_TREASURY_STOCKS IS '减：库存股';

COMMENT ON COLUMN E_BALANCE_SHEET07.SURPLUS_RESERVE IS '盈余公积';

COMMENT ON COLUMN E_BALANCE_SHEET07.UNAPPROPRIATED_PROFIT IS '未分配利润';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_EQUITY IS '所有者权益合计';

COMMENT ON COLUMN E_BALANCE_SHEET07.TOTAL_EQUITY_AND_LIABILITIES IS '负债和所有者权益合计';

COMMENT ON COLUMN E_BALANCE_SHEET07.EHA_BALANCE_SHEET_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_BALANCE_SHEET07.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_BALANCE_SHEET07.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_BALANCE_SHEET07.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_BALANCE_SHEET07.EXTEND3 IS '预留字段3';
