DROP TABLE E_BALANCE_SHEET_BS CASCADE CONSTRAINTS;

CREATE TABLE E_BALANCE_SHEET_BS
(
  EHA_BALANCE_SHEET_BS_SGMT_ID  NCHAR(32)       NOT NULL,
  INF_REC_TYPE                  NCHAR(3),
  ENT_NAME                      NVARCHAR2(80),
  ENT_CERT_TYPE                 NVARCHAR2(2),
  ENT_CERT_NUM                  NVARCHAR2(40),
  RPT_DATE                      NCHAR(10),
  SHEET_YEAR                    NCHAR(4),
  SHEET_TYPE                    NCHAR(2),
  SHEET_TYPE_DIVIDE             NCHAR(1),
  AUDIT_FIRM_NAME               NVARCHAR2(80),
  AUDITOR_NAME                  NVARCHAR2(30),
  AUDIT_TIME                    NVARCHAR2(10),
  CIMOC                         NCHAR(14),
  RPT_DATE_CODE                 NCHAR(2),
  LAST_UPDATE_TIME              NVARCHAR2(10),
  OPERATOR_USER                 NVARCHAR2(50),
  ORG_NAME                      NVARCHAR2(100),
  ORG_CODE                      NVARCHAR2(100),
  BUSINESS_STATES               NVARCHAR2(50),
  REJECT_REASON                 NVARCHAR2(255),
  IS_FILTER                     NCHAR(1),
  REPORT_MESSAGE_ID             NVARCHAR2(60),
  EXTEND1                       NVARCHAR2(100),
  EXTEND2                       NVARCHAR2(100),
  EXTEND3                       NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_BALANCE_SHEET_BS IS '610-企业资产负债表基础段';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.EHA_BALANCE_SHEET_BS_SGMT_ID IS '610-企业资产负债表基础段主键';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.ENT_NAME IS '企业名称';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.ENT_CERT_TYPE IS '企业身份标识类型';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.ENT_CERT_NUM IS '企业身份标识号码';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.RPT_DATE IS '信息报告日期';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.SHEET_YEAR IS '报表年份';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.SHEET_TYPE IS '报表类型';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.SHEET_TYPE_DIVIDE IS '报表类型细分';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.AUDIT_FIRM_NAME IS '审计事务所名称';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.AUDITOR_NAME IS '审计人员名称';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.AUDIT_TIME IS '审计时间';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.CIMOC IS '客户资料维护机构代码';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.RPT_DATE_CODE IS '报告时点说明代码';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_BALANCE_SHEET_BS.EXTEND3 IS '预留字段3';
