DROP TABLE E_BS_MIDDLE CASCADE CONSTRAINTS;

CREATE TABLE E_BS_MIDDLE
(
  ENT_CERT_TYPE  NVARCHAR2(36)                  NOT NULL,
  ENT_CERT_NUM   NVARCHAR2(60)                  NOT NULL,
  EXTEND1        NVARCHAR2(100),
  EXTEND2        NVARCHAR2(100),
  EXTEND3        NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_BS_MIDDLE IS '310-企业基本信息基础段中间表';

COMMENT ON COLUMN E_BS_MIDDLE.ENT_CERT_TYPE IS '企业身份标识类型';

COMMENT ON COLUMN E_BS_MIDDLE.ENT_CERT_NUM IS '企业身份标识号码';

COMMENT ON COLUMN E_BS_MIDDLE.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_BS_MIDDLE.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_BS_MIDDLE.EXTEND3 IS '预留字段3';
