DROP TABLE E_CASH_FLOWS2002_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_CASH_FLOWS2002_HIST
(
  EJB_CASH_FLOWS2002_SGMT_ID      NCHAR(32)     NOT NULL,
  CASH_RECEIVED_FROM_SALES_OF_GO  NUMBER,
  TAX_REFUNDS                     NUMBER,
  OTHER_CASH_RECEIVED_RELATING_T  NUMBER,
  TOTAL_CASH_INFLOWS_FROM_OPERAT  NUMBER,
  CASH_PAID_FOR_GOODS_AND_SERVIC  NUMBER,
  CASH_PAID_TO_AND_ON_BEHALF_OF_  NUMBER,
  PAYMENTS_OF_ALL_TYPES_OF_TAXES  NUMBER,
  OTHER_CASH_PAYMENTS_FROM_OPERA  NUMBER,
  TOTAL_CASH_OUTFLOWS_FROM_OPERA  NUMBER,
  NET_CASH_FLOWS_FROM_OPERATING   NUMBER,
  CASH_RECEIVED_FROM_RETURN_OF_I  NUMBER,
  CASH_RECEIVED_FROM_ONVESTMENTS  NUMBER,
  NET_CASH_RECEIVED_FROM_DISPOSA  NUMBER,
  CASH_RECEIVED_RELATING_TO_OTHE  NUMBER,
  TOTAL_CASH_INFLOWS_FROM_INVEST  NUMBER,
  CASH_PAID_TO_ACQUIRE_FIXED_ASS  NUMBER,
  CASH_PAYMENTS_FOR_INVESTMENTS   NUMBER,
  CASH_PAYMENTS_RELATED_TO_OTH_T  NUMBER,
  TOTAL_CASH_OUTFLOWS_FROM_INVES  NUMBER,
  NET_CASH_FLOWS_FROM_INVESTING_  NUMBER,
  CASH_RECEIVED_FROM_INVESTORS    NUMBER,
  CASH_FROM_BORROWINGS            NUMBER,
  OTHER_CASH_RECEIVED_RELATING_C  NUMBER,
  TOTAL_CASH_INFLOWS_FROM_FINANC  NUMBER,
  CASH_REPAYMENTS_FOR_DEBTS       NUMBER,
  CASH_PAYMENTS_FOR_DISTRIBUTION  NUMBER,
  CASH_PAYMENTS_RELATED_TO_OTH_C  NUMBER,
  TOTAL_CASH_OUTFLOWS_FROM_FINAN  NUMBER,
  NET_CASH_FLOWS_FROM_FINANCING_  NUMBER,
  EFFECT_OF_EXCHANG_RATE_CHANGES  NUMBER,
  NET_INCREASEIN_CASH_AND_CASH_E  NUMBER,
  NET_PROFIT                      NUMBER,
  PROVISION_FOR_ASSETS            NUMBER,
  DEPRECIATION_OF_FIXED_ASSETS    NUMBER,
  AMORTISATION_OF_INTANGIBLE_ASS  NUMBER,
  LONG_TERM_DEFERRED_EXPENSES_AM  NUMBER,
  DECREASE_OF_DEFFERED_EXPENSES   NUMBER,
  ADDITION_OF_ACCUED_EXPENSE      NUMBER,
  LOSSES_ON_DISPOSAL_OF_FIXED_AS  NUMBER,
  LOSSES_ON_SCRAPPING_OF_FIXED_A  NUMBER,
  FINANCE_EXPENSE                 NUMBER,
  LOSSES_ARSING_FROM_INVESTMENT   NUMBER,
  DEFERRED_TAX_CREDIT             NUMBER,
  DECREASE_IN_INVENTORIES         NUMBER,
  DECREASEIN_OPERATING_RECEIVABL  NUMBER,
  INCREASEIN_OPERATING_RECEIVABL  NUMBER,
  OTHERS                          NUMBER,
  NET_CASH_FLOWS_FROM_OPERATING2  NUMBER,
  DEBTS_TRANSFER_TO_CAPITAL       NUMBER,
  ONE_YEAR_DUE_CONVERTIBLE_BONDS  NUMBER,
  FINANCING_RENT_TO_THE_FIXED_AS  NUMBER,
  NON_CASH_OTHERS                 NUMBER,
  CASH_AT_THE_END_OF_PERIOD       NUMBER,
  CASH_AT_THE_BEGINNING_OF_THE_P  NUMBER,
  CASH_EQUIVALENTS_AT_THE_END_OF  NUMBER,
  CASH_RQUIVALENTS_AT_THE_BEGINN  NUMBER,
  NET_INCREASE_IN_CASH_AND_CASH_  NUMBER,
  EJA_CASH_FLOWS_BS_SGMT_ID       NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_CASH_FLOWS2002_HIST IS '630-企业现金流量表02现金流量表段';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.EJB_CASH_FLOWS2002_SGMT_ID IS '630-企业现金流量表02现金流量表段主键';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_RECEIVED_FROM_SALES_OF_GO IS '销售商品和提供劳务收到的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.TAX_REFUNDS IS '收到的税费返还';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.OTHER_CASH_RECEIVED_RELATING_T IS '收到的其他与经营活动有关的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.TOTAL_CASH_INFLOWS_FROM_OPERAT IS '经营活动现金流入小计';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_PAID_FOR_GOODS_AND_SERVIC IS '购买商品、接受劳务支付的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_PAID_TO_AND_ON_BEHALF_OF_ IS '支付给职工以及为职工支付的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.PAYMENTS_OF_ALL_TYPES_OF_TAXES IS '支付的各项税费';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.OTHER_CASH_PAYMENTS_FROM_OPERA IS '支付的其他与经营活动有关的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.TOTAL_CASH_OUTFLOWS_FROM_OPERA IS '经营活动现金流出小计';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_CASH_FLOWS_FROM_OPERATING IS '经营活动产生的现金流量净额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_RECEIVED_FROM_RETURN_OF_I IS '收回投资所收到的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_RECEIVED_FROM_ONVESTMENTS IS '取得投资收益所收到的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_CASH_RECEIVED_FROM_DISPOSA IS '处置固定资产无形资产和其他长期资产所收回的现金净额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_RECEIVED_RELATING_TO_OTHE IS '收到的其他与投资活动有关的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.TOTAL_CASH_INFLOWS_FROM_INVEST IS '投资活动现金流入小计';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_PAID_TO_ACQUIRE_FIXED_ASS IS '购建固定资产无形资产和其他长期资产所支付的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_PAYMENTS_FOR_INVESTMENTS IS '投资所支付的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_PAYMENTS_RELATED_TO_OTH_T IS '支付的其他与投资活动有关的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.TOTAL_CASH_OUTFLOWS_FROM_INVES IS '投资活动现金流出小计';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_CASH_FLOWS_FROM_INVESTING_ IS '投资活动产生的现金流量净额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_RECEIVED_FROM_INVESTORS IS '吸收投资所收到的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_FROM_BORROWINGS IS '借款所收到的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.OTHER_CASH_RECEIVED_RELATING_C IS '收到的其他与筹资活动有关的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.TOTAL_CASH_INFLOWS_FROM_FINANC IS '筹资活动现金流入小计';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_REPAYMENTS_FOR_DEBTS IS '偿还债务所支付的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_PAYMENTS_FOR_DISTRIBUTION IS '分配股利、利润或偿付利息所支付的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_PAYMENTS_RELATED_TO_OTH_C IS '支付的其他与筹资活动有关的现金';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.TOTAL_CASH_OUTFLOWS_FROM_FINAN IS '筹资活动现金流出小计';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_CASH_FLOWS_FROM_FINANCING_ IS '筹集活动产生的现金流量净额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.EFFECT_OF_EXCHANG_RATE_CHANGES IS '汇率变动对现金的影响';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_INCREASEIN_CASH_AND_CASH_E IS '现金及现金等价物净增加额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_PROFIT IS '净利润';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.PROVISION_FOR_ASSETS IS '计提的资产减值准备';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.DEPRECIATION_OF_FIXED_ASSETS IS '固定资产拆旧';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.AMORTISATION_OF_INTANGIBLE_ASS IS '无形资产摊销';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.LONG_TERM_DEFERRED_EXPENSES_AM IS '长期待摊费用摊销';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.DECREASE_OF_DEFFERED_EXPENSES IS '待摊费用减少';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.ADDITION_OF_ACCUED_EXPENSE IS '预提费用增加';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.LOSSES_ON_DISPOSAL_OF_FIXED_AS IS '处置固定资产无形资产和其他长期资产的损失';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.LOSSES_ON_SCRAPPING_OF_FIXED_A IS '固定资产报废损失';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.FINANCE_EXPENSE IS '财务费用';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.LOSSES_ARSING_FROM_INVESTMENT IS '投资损失';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.DEFERRED_TAX_CREDIT IS '递延税款贷项';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.DECREASE_IN_INVENTORIES IS '存货的减少';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.DECREASEIN_OPERATING_RECEIVABL IS '经营性应收项目的减少';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.INCREASEIN_OPERATING_RECEIVABL IS '经营性应付项目的增加';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.OTHERS IS '（净利润调节为经营活动现金流量科目下）其他';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_CASH_FLOWS_FROM_OPERATING2 IS '经营活动产生的现金流量净额2';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.DEBTS_TRANSFER_TO_CAPITAL IS '债务转为资本';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.ONE_YEAR_DUE_CONVERTIBLE_BONDS IS '一年内到期的可转换公司债券';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.FINANCING_RENT_TO_THE_FIXED_AS IS '融资租入固定资产';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NON_CASH_OTHERS IS '（不涉及现金收支的投资和筹资活动科目下）其他';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_AT_THE_END_OF_PERIOD IS '现金的期末余额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_AT_THE_BEGINNING_OF_THE_P IS '现金的期初余额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_EQUIVALENTS_AT_THE_END_OF IS '现金等价物的期末余额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.CASH_RQUIVALENTS_AT_THE_BEGINN IS '现金等价物的期初余额';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.NET_INCREASE_IN_CASH_AND_CASH_ IS '现金及现金等价物净增加额2';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.EJA_CASH_FLOWS_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_CASH_FLOWS2002_HIST.EXTEND3 IS '预留字段3';
