DROP TABLE E_COTA_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_COTA_INF_HIST
(
  EAH_COTA_INF_SGMT_ID   NCHAR(32)              NOT NULL,
  CON_ADD_DISTRICT_CODE  NCHAR(6),
  CON_ADD                NVARCHAR2(100),
  CON_PHONE              NVARCHAR2(25),
  FIN_CON_PHONE          NVARCHAR2(25),
  COTA_INFO_UP_DATE      NCHAR(10),
  EAA_BS_SGMT_ID         NCHAR(32)              NOT NULL,
  RPT_DATE               NCHAR(10),
  EXTEND1                NVARCHAR2(100),
  EXTEND2                NVARCHAR2(100),
  EXTEND3                NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_COTA_INF_HIST IS '310-企业基本信息联系方式段';

COMMENT ON COLUMN E_COTA_INF_HIST.EAH_COTA_INF_SGMT_ID IS '310-企业基本信息联系方式段主键';

COMMENT ON COLUMN E_COTA_INF_HIST.CON_ADD_DISTRICT_CODE IS '联系地址行政区划代码';

COMMENT ON COLUMN E_COTA_INF_HIST.CON_ADD IS '联系地址';

COMMENT ON COLUMN E_COTA_INF_HIST.CON_PHONE IS '联系电话';

COMMENT ON COLUMN E_COTA_INF_HIST.FIN_CON_PHONE IS '财务部门联系电话';

COMMENT ON COLUMN E_COTA_INF_HIST.COTA_INFO_UP_DATE IS '联系方式信息更新日期';

COMMENT ON COLUMN E_COTA_INF_HIST.EAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_COTA_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_COTA_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_COTA_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_COTA_INF_HIST.EXTEND3 IS '预留字段3';
