DROP TABLE E_CREDIT_LIM CASCADE CONSTRAINTS;

CREATE TABLE E_CREDIT_LIM
(
  EGC_CREDIT_LIM_SGMT_ID  NCHAR(32)             NOT NULL,
  CREDIT_LIM_TYPE         NCHAR(2),
  LIM_LOOP_FLG            NCHAR(1),
  CREDIT_LIM              NUMBER,
  CY                      NCHAR(3),
  CON_EFF_DATE            NVARCHAR2(10),
  CON_EXP_DATE            NVARCHAR2(10),
  CON_STATUS              NCHAR(1),
  CREDIT_REST             NUMBER,
  CREDIT_REST_CODE        NVARCHAR2(60),
  EGA_CTRCT_BS_SGMT_ID    NCHAR(32)             NOT NULL,
  RPT_DATE                NCHAR(10),
  EXTEND1                 NVARCHAR2(100),
  EXTEND2                 NVARCHAR2(100),
  EXTEND3                 NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_CREDIT_LIM IS '420-企业授信协议信息额度信息段';

COMMENT ON COLUMN E_CREDIT_LIM.EGC_CREDIT_LIM_SGMT_ID IS '420-企业授信协议信息额度信息段主键';

COMMENT ON COLUMN E_CREDIT_LIM.CREDIT_LIM_TYPE IS '授信额度类型';

COMMENT ON COLUMN E_CREDIT_LIM.LIM_LOOP_FLG IS '额度循环标志';

COMMENT ON COLUMN E_CREDIT_LIM.CREDIT_LIM IS '授信额度';

COMMENT ON COLUMN E_CREDIT_LIM.CY IS '币种';

COMMENT ON COLUMN E_CREDIT_LIM.CON_EFF_DATE IS '额度生效日期';

COMMENT ON COLUMN E_CREDIT_LIM.CON_EXP_DATE IS '额度到期日期';

COMMENT ON COLUMN E_CREDIT_LIM.CON_STATUS IS ' 额度状态';

COMMENT ON COLUMN E_CREDIT_LIM.CREDIT_REST IS '授信限额';

COMMENT ON COLUMN E_CREDIT_LIM.CREDIT_REST_CODE IS '授信限额编号';

COMMENT ON COLUMN E_CREDIT_LIM.EGA_CTRCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_CREDIT_LIM.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_CREDIT_LIM.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_CREDIT_LIM.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_CREDIT_LIM.EXTEND3 IS '预留字段3';
