DROP TABLE E_CTFITG_INF_MIDDLE CASCADE CONSTRAINTS;

CREATE TABLE E_CTFITG_INF_MIDDLE
(
  ENT_CERT_TYPE  NVARCHAR2(36)                  NOT NULL,
  ENT_CERT_NUM   NVARCHAR2(60)                  NOT NULL,
  EXTEND1        NVARCHAR2(100),
  EXTEND2        NVARCHAR2(100),
  EXTEND3        NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_CTFITG_INF_MIDDLE IS '340-企业身份标识整合信息中间表';

COMMENT ON COLUMN E_CTFITG_INF_MIDDLE.ENT_CERT_TYPE IS '企业身份标识类型';

COMMENT ON COLUMN E_CTFITG_INF_MIDDLE.ENT_CERT_NUM IS '企业身份标识号码';

COMMENT ON COLUMN E_CTFITG_INF_MIDDLE.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_CTFITG_INF_MIDDLE.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_CTFITG_INF_MIDDLE.EXTEND3 IS '预留字段3';
