DROP TABLE E_CTRCT_CERT_REL CASCADE CONSTRAINTS;

CREATE TABLE E_CTRCT_CERT_REL
(
  EGB_CTRCT_CERT_REL_SGMT_ID  NCHAR(32)         NOT NULL,
  BRER_TYPE                   NCHAR(1),
  CERT_REL_NAME               NVARCHAR2(80),
  CERT_REL_IDTYPE             NVARCHAR2(2),
  CERT_REL_ID_NUM             NVARCHAR2(40),
  EGA_CTRCT_BS_SGMT_ID        NCHAR(32)         NOT NULL,
  RPT_DATE                    NCHAR(10),
  EXTEND1                     NVARCHAR2(100),
  EXTEND2                     NVARCHAR2(100),
  EXTEND3                     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_CTRCT_CERT_REL IS '420-企业授信协议信息共同受信人';

COMMENT ON COLUMN E_CTRCT_CERT_REL.EGB_CTRCT_CERT_REL_SGMT_ID IS '420-企业授信协议信息共同受信人主键';

COMMENT ON COLUMN E_CTRCT_CERT_REL.BRER_TYPE IS '共同受信人身份类别';

COMMENT ON COLUMN E_CTRCT_CERT_REL.CERT_REL_NAME IS '共同受信人名称';

COMMENT ON COLUMN E_CTRCT_CERT_REL.CERT_REL_IDTYPE IS '共同受信人身份标识类型';

COMMENT ON COLUMN E_CTRCT_CERT_REL.CERT_REL_ID_NUM IS '共同受信人身份标识号码';

COMMENT ON COLUMN E_CTRCT_CERT_REL.EGA_CTRCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_CTRCT_CERT_REL.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_CTRCT_CERT_REL.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_CTRCT_CERT_REL.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_CTRCT_CERT_REL.EXTEND3 IS '预留字段3';
