DROP TABLE E_FCS_INF CASCADE CONSTRAINTS;

CREATE TABLE E_FCS_INF
(
  EAC_FCS_INF_SGMT_ID  NCHAR(32)                NOT NULL,
  NATIONALITY          NCHAR(3),
  REG_ADD              NVARCHAR2(80),
  ADM_DIV_OF_REG       NCHAR(6),
  ESTABLISH_DATE       NVARCHAR2(10),
  BIZ_END_DATE         NVARCHAR2(10),
  BIZ_RANGE            NVARCHAR2(2000),
  ECO_INDUS_CATE       NCHAR(5),
  ECO_TYPE             NCHAR(3),
  ENT_SCALE            NCHAR(1),
  FCS_INFO_UP_DATE     NCHAR(10),
  EAA_BS_SGMT_ID       NCHAR(32)                NOT NULL,
  RPT_DATE             NCHAR(10),
  EXTEND1              NVARCHAR2(100),
  EXTEND2              NVARCHAR2(100),
  EXTEND3              NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_FCS_INF IS '310-企业基本信息基本概况信息段';

COMMENT ON COLUMN E_FCS_INF.EAC_FCS_INF_SGMT_ID IS '310-企业基本信息基本概况信息段主键';

COMMENT ON COLUMN E_FCS_INF.NATIONALITY IS '国别代码';

COMMENT ON COLUMN E_FCS_INF.REG_ADD IS '登记地址';

COMMENT ON COLUMN E_FCS_INF.ADM_DIV_OF_REG IS '登记地行政区划代码';

COMMENT ON COLUMN E_FCS_INF.ESTABLISH_DATE IS '成立日期';

COMMENT ON COLUMN E_FCS_INF.BIZ_END_DATE IS '营业许可证到期日';

COMMENT ON COLUMN E_FCS_INF.BIZ_RANGE IS '业务范围';

COMMENT ON COLUMN E_FCS_INF.ECO_INDUS_CATE IS '行业分类代码';

COMMENT ON COLUMN E_FCS_INF.ECO_TYPE IS '经济类型代码';

COMMENT ON COLUMN E_FCS_INF.ENT_SCALE IS '企业规模';

COMMENT ON COLUMN E_FCS_INF.FCS_INFO_UP_DATE IS '基本概况信息更新日期';

COMMENT ON COLUMN E_FCS_INF.EAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_FCS_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_FCS_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_FCS_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_FCS_INF.EXTEND3 IS '预留字段3';
