DROP TABLE E_GUAR_MOTGA_CLTAL_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_GUAR_MOTGA_CLTAL_INF_HIST
(
  EED_GUAR_MOTGA_CLTAL_INF_ID  NCHAR(32)        NOT NULL,
  CCC                          NVARCHAR2(60),
  EEA_GUAR_ACCT_BS_SGMT_ID     NCHAR(32)        NOT NULL,
  RPT_DATE                     NCHAR(10),
  EXTEND1                      NVARCHAR2(100),
  EXTEND2                      NVARCHAR2(100),
  EXTEND3                      NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_GUAR_MOTGA_CLTAL_INF_HIST IS '440-企业担保账户信息抵质押物信息段';

COMMENT ON COLUMN E_GUAR_MOTGA_CLTAL_INF_HIST.EED_GUAR_MOTGA_CLTAL_INF_ID IS '440-企业担保账户信息抵质押物信息段主键';

COMMENT ON COLUMN E_GUAR_MOTGA_CLTAL_INF_HIST.CCC IS '抵（质）押合同标识码';

COMMENT ON COLUMN E_GUAR_MOTGA_CLTAL_INF_HIST.EEA_GUAR_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_GUAR_MOTGA_CLTAL_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_GUAR_MOTGA_CLTAL_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_GUAR_MOTGA_CLTAL_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_GUAR_MOTGA_CLTAL_INF_HIST.EXTEND3 IS '预留字段3';
