DROP TABLE E_GUAR_ACCT_BS_INF CASCADE CONSTRAINTS;

CREATE TABLE E_GUAR_ACCT_BS_INF
(
  EEB_GUAR_ACCT_BS_INF_SGMT_ID  NCHAR(32)       NOT NULL,
  BUSI_LINES                    NCHAR(1),
  BUSI_DTIL_LINES               NCHAR(2),
  OPEN_DATE                     NVARCHAR2(10),
  GUAR_AMT                      NUMBER,
  CY                            NCHAR(3),
  DUE_DATE                      NVARCHAR2(10),
  GUAR_MODE                     NVARCHAR2(2),
  OTH_REPY_GUARWAY              NCHAR(1),
  SEC_DEP                       NUMBER,
  CTRCT_TXT_CODE                NVARCHAR2(60),
  EEA_GUAR_ACCT_BS_SGMT_ID      NCHAR(32)       NOT NULL,
  RPT_DATE                      NCHAR(10),
  EXTEND1                       NVARCHAR2(100),
  EXTEND2                       NVARCHAR2(100),
  EXTEND3                       NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_GUAR_ACCT_BS_INF IS '440-企业担保账户信息基本信息段';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.EEB_GUAR_ACCT_BS_INF_SGMT_ID IS '440-企业担保账户信息基本信息段主键';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.BUSI_LINES IS '担保业务大类';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.BUSI_DTIL_LINES IS '担保业务种类细分';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.OPEN_DATE IS '开户日期';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.GUAR_AMT IS '担保金额';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.CY IS '币种';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.DUE_DATE IS '到期日期';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.GUAR_MODE IS '反担保方式';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.OTH_REPY_GUARWAY IS '其他还款保证方式';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.SEC_DEP IS '保证金百分比';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.CTRCT_TXT_CODE IS '担保合同文本编号';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.EEA_GUAR_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_GUAR_ACCT_BS_INF.EXTEND3 IS '预留字段3';
