DROP TABLE E_ICDN_RLTP_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_ICDN_RLTP_INF_HIST
(
  ECA_EN_ICDN_RLTP_INF_ID  NCHAR(32)            NOT NULL,
  INF_REC_TYPE             NCHAR(3),
  ENT_NAME                 NVARCHAR2(80),
  ENT_CERT_TYPE            NVARCHAR2(2),
  ENT_CERT_NUM             NVARCHAR2(40),
  ASSO_ENT_NAME            NVARCHAR2(80),
  ASSO_ENT_CERT_TYPE       NVARCHAR2(2),
  ASSO_ENT_CERT_NUM        NVARCHAR2(40),
  ASSO_TYPE                NCHAR(2),
  ASSO_SIGN                NCHAR(1),
  LAST_UPDATE_TIME         NVARCHAR2(10),
  OPERATOR_USER            NVARCHAR2(50),
  ORG_NAME                 NVARCHAR2(100),
  ORG_CODE                 NVARCHAR2(100),
  BUSINESS_STATES          NVARCHAR2(50),
  REJECT_REASON            NVARCHAR2(255),
  IS_FILTER                NCHAR(1),
  REPORT_MESSAGE_ID        NVARCHAR2(60),
  RPT_DATE                 NCHAR(10),
  EXTEND1                  NVARCHAR2(100),
  EXTEND2                  NVARCHAR2(100),
  EXTEND3                  NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_ICDN_RLTP_INF_HIST IS '350-企业间关联关系信息';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ECA_EN_ICDN_RLTP_INF_ID IS '350-企业间关联关系信息主键';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ENT_NAME IS 'A企业名称';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ENT_CERT_TYPE IS 'A企业身份标识类型';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ENT_CERT_NUM IS 'A企业身份标识码';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ASSO_ENT_NAME IS 'B企业名称';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ASSO_ENT_CERT_TYPE IS 'B企业身份标识类型';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ASSO_ENT_CERT_NUM IS 'B企业身份标识码';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ASSO_TYPE IS '关联关系类型';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ASSO_SIGN IS '关联标志';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.RPT_DATE IS '信息报告日期';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_ICDN_RLTP_INF_HIST.EXTEND3 IS '预留字段3';
