DROP TABLE E_ID_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_ID_HIST
(
  EAB_ID_SGMT_ID     NCHAR(32)                  NOT NULL,
  OTH_ENT_CERT_TYPE  NVARCHAR2(2),
  OTH_ENT_CERT_NUM   NVARCHAR2(40),
  ID_INFO_UP_DATE    NCHAR(10),
  EAA_BS_SGMT_ID     NCHAR(32)                  NOT NULL,
  RPT_DATE           NCHAR(10),
  EXTEND1            NVARCHAR2(100),
  EXTEND2            NVARCHAR2(100),
  EXTEND3            NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_ID_HIST IS '310-企业基本信息其他标识信息段';

COMMENT ON COLUMN E_ID_HIST.EAB_ID_SGMT_ID IS '310-企业基本信息其他标识信息段主键';

COMMENT ON COLUMN E_ID_HIST.OTH_ENT_CERT_TYPE IS '企业身份标识类型';

COMMENT ON COLUMN E_ID_HIST.OTH_ENT_CERT_NUM IS '企业身份标识号码';

COMMENT ON COLUMN E_ID_HIST.ID_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN E_ID_HIST.EAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_ID_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_ID_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_ID_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_ID_HIST.EXTEND3 IS '预留字段3';
