DROP TABLE E_INSTITU_BALANCE_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_INSTITU_BALANCE_HIST
(
  EKB_INSTITUTION_BALANCE_SHT_ID  NCHAR(32)     NOT NULL,
  CURRENCY_FUNDS                  NUMBER,
  SHORT_TERM_INVESTMENTS          NUMBER,
  AMOUNT_OF_FINANCIAL_RETURN      NUMBER,
  NOTES_RECEIVABLE                NUMBER,
  ACCOUNTS_RECEIVABLE             NUMBER,
  PREPAYMENTS                     NUMBER,
  OTHER_RECEIVABLES               NUMBER,
  INVENTORIES                     NUMBER,
  OTHER_CURRENT_ASSETS            NUMBER,
  TOTAL_CURRENT_ASSETS            NUMBER,
  LONG_TERM_INVESTMENT            NUMBER,
  FIXED_ASSETS                    NUMBER,
  ORIGINAL_COST_OF_FIXED_ASSET    NUMBER,
  FIXED_ASSET_ACCUMULATED_DEPREC  NUMBER,
  CONSTRUCTION_IN_PROCESS         NUMBER,
  INTANGIBLE_ASSETS               NUMBER,
  ORIGINAL_PRICE_OF_INTANGIBLE_A  NUMBER,
  ACCUMULATED_AMORTIZATION        NUMBER,
  ASSETS_TO_BE_PROCESSED_PENDING  NUMBER,
  TOTAL_NON_CURRENT_ASSETS        NUMBER,
  TOTAL_ASSETS                    NUMBER,
  SHORT_TERM_BORROWINGS           NUMBER,
  TAX_PAYABLE                     NUMBER,
  TREASURY_PAYABLE                NUMBER,
  PAYABLE_FINANCIAL_SPECIAL_ACCO  NUMBER,
  EMPLOYEE_BENEFITS_PAYABLE       NUMBER,
  NOTES_PAYABLE                   NUMBER,
  ACCOUNTS_PAYABLE                NUMBER,
  RECEIPTS_IN_ADVANCE             NUMBER,
  OTHER_PAYABLES                  NUMBER,
  OTHER_CURRENT_LIABILITIES       NUMBER,
  TOTAL_CURRENT_LIABILITIES       NUMBER,
  LONG_TERM_BORROWINGS            NUMBER,
  LONG_TERM_PAYABLES              NUMBER,
  TOTAL_NON_CURRENT_LIABILITIES   NUMBER,
  TOTAL_LIABILITIES               NUMBER,
  ENTERPRISE_FUND                 NUMBER,
  NON_CURRENT_ASSETS_FUND         NUMBER,
  SPECIAL_PURPOSE_FUNDS           NUMBER,
  FINANCIAL_AID_CARRIED_OVER      NUMBER,
  FINANCIAL_AID_BALANCE           NUMBER,
  NON_FINANCIAL_AID_CARRIED_OVER  NUMBER,
  NON_FINANCIAL_AID_BALANCE       NUMBER,
  UNDERTAKINGS_BALANCE            NUMBER,
  OPERATING_BALANCE               NUMBER,
  TOTAL_NET_ASSETS                NUMBER,
  TOTAL_LIABILITIES_AND_NET_ASSE  NUMBER,
  EKA_INSTITUTION_BALANCE_SHT_ID  NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_INSTITU_BALANCE_HIST IS '640-事业单位资产负债表事业单位资产负债表段';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.EKB_INSTITUTION_BALANCE_SHT_ID IS '640-事业单位资产负债表事业单位资产负债表段主键';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.CURRENCY_FUNDS IS '货币资金';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.SHORT_TERM_INVESTMENTS IS '短期投资';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.AMOUNT_OF_FINANCIAL_RETURN IS '财政应返还额度';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.NOTES_RECEIVABLE IS '应收票据';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.ACCOUNTS_RECEIVABLE IS '应收账款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.PREPAYMENTS IS '预付账款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.OTHER_RECEIVABLES IS '其他应收款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.INVENTORIES IS '存货';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.OTHER_CURRENT_ASSETS IS '其他流动资产';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_CURRENT_ASSETS IS '流动资产合计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.LONG_TERM_INVESTMENT IS '长期投资';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.FIXED_ASSETS IS '固定资产';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.ORIGINAL_COST_OF_FIXED_ASSET IS '固定资产原价';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.FIXED_ASSET_ACCUMULATED_DEPREC IS '累计折旧';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.CONSTRUCTION_IN_PROCESS IS '在建工程';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.INTANGIBLE_ASSETS IS '无形资产';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.ORIGINAL_PRICE_OF_INTANGIBLE_A IS '无形资产原价';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.ACCUMULATED_AMORTIZATION IS '累计摊销';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.ASSETS_TO_BE_PROCESSED_PENDING IS '待处置资产损溢';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_NON_CURRENT_ASSETS IS '非流动资产合计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_ASSETS IS '资产总计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.SHORT_TERM_BORROWINGS IS '短期借款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TAX_PAYABLE IS '应缴税费';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TREASURY_PAYABLE IS '应缴国库款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.PAYABLE_FINANCIAL_SPECIAL_ACCO IS '应缴财政专户款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.EMPLOYEE_BENEFITS_PAYABLE IS '应付职工薪酬';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.NOTES_PAYABLE IS '应付票据';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.ACCOUNTS_PAYABLE IS '应付账款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.RECEIPTS_IN_ADVANCE IS '预收账款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.OTHER_PAYABLES IS '其他应付款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.OTHER_CURRENT_LIABILITIES IS '其他流动负债';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_CURRENT_LIABILITIES IS '流动负债合计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.LONG_TERM_BORROWINGS IS '长期借款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.LONG_TERM_PAYABLES IS '长期应付款';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_NON_CURRENT_LIABILITIES IS '非流动负债合计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_LIABILITIES IS '负债合计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.ENTERPRISE_FUND IS '事业基金';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.NON_CURRENT_ASSETS_FUND IS '非流动资产基金';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.SPECIAL_PURPOSE_FUNDS IS '专用基金';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.FINANCIAL_AID_CARRIED_OVER IS '财政补助结转';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.FINANCIAL_AID_BALANCE IS '财政补助结余';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.NON_FINANCIAL_AID_CARRIED_OVER IS '非财政补助结转';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.NON_FINANCIAL_AID_BALANCE IS '非财政补助结余';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.UNDERTAKINGS_BALANCE IS '事业结余';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.OPERATING_BALANCE IS '经营结余';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_NET_ASSETS IS '净资产合计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.TOTAL_LIABILITIES_AND_NET_ASSE IS '负债和净资产总计';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.EKA_INSTITUTION_BALANCE_SHT_ID IS '数据外键';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_INSTITU_BALANCE_HIST.EXTEND3 IS '预留字段3';
