DROP TABLE E_INCOME_EXPENSE_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_INCOME_EXPENSE_HIST
(
  ELB_INCOME_AND_EXPENSE_STAT_ID  NCHAR(32)     NOT NULL,
  CURRENT_FINANCIAL_SUBSIDY_CARR  NUMBER,
  FINANCIAL_SUBSIDY_REVENUE       NUMBER,
  UNDERTAKINGS_EXPENDITURE_FINAN  NUMBER,
  CURRENT_UNDERTAKINGS_CARRIED_O  NUMBER,
  UNDERTAKINGS_CLASS_REVENUE      NUMBER,
  UNDERTAKINGS_REVENUE            NUMBER,
  SUPERIOR_SUBSIDY_REVENUE        NUMBER,
  REVENUE_TURNED_OVER_BY_SUBSIDI  NUMBER,
  OTHER_REVENUE                   NUMBER,
  DONATION_INCOME                 NUMBER,
  UNDERTAKINGS_CLASS_EXPENDITURE  NUMBER,
  UNDERTAKINGS_EXPENDITURE_NON_F  NUMBER,
  PAYMENT_TO_THE_HIGHER_AUTHORIT  NUMBER,
  GRANT_TO_THE_AUXILIARY_ORGANIZ  NUMBER,
  OTHER_EXPENDITURE               NUMBER,
  CURRENT_OPERATING_BALANCE       NUMBER,
  OPERATING_REVENUE               NUMBER,
  OPERATING_EXPENDITURE           NUMBER,
  OPERATING_BALANCE_MADE_UP_FOR_  NUMBER,
  NON_FINANCIAL_SUBSIDY_CARRIED_  NUMBER,
  NON_FINANCIAL_AID_CARRIED_OVER  NUMBER,
  NON_FINANCIAL_AID_BALANCE_THIS  NUMBER,
  ENTERPRISEINCOME_TAX_PAYABLE    NUMBER,
  SPECIAL_FUNDS_TO_EXTRACT        NUMBER,
  PUBLIC_FUND_TURNED_INTO         NUMBER,
  ELA_INCOME_AND_EXPENSE_STAT_ID  NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_INCOME_EXPENSE_HIST IS '650-事业单位收入支出表事业单位收入支出表段';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.ELB_INCOME_AND_EXPENSE_STAT_ID IS '650-事业单位收入支出表事业单位收入支出表段主键';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.CURRENT_FINANCIAL_SUBSIDY_CARR IS '本期财政补助结转结余';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.FINANCIAL_SUBSIDY_REVENUE IS '财政补助收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.UNDERTAKINGS_EXPENDITURE_FINAN IS '事业支出（财政补助支出）';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.CURRENT_UNDERTAKINGS_CARRIED_O IS '本期事业结转结余';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.UNDERTAKINGS_CLASS_REVENUE IS '事业类收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.UNDERTAKINGS_REVENUE IS '事业收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.SUPERIOR_SUBSIDY_REVENUE IS '上级补助收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.REVENUE_TURNED_OVER_BY_SUBSIDI IS '附属单位上缴收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.OTHER_REVENUE IS '其他收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.DONATION_INCOME IS '（其他收入科目下）捐赠收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.UNDERTAKINGS_CLASS_EXPENDITURE IS '事业类支出';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.UNDERTAKINGS_EXPENDITURE_NON_F IS '事业支出（非财政补助支出）';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.PAYMENT_TO_THE_HIGHER_AUTHORIT IS '上缴上级支出';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.GRANT_TO_THE_AUXILIARY_ORGANIZ IS '对附属单位补助支出';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.OTHER_EXPENDITURE IS '其他支出';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.CURRENT_OPERATING_BALANCE IS '本期经营结余';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.OPERATING_REVENUE IS '经营收入';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.OPERATING_EXPENDITURE IS '经营支出';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.OPERATING_BALANCE_MADE_UP_FOR_ IS '弥补以前年度亏损后的经营结余';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.NON_FINANCIAL_SUBSIDY_CARRIED_ IS '本年非财政补助结转结余';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.NON_FINANCIAL_AID_CARRIED_OVER IS '非财政补助结转';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.NON_FINANCIAL_AID_BALANCE_THIS IS '本年非财政补助结余';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.ENTERPRISEINCOME_TAX_PAYABLE IS '应缴企业所得税';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.SPECIAL_FUNDS_TO_EXTRACT IS '提取专用基金';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.PUBLIC_FUND_TURNED_INTO IS '转入事业基金';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.ELA_INCOME_AND_EXPENSE_STAT_ID IS '数据外键';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_INCOME_EXPENSE_HIST.EXTEND3 IS '预留字段3';
