DROP TABLE E_INCOME_STATEMENT_07 CASCADE CONSTRAINTS;

CREATE TABLE E_INCOME_STATEMENT_07
(
  EIC_INCOME_STATEMENT_PROFIT_ID  NCHAR(32)     NOT NULL,
  REVENUE_OF_SALES                NUMBER,
  COST_OF_SALES                   NUMBER,
  BUSINESS_AND_OTHER_TAXES        NUMBER,
  SELLING_EXPENSES                NUMBER,
  GENERAL_AND_ADMINISTRATIVE_EXP  NUMBER,
  FINANCIAL_EXPENSE               NUMBER,
  IMPAIRMENT_LOSS_OF_ASSETS       NUMBER,
  PROFIT_OR_LOSS_ARISING_FROM_CH  NUMBER,
  INVESTMENT_INCOME               NUMBER,
  INVESTMENT_INCOME_FROM_AFFILIA  NUMBER,
  OPERATING_PROFITS               NUMBER,
  NON_OPERATING_INCOME            NUMBER,
  NON_OPERATING_EXPENSES          NUMBER,
  NON_CURRENTASSETS               NUMBER,
  PROFIT_BEFORE_TAX               NUMBER,
  INCOME_TAX_EXPENSE              NUMBER,
  NET_PROFIT                      NUMBER,
  BASICEARNINGS_PER_SHARE         NUMBER,
  DILUTED_EARNINGS_PER_SHARE      NUMBER,
  EIA_INCOME_STATEMENT_PROFIT_ID  NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_INCOME_STATEMENT_07 IS '620-企业利润及利润分配表07利润及利润分配表段';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.EIC_INCOME_STATEMENT_PROFIT_ID IS '620-企业利润及利润分配表07利润及利润分配表段主键';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.REVENUE_OF_SALES IS '营业收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.COST_OF_SALES IS '营业成本';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.BUSINESS_AND_OTHER_TAXES IS '营业税金及附加';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.SELLING_EXPENSES IS '销售费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.GENERAL_AND_ADMINISTRATIVE_EXP IS '管理费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.FINANCIAL_EXPENSE IS '财务费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.IMPAIRMENT_LOSS_OF_ASSETS IS '资产减值损失';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.PROFIT_OR_LOSS_ARISING_FROM_CH IS '公允价值变动净收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.INVESTMENT_INCOME IS '投资净收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.INVESTMENT_INCOME_FROM_AFFILIA IS '对联营企业和合营企业的投资收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.OPERATING_PROFITS IS '营业利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.NON_OPERATING_INCOME IS '营业外收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.NON_OPERATING_EXPENSES IS '营业外支出';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.NON_CURRENTASSETS IS '非流动资产损失（其中：非流动资产处置损失）';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.PROFIT_BEFORE_TAX IS '利润总额';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.INCOME_TAX_EXPENSE IS '所得税费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.NET_PROFIT IS '净利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.BASICEARNINGS_PER_SHARE IS '基本每股收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.DILUTED_EARNINGS_PER_SHARE IS '稀释每股收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.EIA_INCOME_STATEMENT_PROFIT_ID IS '数据外键';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_INCOME_STATEMENT_07.EXTEND3 IS '预留字段3';
