DROP TABLE E_INCOME_STATEMENT_02_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_INCOME_STATEMENT_02_HIST
(
  EIB_INCOME_STATEMENT_PROFIT_ID  NCHAR(32)     NOT NULL,
  MAIN_REVENUEF_REVENUE           NUMBER,
  SALES_INCOME_OF_EXPORT_GOODS_P  NUMBER,
  SALES_INCOME_OF_IMPORT_GOODS_P  NUMBER,
  DISCOUNT_AND_ALLOWANCE          NUMBER,
  NET_AMOUNT_OF_INCOME_FROM_MAIN  NUMBER,
  MAIN_OPERATING_COST             NUMBER,
  SALES_INCOME_OF_EXPORT_PRODUCT  NUMBER,
  PRINCIPLE_BUSINESS_TAX_AND_EXT  NUMBER,
  OPERATION_EXPENSE               NUMBER,
  OTHERS_OPERATING_COST           NUMBER,
  DEFERRED_INCOME                 NUMBER,
  INCOME_FROM_SALES_AGENCY        NUMBER,
  OTHER_OPERATING_INCOME          NUMBER,
  PRINCIPLE_BUSINESS_PROFIT       NUMBER,
  OTHER_BUSINESS_PROFIT           NUMBER,
  SELLING_EXPENSES                NUMBER,
  GENERAL_AND_ADMINISTRATIVE_EXP  NUMBER,
  FINANCIAL_EXPENSES              NUMBER,
  OTHERS_EXPENSES                 NUMBER,
  OPERATING_PROFITS               NUMBER,
  INVESTMENT_INCOME               NUMBER,
  FUTURES_INCOME                  NUMBER,
  ALLOWANCE_INCOME                NUMBER,
  ALLOWANCE_INCOME_BEFORE_ALLOWA  NUMBER,
  NON_OPERATING_INCOME            NUMBER,
  NET_GAIN_ON_DISPOSAL_OF_FIXED   NUMBER,
  INCOME_FROM_NON_CURRENCY_TRADE  NUMBER,
  INCOME_FROM_SALES_OF_INTANGIBL  NUMBER,
  INCOME_FROM_PENALTY             NUMBER,
  OTHERS_INCOME                   NUMBER,
  CALCULATING_FROM_THE_CONTENT_S  NUMBER,
  NON_OPERATING_EXPENSES          NUMBER,
  LOSS_FROM_DISPOSAL_OF_FIXED_AS  NUMBER,
  EXCHANGE_OF_NON_MONETARY_ASSET  NUMBER,
  LOSS_OF_LAWSUITS                NUMBER,
  PAYMENT_FOR_DONATION            NUMBER,
  OTHER_PAYMENTS                  NUMBER,
  BALANCE_OF_CONTENT_SALARY       NUMBER,
  TOTAL_PROFIT                    NUMBER,
  INCOMETAX                       NUMBER,
  IMPARIMENT_LOSS                 NUMBER,
  UNREALIZEDINVESTMENT_LOSSES     NUMBER,
  NET_PROFIT                      NUMBER,
  PROFIT_DISTRIBUTION_AT_BEGINNI  NUMBER,
  COMPENSATION_OF_SURPLUS_RESERV  NUMBER,
  OTHER_ADJUSTMENT_FACTORS        NUMBER,
  PROFIT_AVAILABLE_FOR_DISTRIBUT  NUMBER,
  PROFIT_RESERVED_FOR_A_SINGLEIT  NUMBER,
  SUPPLEMENTARY_CURRENT_CAPITAL   NUMBER,
  APPROPRIATION_OF_STATUTORY_SUR  NUMBER,
  APPROPRIATION_OF_STATUTORY_WEL  NUMBER,
  APPROPRIATION_OF_STAFFINCENTIV  NUMBER,
  APPROPRIATION_OF_RESERVE_FUND   NUMBER,
  APPROPRIATION_OF_ENTERPRISE_EX  NUMBER,
  PROFITS_CAPITALIZAD_ON_RETURN   NUMBER,
  OTHERS                          NUMBER,
  PROFIT_AVAILABLE_FOR_OWNERS_DI  NUMBER,
  PREFERRED_STOCK_DIVIDENDS_PAYA  NUMBER,
  WITHDRAWAL_OTHER_COMMON_ACCUMU  NUMBER,
  PAYABLE_DIVIDENDS_OF_COMMON_ST  NUMBER,
  TRANSFER_FROM_ORDINARY_SHARES   NUMBER,
  OTHERS_FOR_OWNERS               NUMBER,
  UNAPPROPRIATED_PROFIT           NUMBER,
  LOSS_COMPENSATED_BEFORE_THE_TA  NUMBER,
  EIA_INCOME_STATEMENT_PROFIT_ID  NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_INCOME_STATEMENT_02_HIST IS '620-企业利润及利润分配表02利润及利润分配表段';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.EIB_INCOME_STATEMENT_PROFIT_ID IS '620-企业利润及利润分配表02利润及利润分配表段主键';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.MAIN_REVENUEF_REVENUE IS '主营业务收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.SALES_INCOME_OF_EXPORT_GOODS_P IS '（主营业务收入科目下）出口产品销售收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.SALES_INCOME_OF_IMPORT_GOODS_P IS '（主营业务收入科目下）进口产品销售收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.DISCOUNT_AND_ALLOWANCE IS '销售折扣与折让';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.NET_AMOUNT_OF_INCOME_FROM_MAIN IS '主营业务收入净额';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.MAIN_OPERATING_COST IS '主营业务成本';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.SALES_INCOME_OF_EXPORT_PRODUCT IS '（主营业务成本科目下）出口产品销售成本';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PRINCIPLE_BUSINESS_TAX_AND_EXT IS '主营业务税金及附加';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OPERATION_EXPENSE IS '经营费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHERS_OPERATING_COST IS '其他（业务成本）';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.DEFERRED_INCOME IS '递延收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.INCOME_FROM_SALES_AGENCY IS '代购代销收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHER_OPERATING_INCOME IS '其他（收入）';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PRINCIPLE_BUSINESS_PROFIT IS '主营业务利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHER_BUSINESS_PROFIT IS '其他业务利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.SELLING_EXPENSES IS '营业费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.GENERAL_AND_ADMINISTRATIVE_EXP IS '管理费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.FINANCIAL_EXPENSES IS '财务费用';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHERS_EXPENSES IS '其他（费用）';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OPERATING_PROFITS IS '营业利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.INVESTMENT_INCOME IS '投资收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.FUTURES_INCOME IS '期货收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.ALLOWANCE_INCOME IS '补贴收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.ALLOWANCE_INCOME_BEFORE_ALLOWA IS '（补贴收入科目下）补贴前亏损的企业补贴收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.NON_OPERATING_INCOME IS '营业外收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.NET_GAIN_ON_DISPOSAL_OF_FIXED IS '（营业外收入科目下）处置固定资产净收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.INCOME_FROM_NON_CURRENCY_TRADE IS '（营业外收入科目下）非货币性交易收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.INCOME_FROM_SALES_OF_INTANGIBL IS '（营业外收入科目下）出售无形资产收益';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.INCOME_FROM_PENALTY IS '（营业外收入科目下）罚款净收入';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHERS_INCOME IS '其他（利润）';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.CALCULATING_FROM_THE_CONTENT_S IS '（其他科目下）用以前年度含量工资节余弥补利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.NON_OPERATING_EXPENSES IS '营业外支出';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.LOSS_FROM_DISPOSAL_OF_FIXED_AS IS '（营业外支出科目下）处置固定资产净损失';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.EXCHANGE_OF_NON_MONETARY_ASSET IS '（营业外支出科目下）债务重组损失';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.LOSS_OF_LAWSUITS IS '（营业外支出科目下）罚款支出';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PAYMENT_FOR_DONATION IS '（营业外支出科目下）捐赠支出';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHER_PAYMENTS IS '其他支出';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.BALANCE_OF_CONTENT_SALARY IS '（其他支出）结转的含量工资包干节余';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.TOTAL_PROFIT IS '利润总额';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.INCOMETAX IS '所得税';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.IMPARIMENT_LOSS IS '少数股东损益';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.UNREALIZEDINVESTMENT_LOSSES IS '未确认的投资损失';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.NET_PROFIT IS '净利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PROFIT_DISTRIBUTION_AT_BEGINNI IS '年初未分配利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.COMPENSATION_OF_SURPLUS_RESERV IS '盈余公积补亏';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHER_ADJUSTMENT_FACTORS IS '其他调整因素';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PROFIT_AVAILABLE_FOR_DISTRIBUT IS '可供分配的利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PROFIT_RESERVED_FOR_A_SINGLEIT IS '单项留用的利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.SUPPLEMENTARY_CURRENT_CAPITAL IS '补充流动资本';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.APPROPRIATION_OF_STATUTORY_SUR IS '提取法定盈余公积';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.APPROPRIATION_OF_STATUTORY_WEL IS '提取法定公益金';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.APPROPRIATION_OF_STAFFINCENTIV IS '提取职工奖励及福利基金';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.APPROPRIATION_OF_RESERVE_FUND IS '提取储备基金';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.APPROPRIATION_OF_ENTERPRISE_EX IS '提取企业发展基金';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PROFITS_CAPITALIZAD_ON_RETURN IS '利润归还投资';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHERS IS '（可供分配的利润科目下）其他';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PROFIT_AVAILABLE_FOR_OWNERS_DI IS '可供投资者分配的利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PREFERRED_STOCK_DIVIDENDS_PAYA IS '应付优先股股利';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.WITHDRAWAL_OTHER_COMMON_ACCUMU IS '提取任意盈余公积';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.PAYABLE_DIVIDENDS_OF_COMMON_ST IS '应付普通股股利';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.TRANSFER_FROM_ORDINARY_SHARES IS '转作资本的普通股股利';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.OTHERS_FOR_OWNERS IS '（可供投资者分配的利润科目下）其他';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.UNAPPROPRIATED_PROFIT IS '未分配利润';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.LOSS_COMPENSATED_BEFORE_THE_TA IS '（未分配利润科目下）应由以后年度税前利润弥补的亏损';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.EIA_INCOME_STATEMENT_PROFIT_ID IS '数据外键';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_INCOME_STATEMENT_02_HIST.EXTEND3 IS '预留字段3';
