DROP TABLE E_IN_CAGS_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_IN_CAGS_INF_HIST
(
  PDW_INSECACCTID_CAGSINF_ID  NCHAR(32)         NOT NULL,
  INF_REC_TYPE                NVARCHAR2(3),
  ACCT_TYPE                   NVARCHAR2(2),
  OD_BNES_CODE                NVARCHAR2(60),
  NW_BNES_CODE                NVARCHAR2(60),
  LAST_UPDATE_TIME            NVARCHAR2(10),
  OPERATOR_USER               NVARCHAR2(50),
  ORG_NAME                    NVARCHAR2(100),
  ORG_CODE                    NVARCHAR2(100),
  BUSINESS_STATES             NVARCHAR2(50),
  REJECT_REASON               NVARCHAR2(255),
  IS_FILTER                   NCHAR(1),
  REPORT_MESSAGE_ID           NVARCHAR2(60),
  RPT_DATE                    NCHAR(10),
  NAME                        NVARCHAR2(30),
  ID_TYPE                     NVARCHAR2(2),
  ID_NUM                      NVARCHAR2(20)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_IN_CAGS_INF_HIST IS '企业标识变更请求记录表';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.PDW_INSECACCTID_CAGSINF_ID IS '主键';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.ACCT_TYPE IS '账户类型';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.OD_BNES_CODE IS '原业务标识码';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.NW_BNES_CODE IS '新业务标识码';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.NAME IS '姓名(当INF_REC_TYPE 为211是该字段为借贷人姓名，221为授信人姓名，231为担保人姓名)';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.ID_TYPE IS '证件类型(当INF_REC_TYPE 为211是该字段为借贷人证件类型，221为授信人证件类型，231为担保人证件类型)';

COMMENT ON COLUMN E_IN_CAGS_INF_HIST.ID_NUM IS '证件号码(当INF_REC_TYPE 为211是该字段为借贷人证件号码，221为授信人证件号码，231为担保人证件号码)';
