DROP TABLE E_MN_SHA_HOD_INF CASCADE CONSTRAINTS;

CREATE TABLE E_MN_SHA_HOD_INF
(
  EAE_MN_SHA_HOD_INF_SGMT_ID  NCHAR(32)         NOT NULL,
  REG_CAP_CURRENCY            NCHAR(3),
  REG_CAP                     NUMBER,
  SHAR_HOD_TYPE               NCHAR(2),
  SHAR_HOD_CERT_TYPE          NCHAR(1),
  SHAR_HOD_NAME               NVARCHAR2(80),
  SHAR_HOD_ID_TYPE            NVARCHAR2(2),
  SHAR_HOD_ID_NUM             NVARCHAR2(40),
  INV_RATIO                   NUMBER,
  MN_SHA_HOD_INFO_UP_DATE     NCHAR(10),
  EAA_BS_SGMT_ID              NCHAR(32)         NOT NULL,
  RPT_DATE                    NCHAR(10),
  EXTEND1                     NVARCHAR2(100),
  EXTEND2                     NVARCHAR2(100),
  EXTEND3                     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_MN_SHA_HOD_INF IS '310-企业基本信息注册资本及主要出资人段';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.EAE_MN_SHA_HOD_INF_SGMT_ID IS '310-企业基本信息注册资本及主要出资人段主键';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.REG_CAP_CURRENCY IS '注册资本币种';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.REG_CAP IS '注册资本';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.SHAR_HOD_TYPE IS '出资人类型';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.SHAR_HOD_CERT_TYPE IS '出资人身份类别';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.SHAR_HOD_NAME IS '出资人名称';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.SHAR_HOD_ID_TYPE IS '出资人身份标识类型';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.SHAR_HOD_ID_NUM IS '出资人身份标识号码';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.INV_RATIO IS '出资比例';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.MN_SHA_HOD_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.EAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_MN_SHA_HOD_INF.EXTEND3 IS '预留字段3';
