DROP TABLE E_MN_MMB_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_MN_MMB_INF_HIST
(
  EAD_MN_MMB_INF_SGMT_ID  NCHAR(32)             NOT NULL,
  MMB_ALIAS               NVARCHAR2(30),
  MMB_ID_TYPE             NVARCHAR2(2),
  MMB_ID_NUM              NVARCHAR2(20),
  MMB_PSTN                NCHAR(1),
  MN_MMB_INFO_UPDATE      NCHAR(10),
  EAA_BS_SGMT_ID          NCHAR(32)             NOT NULL,
  RPT_DATE                NCHAR(10),
  EXTEND1                 NVARCHAR2(100),
  EXTEND2                 NVARCHAR2(100),
  EXTEND3                 NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_MN_MMB_INF_HIST IS '310-企业基本信息主要组成人员段';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.EAD_MN_MMB_INF_SGMT_ID IS '310-企业基本信息主要组成人员段主键';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.MMB_ALIAS IS '主要组成人员姓名';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.MMB_ID_TYPE IS '主要组成人员证件类型';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.MMB_ID_NUM IS '主要组成人员证件号码';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.MMB_PSTN IS '主要组成人员职位';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.MN_MMB_INFO_UPDATE IS '信息更新日期';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.EAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_MN_MMB_INF_HIST.EXTEND3 IS '预留字段3';
