DROP TABLE E_ORIG_CREDITOR_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_ORIG_CREDITOR_INF_HIST
(
  EDF_ORIG_CREDITOR_INF_SGMT_ID  NCHAR(32)      NOT NULL,
  INIT_CRED_NAME                 NVARCHAR2(80),
  INIT_CED_ORG_CODE              NCHAR(18),
  ORIG_DBT_CATE                  NCHAR(2),
  INIT_RPY_STS                   NCHAR(1),
  EDA_ACCT_BS_SGMT_ID            NCHAR(32)      NOT NULL,
  RPT_DATE                       NCHAR(10),
  EXTEND1                        NVARCHAR2(100),
  EXTEND2                        NVARCHAR2(100),
  EXTEND3                        NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_ORIG_CREDITOR_INF_HIST IS '410-企业借贷账户交易初始债权说明段';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.EDF_ORIG_CREDITOR_INF_SGMT_ID IS '410-企业借贷账户交易初始债权说明段主键';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.INIT_CRED_NAME IS '初始债权人名称';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.INIT_CED_ORG_CODE IS '初始债权人机构代码';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.ORIG_DBT_CATE IS '原债务种类';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.INIT_RPY_STS IS '债权转移时的还款状态';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.EDA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_ORIG_CREDITOR_INF_HIST.EXTEND3 IS '预留字段3';
