DROP TABLE E_SEC_ACCT_DEL CASCADE CONSTRAINTS;

CREATE TABLE E_SEC_ACCT_DEL
(
  EEY_EN_SEC_ACCT_DEL_ID  NCHAR(32)             NOT NULL,
  INF_REC_TYPE            NCHAR(3),
  ACCT_TYPE               NCHAR(2),
  DEL_REC_CODE            NVARCHAR2(60),
  DEL_SGMT_CODE           NCHAR(1),
  DEL_START_DATE          NVARCHAR2(10),
  DEL_END_DATE            NVARCHAR2(10),
  LAST_UPDATE_TIME        NVARCHAR2(10),
  OPERATOR_USER           NVARCHAR2(50),
  ORG_NAME                NVARCHAR2(100),
  ORG_CODE                NVARCHAR2(100),
  BUSINESS_STATES         NVARCHAR2(50),
  REJECT_REASON           NVARCHAR2(255),
  IS_FILTER               NCHAR(1),
  REPORT_MESSAGE_ID       NVARCHAR2(60),
  RPT_DATE                NCHAR(10),
  NAME                    NVARCHAR2(80),
  ID_TYPE                 NVARCHAR2(2),
  ID_NUM                  NVARCHAR2(40),
  EXTEND1                 NVARCHAR2(100),
  EXTEND2                 NVARCHAR2(100),
  EXTEND3                 NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_SEC_ACCT_DEL IS '443-企业担保账户信息按段删除类请求';

COMMENT ON COLUMN E_SEC_ACCT_DEL.EEY_EN_SEC_ACCT_DEL_ID IS '443-企业担保账户信息按段删除类请求主键';

COMMENT ON COLUMN E_SEC_ACCT_DEL.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN E_SEC_ACCT_DEL.ACCT_TYPE IS '账户类型';

COMMENT ON COLUMN E_SEC_ACCT_DEL.DEL_REC_CODE IS '待删除业务标识码';

COMMENT ON COLUMN E_SEC_ACCT_DEL.DEL_SGMT_CODE IS '待删除段段标';

COMMENT ON COLUMN E_SEC_ACCT_DEL.DEL_START_DATE IS '待删除起始日期';

COMMENT ON COLUMN E_SEC_ACCT_DEL.DEL_END_DATE IS '待删除结束日期';

COMMENT ON COLUMN E_SEC_ACCT_DEL.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN E_SEC_ACCT_DEL.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN E_SEC_ACCT_DEL.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN E_SEC_ACCT_DEL.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN E_SEC_ACCT_DEL.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN E_SEC_ACCT_DEL.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN E_SEC_ACCT_DEL.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN E_SEC_ACCT_DEL.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN E_SEC_ACCT_DEL.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_SEC_ACCT_DEL.NAME IS '债务人名称';

COMMENT ON COLUMN E_SEC_ACCT_DEL.ID_TYPE IS '债务人身份标识类型';

COMMENT ON COLUMN E_SEC_ACCT_DEL.ID_NUM IS '债务人身份标识号码';

COMMENT ON COLUMN E_SEC_ACCT_DEL.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_SEC_ACCT_DEL.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_SEC_ACCT_DEL.EXTEND3 IS '预留字段3';
