DROP TABLE E_SPVSG_ATHRTY_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE E_SPVSG_ATHRTY_INF_HIST
(
  EAG_SPVSG_ATHRTY_INF_SGMT_ID  NCHAR(32)       NOT NULL,
  SUP_ORG_TYPE                  NCHAR(1),
  SUP_ORG_NAME                  NVARCHAR2(80),
  SUP_ORG_CERT_TYPE             NVARCHAR2(2),
  SUP_ORG_CERT_NUM              NVARCHAR2(40),
  SUP_ORG_INFO_UP_DATE          NCHAR(10),
  EAA_BS_SGMT_ID                NCHAR(32)       NOT NULL,
  RPT_DATE                      NCHAR(10),
  EXTEND1                       NVARCHAR2(100),
  EXTEND2                       NVARCHAR2(100),
  EXTEND3                       NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE E_SPVSG_ATHRTY_INF_HIST IS '310-企业基本信息上级机构段';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.EAG_SPVSG_ATHRTY_INF_SGMT_ID IS '310-企业基本信息上级机构段主键';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.SUP_ORG_TYPE IS '上级机构类型';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.SUP_ORG_NAME IS '上级机构名称';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.SUP_ORG_CERT_TYPE IS '上级机构身份标识类型';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.SUP_ORG_CERT_NUM IS '上级机构身份标识号码';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.SUP_ORG_INFO_UP_DATE IS '上级机构信息更新日期';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.EAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN E_SPVSG_ATHRTY_INF_HIST.EXTEND3 IS '预留字段3';
