DROP TABLE EXTERNAL_DB_SSO CASCADE CONSTRAINTS;

CREATE TABLE EXTERNAL_DB_SSO
(
  SYS_TOKEN   NVARCHAR2(36)                     NOT NULL,
  LOGIN_NAME  NVARCHAR2(36),
  USER_ID     NVARCHAR2(36)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE EXTERNAL_DB_SSO IS '通过数据库映射用户信息，与第三方系统集成SSO使用该表，登录成功后就删除';

COMMENT ON COLUMN EXTERNAL_DB_SSO.SYS_TOKEN IS 'TOKEN';

COMMENT ON COLUMN EXTERNAL_DB_SSO.LOGIN_NAME IS '用户名称';

COMMENT ON COLUMN EXTERNAL_DB_SSO.USER_ID IS '用户ID';
