DROP TABLE FEED_BACK_REPORT_CODE CASCADE CONSTRAINTS;

CREATE TABLE FEED_BACK_REPORT_CODE
(
  FEED_BACK_REPORT_CODE_ID  NCHAR(32)           NOT NULL,
  FB_CODE                   NVARCHAR2(100),
  FB_TAG                    NVARCHAR2(100),
  MAP_RULE_CODE             NVARCHAR2(100),
  MESSAGE                   NVARCHAR2(2000)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FEED_BACK_REPORT_CODE IS '反馈报文状态信息表';

COMMENT ON COLUMN FEED_BACK_REPORT_CODE.FB_CODE IS '反馈代码';

COMMENT ON COLUMN FEED_BACK_REPORT_CODE.FB_TAG IS '反馈标签';

COMMENT ON COLUMN FEED_BACK_REPORT_CODE.MAP_RULE_CODE IS '映射规则代码';

COMMENT ON COLUMN FEED_BACK_REPORT_CODE.MESSAGE IS '描述信息';
