DROP TABLE FEED_BACK_REPORT_ERR_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE FEED_BACK_REPORT_ERR_MESSAGE
(
  FEED_BACK_REPORT_ERROR_MESS_ID  NCHAR(32)     NOT NULL,
  FEED_BACK_REPORT_CODE_ID        NVARCHAR2(50),
  ERROR_MESSAGE                   NVARCHAR2(2000),
  RECORD_ID                       NCHAR(32),
  REPORT_MESSAGE_ID               NVARCHAR2(60),
  REPORT_MESSAGE_TYPE             NVARCHAR2(10),
  CREATE_TIME                     NVARCHAR2(10),
  REPORT_MESSAGE_NAME             NVARCHAR2(100),
  FEED_BACK_REPORT_NAME           NVARCHAR2(255),
  FB_CODE                         NVARCHAR2(255),
  FB_TAG                          NVARCHAR2(255)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FEED_BACK_REPORT_ERR_MESSAGE IS '反馈报文错误信息表';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.FEED_BACK_REPORT_CODE_ID IS '反馈报文错误码主键';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.ERROR_MESSAGE IS '错误信息';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.RECORD_ID IS '记录ID';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.REPORT_MESSAGE_TYPE IS '记录类型';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.REPORT_MESSAGE_NAME IS '报文名称';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.FEED_BACK_REPORT_NAME IS '反馈报文名称';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.FB_CODE IS '反馈代码';

COMMENT ON COLUMN FEED_BACK_REPORT_ERR_MESSAGE.FB_TAG IS '反馈标签';
