DROP TABLE I_ACCT_DBT_INF CASCADE CONSTRAINTS;

CREATE TABLE I_ACCT_DBT_INF
(
  PBI_ACCT_DBT_INF_SGMT_ID    NCHAR(32)         NOT NULL,
  NOMONTH_ACCT_STATUS         NVARCHAR2(2),
  NOMONTH_ACCT_BAL            NUMBER,
  NOMONTH_FIVE_CATE           NVARCHAR2(1),
  NOMONTH_FIVE_CATE_ADJ_DATE  NVARCHAR2(10),
  NOMONTH_REM_REP_PRD         NUMBER,
  NOMONTH_RPY_STATUS          NVARCHAR2(1),
  NOMONTH_OVERD_PRD           NUMBER,
  NOMONTH_TOT_OVERD           NUMBER,
  NOMONTH_LAT_RPY_AMT         NUMBER,
  NOMONTH_LAT_RPY_DATE        NVARCHAR2(10),
  NOMONTH_CLOSE_DATE          NVARCHAR2(10),
  PBA_ACCT_BS_SGMT_ID         NCHAR(32)         NOT NULL,
  RPT_DATE                    NCHAR(10),
  EXTEND1                     NVARCHAR2(100),
  EXTEND2                     NVARCHAR2(100),
  EXTEND3                     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_ACCT_DBT_INF IS '210-个人借贷账户信息记录非月度表现信息段';

COMMENT ON COLUMN I_ACCT_DBT_INF.PBI_ACCT_DBT_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_ACCT_STATUS IS '账户状态';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_ACCT_BAL IS '余额';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_FIVE_CATE IS '五级分类';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_FIVE_CATE_ADJ_DATE IS '五级分类认定日期';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_REM_REP_PRD IS '剩余还款期数';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_RPY_STATUS IS '当前还款状态';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_OVERD_PRD IS '当前逾期期数';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_TOT_OVERD IS '当前逾期总额';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_LAT_RPY_AMT IS '最近一次实际还款金额';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_LAT_RPY_DATE IS '最近一次实际还款日期';

COMMENT ON COLUMN I_ACCT_DBT_INF.NOMONTH_CLOSE_DATE IS '账户关闭日期';

COMMENT ON COLUMN I_ACCT_DBT_INF.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_ACCT_DBT_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_ACCT_DBT_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_ACCT_DBT_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_ACCT_DBT_INF.EXTEND3 IS '预留字段3';
