DROP TABLE I_ACCT_CRED_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_ACCT_CRED_HIST
(
  PBE_ACCT_CRED_SGMT_ID  NCHAR(32)              NOT NULL,
  MCC                    NVARCHAR2(60),
  PBA_ACCT_BS_SGMT_ID    NCHAR(32)              NOT NULL,
  RPT_DATE               NCHAR(10),
  EXTEND1                NVARCHAR2(100),
  EXTEND2                NVARCHAR2(100),
  EXTEND3                NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_ACCT_CRED_HIST IS '210-个人借贷账户信息记录授信额度信息段';

COMMENT ON COLUMN I_ACCT_CRED_HIST.PBE_ACCT_CRED_SGMT_ID IS '主键';

COMMENT ON COLUMN I_ACCT_CRED_HIST.MCC IS '授信协议标识码';

COMMENT ON COLUMN I_ACCT_CRED_HIST.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_ACCT_CRED_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_ACCT_CRED_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_ACCT_CRED_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_ACCT_CRED_HIST.EXTEND3 IS '预留字段3';
