DROP TABLE I_ACCT_BS_MIDDLE CASCADE CONSTRAINTS;

CREATE TABLE I_ACCT_BS_MIDDLE
(
  ACCT_TYPE  NVARCHAR2(36)                      NOT NULL,
  ACCT_CODE  NVARCHAR2(60)                      NOT NULL,
  EXTEND1    NVARCHAR2(100),
  EXTEND2    NVARCHAR2(100),
  EXTEND3    NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_ACCT_BS_MIDDLE IS '210-个人借贷账户信息记录基础段中间表';

COMMENT ON COLUMN I_ACCT_BS_MIDDLE.ACCT_TYPE IS '账户类型';

COMMENT ON COLUMN I_ACCT_BS_MIDDLE.ACCT_CODE IS '账户标识码';

COMMENT ON COLUMN I_ACCT_BS_MIDDLE.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_ACCT_BS_MIDDLE.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_ACCT_BS_MIDDLE.EXTEND3 IS '预留字段3';
