DROP TABLE I_ACCT_BS_INF CASCADE CONSTRAINTS;

CREATE TABLE I_ACCT_BS_INF
(
  PBB_ACCT_BS_INF_SGMT_ID  NCHAR(32)            NOT NULL,
  BUSI_LINES               NVARCHAR2(1),
  BUSI_DTL_LINES           NVARCHAR2(2),
  OPEN_DATE                NVARCHAR2(10),
  CY                       NVARCHAR2(3),
  ACCT_CRED_LINE           NUMBER,
  LOAN_AMT                 NUMBER,
  FLAG                     NVARCHAR2(1),
  DUE_DATE                 NVARCHAR2(10),
  REPAY_MODE               NVARCHAR2(2),
  REPAY_FREQCY             NVARCHAR2(2),
  REPAY_PRD                NUMBER,
  APPLY_BUSI_DIST          NVARCHAR2(6),
  GUAR_MODE                NVARCHAR2(1),
  OTH_REPY_GUAR_WAY        NVARCHAR2(1),
  ASSET_TRAND_FLAG         NVARCHAR2(1),
  FUND_SOU                 NVARCHAR2(2),
  LOAN_FORM                NVARCHAR2(1),
  CREDIT_ID                NVARCHAR2(4),
  PBA_ACCT_BS_SGMT_ID      NCHAR(32)            NOT NULL,
  RPT_DATE                 NCHAR(10),
  EXTEND1                  NVARCHAR2(100),
  EXTEND2                  NVARCHAR2(100),
  EXTEND3                  NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_ACCT_BS_INF IS '210-个人借贷账户信息记录基本信息段';

COMMENT ON COLUMN I_ACCT_BS_INF.PBB_ACCT_BS_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_ACCT_BS_INF.BUSI_LINES IS '借贷业务大类';

COMMENT ON COLUMN I_ACCT_BS_INF.BUSI_DTL_LINES IS '借贷业务种类细分';

COMMENT ON COLUMN I_ACCT_BS_INF.OPEN_DATE IS '开户日期';

COMMENT ON COLUMN I_ACCT_BS_INF.CY IS '币种';

COMMENT ON COLUMN I_ACCT_BS_INF.ACCT_CRED_LINE IS '信用额度';

COMMENT ON COLUMN I_ACCT_BS_INF.LOAN_AMT IS '借款金额';

COMMENT ON COLUMN I_ACCT_BS_INF.FLAG IS '分次放款标志';

COMMENT ON COLUMN I_ACCT_BS_INF.DUE_DATE IS '到期日期';

COMMENT ON COLUMN I_ACCT_BS_INF.REPAY_MODE IS '还款方式';

COMMENT ON COLUMN I_ACCT_BS_INF.REPAY_FREQCY IS '还款频率';

COMMENT ON COLUMN I_ACCT_BS_INF.REPAY_PRD IS '还款期数';

COMMENT ON COLUMN I_ACCT_BS_INF.APPLY_BUSI_DIST IS '业务申请地行政区划代码';

COMMENT ON COLUMN I_ACCT_BS_INF.GUAR_MODE IS '担保方式';

COMMENT ON COLUMN I_ACCT_BS_INF.OTH_REPY_GUAR_WAY IS '其他还款保证方式';

COMMENT ON COLUMN I_ACCT_BS_INF.ASSET_TRAND_FLAG IS '资产转让标志';

COMMENT ON COLUMN I_ACCT_BS_INF.FUND_SOU IS '业务经营类型';

COMMENT ON COLUMN I_ACCT_BS_INF.LOAN_FORM IS '贷款发放形式';

COMMENT ON COLUMN I_ACCT_BS_INF.CREDIT_ID IS '卡片标识号';

COMMENT ON COLUMN I_ACCT_BS_INF.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_ACCT_BS_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_ACCT_BS_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_ACCT_BS_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_ACCT_BS_INF.EXTEND3 IS '预留字段3';
