DROP TABLE I_AMBLG_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_AMBLG_INF_HIST
(
  PBG_AMBLG_INF_SGMT_ID  NCHAR(32)              NOT NULL,
  MONTH                  NVARCHAR2(7),
  SETT_DATE              NVARCHAR2(10),
  ACCT_STATUS            NVARCHAR2(2),
  ACCT_BAL               NUMBER,
  PRID_ACCT_BAL          NUMBER,
  USED_AMT               NUMBER,
  NOT_ISU_BAL            NUMBER,
  REM_REP_PRD            NUMBER,
  FIVE_CATE              NVARCHAR2(1),
  FIVE_CATE_ADJ_DATE     NVARCHAR2(10),
  RPY_STATUS             NVARCHAR2(1),
  RPY_PRCT               NUMBER,
  OVERD_PRD              NUMBER,
  TOT_OVERD              NUMBER,
  OVERD_PRINC            NUMBER,
  OVED31_60_PRINC        NUMBER,
  OVED61_90_PRINC        NUMBER,
  OVED91_180_PRINC       NUMBER,
  OVED_PRINC180          NUMBER,
  OVEDRAW_BA_OVE180      NUMBER,
  CUR_RPY_AMT            NUMBER,
  ACT_RPY_AMT            NUMBER,
  LAT_RPY_DATE           NVARCHAR2(10),
  CLOSE_DATE             NVARCHAR2(10),
  PBA_ACCT_BS_SGMT_ID    NCHAR(32)              NOT NULL,
  RPT_DATE               NCHAR(10),
  EXTEND1                NVARCHAR2(100),
  EXTEND2                NVARCHAR2(100),
  EXTEND3                NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_AMBLG_INF_HIST IS '210-个人借贷账户信息记录月度表现信息段';

COMMENT ON COLUMN I_AMBLG_INF_HIST.PBG_AMBLG_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_AMBLG_INF_HIST.MONTH IS '月份';

COMMENT ON COLUMN I_AMBLG_INF_HIST.SETT_DATE IS '结算/应还款日';

COMMENT ON COLUMN I_AMBLG_INF_HIST.ACCT_STATUS IS '账户状态';

COMMENT ON COLUMN I_AMBLG_INF_HIST.ACCT_BAL IS '余额';

COMMENT ON COLUMN I_AMBLG_INF_HIST.PRID_ACCT_BAL IS '本期账单余额';

COMMENT ON COLUMN I_AMBLG_INF_HIST.USED_AMT IS '已使用额度';

COMMENT ON COLUMN I_AMBLG_INF_HIST.NOT_ISU_BAL IS '未出单的大额专项分期余额';

COMMENT ON COLUMN I_AMBLG_INF_HIST.REM_REP_PRD IS '剩余还款期数';

COMMENT ON COLUMN I_AMBLG_INF_HIST.FIVE_CATE IS '五级分类';

COMMENT ON COLUMN I_AMBLG_INF_HIST.FIVE_CATE_ADJ_DATE IS '五级分类认定日期';

COMMENT ON COLUMN I_AMBLG_INF_HIST.RPY_STATUS IS '当前还款状态';

COMMENT ON COLUMN I_AMBLG_INF_HIST.RPY_PRCT IS '实际还款百分比';

COMMENT ON COLUMN I_AMBLG_INF_HIST.OVERD_PRD IS '当前逾期期数';

COMMENT ON COLUMN I_AMBLG_INF_HIST.TOT_OVERD IS '当前逾期总额';

COMMENT ON COLUMN I_AMBLG_INF_HIST.OVERD_PRINC IS '当前逾期本金';

COMMENT ON COLUMN I_AMBLG_INF_HIST.OVED31_60_PRINC IS '逾期31-60天未归还本金';

COMMENT ON COLUMN I_AMBLG_INF_HIST.OVED61_90_PRINC IS '逾期61-90天未归还本金';

COMMENT ON COLUMN I_AMBLG_INF_HIST.OVED91_180_PRINC IS '逾期91-180天未归还本金';

COMMENT ON COLUMN I_AMBLG_INF_HIST.OVED_PRINC180 IS '逾期180天以上未归还本金';

COMMENT ON COLUMN I_AMBLG_INF_HIST.OVEDRAW_BA_OVE180 IS '透支180天以上未还余额';

COMMENT ON COLUMN I_AMBLG_INF_HIST.CUR_RPY_AMT IS '本月应还款金额';

COMMENT ON COLUMN I_AMBLG_INF_HIST.ACT_RPY_AMT IS '本月实际还款金额';

COMMENT ON COLUMN I_AMBLG_INF_HIST.LAT_RPY_DATE IS '最近一次实际还款日期';

COMMENT ON COLUMN I_AMBLG_INF_HIST.CLOSE_DATE IS '账户关闭日期';

COMMENT ON COLUMN I_AMBLG_INF_HIST.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_AMBLG_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_AMBLG_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_AMBLG_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_AMBLG_INF_HIST.EXTEND3 IS '预留字段3';
