DROP TABLE I_AS_TRST_DSPN_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_AS_TRST_DSPN_HIST
(
  PBJ_AS_TRST_DSPN_SGMT_ID  NCHAR(32)           NOT NULL,
  CHAN_TRAN_TYPE            NVARCHAR2(2),
  TRAN_DATE                 NVARCHAR2(10),
  TRAN_AMT                  NUMBER,
  DUE_TRAN_MON              NUMBER,
  DET_INFO                  NVARCHAR2(200),
  PBA_ACCT_BS_SGMT_ID       NCHAR(32)           NOT NULL,
  RPT_DATE                  NCHAR(10),
  EXTEND1                   NVARCHAR2(100),
  EXTEND2                   NVARCHAR2(100),
  EXTEND3                   NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_AS_TRST_DSPN_HIST IS '210-个人借贷账户信息记录特殊交易说明段';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.PBJ_AS_TRST_DSPN_SGMT_ID IS '主键';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.CHAN_TRAN_TYPE IS '交易类型';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.TRAN_DATE IS '交易日期';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.TRAN_AMT IS '交易金额';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.DUE_TRAN_MON IS '到期日期变更月数';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.DET_INFO IS '交易明细信息';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_AS_TRST_DSPN_HIST.EXTEND3 IS '预留字段3';
