DROP TABLE I_BS_MIDDLE CASCADE CONSTRAINTS;

CREATE TABLE I_BS_MIDDLE
(
  ID_TYPE  NVARCHAR2(36)                        NOT NULL,
  ID_NUM   NVARCHAR2(60)                        NOT NULL,
  EXTEND1  NVARCHAR2(100),
  EXTEND2  NVARCHAR2(100),
  EXTEND3  NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_BS_MIDDLE IS '110-个人基本信息记录基础段中间表';

COMMENT ON COLUMN I_BS_MIDDLE.ID_TYPE IS '证件类型';

COMMENT ON COLUMN I_BS_MIDDLE.ID_NUM IS '证件号码';

COMMENT ON COLUMN I_BS_MIDDLE.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_BS_MIDDLE.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_BS_MIDDLE.EXTEND3 IS '预留字段3';
