DROP TABLE I_CTRCT_CERT_REL CASCADE CONSTRAINTS;

CREATE TABLE I_CTRCT_CERT_REL
(
  PCB_CTRCT_CERT_REL_SGMT_ID  NCHAR(32)         NOT NULL,
  BRER_TYPE                   NVARCHAR2(1),
  CERT_REL_NAME               NVARCHAR2(80),
  CERT_REL_ID_TYPE            NVARCHAR2(2),
  CERT_REL_ID_NUM             NVARCHAR2(40),
  PCA_CTRCT_BS_SGMT_ID        NCHAR(32)         NOT NULL,
  RPT_DATE                    NCHAR(10),
  EXTEND1                     NVARCHAR2(100),
  EXTEND2                     NVARCHAR2(100),
  EXTEND3                     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_CTRCT_CERT_REL IS '220-个人授信协议信息记录共同受信人信息段';

COMMENT ON COLUMN I_CTRCT_CERT_REL.PCB_CTRCT_CERT_REL_SGMT_ID IS '主键';

COMMENT ON COLUMN I_CTRCT_CERT_REL.BRER_TYPE IS '共同受信人身份类别';

COMMENT ON COLUMN I_CTRCT_CERT_REL.CERT_REL_NAME IS '共同受信人名称';

COMMENT ON COLUMN I_CTRCT_CERT_REL.CERT_REL_ID_TYPE IS '共同受信人身份标识类型';

COMMENT ON COLUMN I_CTRCT_CERT_REL.CERT_REL_ID_NUM IS '共同受信人身份标识号码';

COMMENT ON COLUMN I_CTRCT_CERT_REL.PCA_CTRCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_CTRCT_CERT_REL.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_CTRCT_CERT_REL.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_CTRCT_CERT_REL.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_CTRCT_CERT_REL.EXTEND3 IS '预留字段3';
