DROP TABLE I_CTRCT_BS_MIDDLE CASCADE CONSTRAINTS;

CREATE TABLE I_CTRCT_BS_MIDDLE
(
  CONTRACT_CODE  NVARCHAR2(60)                  NOT NULL,
  EXTEND1        NVARCHAR2(100),
  EXTEND2        NVARCHAR2(100),
  EXTEND3        NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_CTRCT_BS_MIDDLE IS '220-个人授信协议信息记录基础段中间表';

COMMENT ON COLUMN I_CTRCT_BS_MIDDLE.CONTRACT_CODE IS '授信协议标识码';

COMMENT ON COLUMN I_CTRCT_BS_MIDDLE.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_CTRCT_BS_MIDDLE.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_CTRCT_BS_MIDDLE.EXTEND3 IS '预留字段3';
