DROP TABLE I_GR_REPYMT_INF CASCADE CONSTRAINTS;

CREATE TABLE I_GR_REPYMT_INF
(
  PDE_GR_REPYMT_INF_SGMT_ID  NCHAR(32)          NOT NULL,
  ACCT_STATUS                NVARCHAR2(1),
  LOAN_AMT                   NUMBER,
  REPAY_PRD                  NVARCHAR2(10),
  FIVE_CATE                  NVARCHAR2(1),
  FIVE_CATE_ADJ_DATE         NVARCHAR2(10),
  RI_EX                      NUMBER,
  COMP_ADV_FLAG              NVARCHAR2(1),
  CLOSE_DATE                 NVARCHAR2(10),
  PDA_GUAR_ACCT_BS_SGMT_ID   NCHAR(32)          NOT NULL,
  RPT_DATE                   NCHAR(10),
  EXTEND1                    NVARCHAR2(100),
  EXTEND2                    NVARCHAR2(100),
  EXTEND3                    NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_GR_REPYMT_INF IS '230-个人担保账户信息记录在保责任信息段';

COMMENT ON COLUMN I_GR_REPYMT_INF.PDE_GR_REPYMT_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_GR_REPYMT_INF.ACCT_STATUS IS '账户状态';

COMMENT ON COLUMN I_GR_REPYMT_INF.LOAN_AMT IS '在保余额';

COMMENT ON COLUMN I_GR_REPYMT_INF.REPAY_PRD IS '余额变化日期';

COMMENT ON COLUMN I_GR_REPYMT_INF.FIVE_CATE IS '五级分类';

COMMENT ON COLUMN I_GR_REPYMT_INF.FIVE_CATE_ADJ_DATE IS '五级分类认定日期';

COMMENT ON COLUMN I_GR_REPYMT_INF.RI_EX IS '风险敞口';

COMMENT ON COLUMN I_GR_REPYMT_INF.COMP_ADV_FLAG IS '代偿（垫款）标志';

COMMENT ON COLUMN I_GR_REPYMT_INF.CLOSE_DATE IS '账户关闭日期';

COMMENT ON COLUMN I_GR_REPYMT_INF.PDA_GUAR_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_GR_REPYMT_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_GR_REPYMT_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_GR_REPYMT_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_GR_REPYMT_INF.EXTEND3 IS '预留字段3';
