DROP TABLE I_GUAR_RLT_REPYMT_INF CASCADE CONSTRAINTS;

CREATE TABLE I_GUAR_RLT_REPYMT_INF
(
  PDC_RLT_REPYMT_INF_SGMT_ID  NCHAR(32)         NOT NULL,
  INFO_ID_TYPE                NVARCHAR2(1),
  ARLP_NAME                   NVARCHAR2(80),
  ARLP_CERT_TYPE              NVARCHAR2(2),
  ARLP_CERT_NUM               NVARCHAR2(40),
  ARLP_TYPE                   NVARCHAR2(1),
  ARLP_AMT                    NUMBER,
  WARTY_SIGN                  NVARCHAR2(1),
  MAX_GUAR_MCC                NVARCHAR2(60),
  PDA_GUAR_ACCT_BS_SGMT_ID    NCHAR(32)         NOT NULL,
  RPT_DATE                    NCHAR(10),
  EXTEND1                     NVARCHAR2(100),
  EXTEND2                     NVARCHAR2(100),
  EXTEND3                     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_GUAR_RLT_REPYMT_INF IS '230-个人担保账户信息记录相关还款责任人段';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.PDC_RLT_REPYMT_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.INFO_ID_TYPE IS '身份类别';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.ARLP_NAME IS '责任人名称';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.ARLP_CERT_TYPE IS '责任人身份标识类型';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.ARLP_CERT_NUM IS '责任人身份标识号码';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.ARLP_TYPE IS '还款责任人类型';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.ARLP_AMT IS '还款责任金额';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.WARTY_SIGN IS '联保标志';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.MAX_GUAR_MCC IS '保证合同编号';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.PDA_GUAR_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_GUAR_RLT_REPYMT_INF.EXTEND3 IS '预留字段3';
