DROP TABLE I_ID CASCADE CONSTRAINTS;

CREATE TABLE I_ID
(
  PAB_ID_SGMT_ID   NCHAR(32)                    NOT NULL,
  ALIAS            NVARCHAR2(30),
  OTH_ID_TYPE      NVARCHAR2(2),
  OTH_ID_NUM       NVARCHAR2(20),
  ID_INFO_UP_DATE  NCHAR(10),
  PAA_BS_SGMT_ID   NCHAR(32)                    NOT NULL,
  RPT_DATE         NCHAR(10),
  EXTEND1          NVARCHAR2(100),
  EXTEND2          NVARCHAR2(100),
  EXTEND3          NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_ID IS '110-个人基本信息记录其他标识段';

COMMENT ON COLUMN I_ID.PAB_ID_SGMT_ID IS '主键';

COMMENT ON COLUMN I_ID.ALIAS IS '姓名';

COMMENT ON COLUMN I_ID.OTH_ID_TYPE IS '证件类型';

COMMENT ON COLUMN I_ID.OTH_ID_NUM IS '证件号码';

COMMENT ON COLUMN I_ID.ID_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN I_ID.PAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_ID.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_ID.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_ID.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_ID.EXTEND3 IS '预留字段3';
