DROP TABLE I_IN_CTRCT_DEL CASCADE CONSTRAINTS;

CREATE TABLE I_IN_CTRCT_DEL
(
  PCY_IN_CTRCT_DEL_ID  NCHAR(32)                NOT NULL,
  INF_REC_TYPE         NVARCHAR2(3),
  DEL_REC_CODE         NVARCHAR2(60),
  DEL_SGMT_CODE        NVARCHAR2(1),
  DEL_START_DATE       NVARCHAR2(10),
  DEL_END_DATE         NVARCHAR2(10),
  LAST_UPDATE_TIME     NVARCHAR2(10),
  OPERATOR_USER        NVARCHAR2(50),
  ORG_NAME             NVARCHAR2(100),
  ORG_CODE             NVARCHAR2(100),
  BUSINESS_STATES      NVARCHAR2(50),
  REJECT_REASON        NVARCHAR2(255),
  IS_FILTER            NCHAR(1),
  REPORT_MESSAGE_ID    NVARCHAR2(60),
  RPT_DATE             NCHAR(10),
  NAME                 NVARCHAR2(30),
  ID_TYPE              NVARCHAR2(2),
  ID_NUM               NVARCHAR2(20),
  EXTEND1              NVARCHAR2(100),
  EXTEND2              NVARCHAR2(100),
  EXTEND3              NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_IN_CTRCT_DEL IS '223-个人授信协议按段删除请求记录';

COMMENT ON COLUMN I_IN_CTRCT_DEL.PCY_IN_CTRCT_DEL_ID IS '主键';

COMMENT ON COLUMN I_IN_CTRCT_DEL.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN I_IN_CTRCT_DEL.DEL_REC_CODE IS '待删除业务标识码';

COMMENT ON COLUMN I_IN_CTRCT_DEL.DEL_SGMT_CODE IS '待删除段段标';

COMMENT ON COLUMN I_IN_CTRCT_DEL.DEL_START_DATE IS '待删除起始日期';

COMMENT ON COLUMN I_IN_CTRCT_DEL.DEL_END_DATE IS '待删除结束日期';

COMMENT ON COLUMN I_IN_CTRCT_DEL.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN I_IN_CTRCT_DEL.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN I_IN_CTRCT_DEL.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN I_IN_CTRCT_DEL.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN I_IN_CTRCT_DEL.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN I_IN_CTRCT_DEL.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN I_IN_CTRCT_DEL.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN I_IN_CTRCT_DEL.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN I_IN_CTRCT_DEL.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_IN_CTRCT_DEL.NAME IS '受信人姓名';

COMMENT ON COLUMN I_IN_CTRCT_DEL.ID_TYPE IS '受信人证件类型';

COMMENT ON COLUMN I_IN_CTRCT_DEL.ID_NUM IS '受信人证件号码';

COMMENT ON COLUMN I_IN_CTRCT_DEL.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_IN_CTRCT_DEL.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_IN_CTRCT_DEL.EXTEND3 IS '预留字段3';
