DROP TABLE I_INC_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_INC_INF_HIST
(
  PAI_INC_INF_SGMT_ID  NCHAR(32)                NOT NULL,
  ANNL_INC             NUMBER,
  TAX_INCOME           NUMBER,
  INC_INFO_UP_DATE     NCHAR(10),
  PAA_BS_SGMT_ID       NCHAR(32)                NOT NULL,
  RPT_DATE             NCHAR(10),
  EXTEND1              NVARCHAR2(100),
  EXTEND2              NVARCHAR2(100),
  EXTEND3              NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_INC_INF_HIST IS '110-个人基本信息记录收入信息段';

COMMENT ON COLUMN I_INC_INF_HIST.PAI_INC_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_INC_INF_HIST.ANNL_INC IS '自报年收入';

COMMENT ON COLUMN I_INC_INF_HIST.TAX_INCOME IS '纳税年收入';

COMMENT ON COLUMN I_INC_INF_HIST.INC_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN I_INC_INF_HIST.PAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_INC_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_INC_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_INC_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_INC_INF_HIST.EXTEND3 IS '预留字段3';
