DROP TABLE I_IN_ACCT_ENT_DEL_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_IN_ACCT_ENT_DEL_HIST
(
  PBZ_IN_ACCT_ENT_DEL_ID  NCHAR(32)             NOT NULL,
  INF_REC_TYPE            NVARCHAR2(3),
  ACCT_TYPE               NVARCHAR2(2),
  DEL_REC_CODE            NVARCHAR2(60),
  LAST_UPDATE_TIME        NVARCHAR2(10),
  OPERATOR_USER           NVARCHAR2(50),
  ORG_NAME                NVARCHAR2(100),
  ORG_CODE                NVARCHAR2(100),
  BUSINESS_STATES         NVARCHAR2(50),
  REJECT_REASON           NVARCHAR2(255),
  IS_FILTER               NCHAR(1),
  REPORT_MESSAGE_ID       NVARCHAR2(60),
  RPT_DATE                NCHAR(10),
  NAME                    NVARCHAR2(30),
  ID_TYPE                 NVARCHAR2(2),
  ID_NUM                  NVARCHAR2(20),
  EXTEND1                 NVARCHAR2(100),
  EXTEND2                 NVARCHAR2(100),
  EXTEND3                 NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_IN_ACCT_ENT_DEL_HIST IS '214-个人借贷账户整笔删除请求记录';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.PBZ_IN_ACCT_ENT_DEL_ID IS '主键';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.ACCT_TYPE IS '账户类型';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.DEL_REC_CODE IS '待删除业务标识码';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.NAME IS '借款人姓名';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.ID_TYPE IS '借款人证件类型';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.ID_NUM IS '借款人证件号码';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_IN_ACCT_ENT_DEL_HIST.EXTEND3 IS '预留字段3';
