DROP TABLE I_IN_SPC_EVT_DSC_INF CASCADE CONSTRAINTS;

CREATE TABLE I_IN_SPC_EVT_DSC_INF
(
  PBK_IN_SPC_EVT_DSC_INF_ID  NCHAR(32)          NOT NULL,
  INF_REC_TYPE               NVARCHAR2(3),
  ACCT_TYPE                  NVARCHAR2(2),
  ACCT_CODE                  NVARCHAR2(60),
  OPETN_TYPE                 NVARCHAR2(2),
  MONTH                      NVARCHAR2(7),
  FLAG                       NVARCHAR2(1),
  RPT_DATE                   NCHAR(10),
  LAST_UPDATE_TIME           NVARCHAR2(10),
  OPERATOR_USER              NVARCHAR2(50),
  ORG_NAME                   NVARCHAR2(100),
  ORG_CODE                   NVARCHAR2(100),
  BUSINESS_STATES            NVARCHAR2(50),
  REJECT_REASON              NVARCHAR2(255),
  IS_FILTER                  NCHAR(1),
  REPORT_MESSAGE_ID          NVARCHAR2(60),
  NAME                       NVARCHAR2(30),
  ID_TYPE                    NVARCHAR2(2),
  ID_NUM                     NVARCHAR2(20),
  EXTEND1                    NVARCHAR2(100),
  EXTEND2                    NVARCHAR2(100),
  EXTEND3                    NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_IN_SPC_EVT_DSC_INF IS '215-个人借贷账户特殊事件说明记录';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.PBK_IN_SPC_EVT_DSC_INF_ID IS '主键';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.ACCT_TYPE IS '账户类型';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.ACCT_CODE IS '账户标识码';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.OPETN_TYPE IS '事件类型';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.MONTH IS '发生月份';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.FLAG IS '生效标志';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.RPT_DATE IS '信息报告日期';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.NAME IS '借款人姓名';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.ID_TYPE IS '借款人证件类型';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.ID_NUM IS '借款人证件号码';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF.EXTEND3 IS '预留字段3';



CREATE UNIQUE INDEX PBK_IN_SPC_EVT_DSC_INF_ID ON I_IN_SPC_EVT_DSC_INF
(PBK_IN_SPC_EVT_DSC_INF_ID)
NOPARALLEL;


ALTER TABLE I_IN_SPC_EVT_DSC_INF ADD (
  CONSTRAINT PBK_IN_SPC_EVT_DSC_INF_ID
  UNIQUE (PBK_IN_SPC_EVT_DSC_INF_ID)
  USING INDEX PBK_IN_SPC_EVT_DSC_INF_ID
  ENABLE VALIDATE);
