DROP TABLE I_IN_SPC_EVT_DSC_INF_MIDDLE CASCADE CONSTRAINTS;

CREATE TABLE I_IN_SPC_EVT_DSC_INF_MIDDLE
(
  ACCT_TYPE  NVARCHAR2(36)                      NOT NULL,
  ACCT_CODE  NVARCHAR2(60)                      NOT NULL,
  EXTEND1    NVARCHAR2(100),
  EXTEND2    NVARCHAR2(100),
  EXTEND3    NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_IN_SPC_EVT_DSC_INF_MIDDLE IS '215-个人借贷账户特殊事件说明记录中间表';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF_MIDDLE.ACCT_TYPE IS '账户类型';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF_MIDDLE.ACCT_CODE IS '账户标识码';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF_MIDDLE.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF_MIDDLE.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_IN_SPC_EVT_DSC_INF_MIDDLE.EXTEND3 IS '预留字段3';
