DROP TABLE I_LOAN_RLT_REPYMT_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_LOAN_RLT_REPYMT_INF_HIST
(
  PBC_RLT_REPYMT_INF_SGMT_ID  NCHAR(32)         NOT NULL,
  INFO_ID_TYPE                NVARCHAR2(1),
  ARLP_NAME                   NVARCHAR2(80),
  ARLP_CERT_TYPE              NVARCHAR2(2),
  ARLP_CERT_NUM               NVARCHAR2(40),
  ARLP_TYPE                   NVARCHAR2(1),
  ARLP_AMT                    NUMBER,
  WARTY_SIGN                  NVARCHAR2(1),
  MAX_GUAR_MCC                NVARCHAR2(60),
  PBA_ACCT_BS_SGMT_ID         NCHAR(32)         NOT NULL,
  RPT_DATE                    NCHAR(10),
  EXTEND1                     NVARCHAR2(100),
  EXTEND2                     NVARCHAR2(100),
  EXTEND3                     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_LOAN_RLT_REPYMT_INF_HIST IS '210-个人借贷账户信息记录相关还款责任人段';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.PBC_RLT_REPYMT_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.INFO_ID_TYPE IS '身份类别';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.ARLP_NAME IS '责任人名称';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.ARLP_CERT_TYPE IS '责任人身份标识类型';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.ARLP_CERT_NUM IS '责任人身份标识号码';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.ARLP_TYPE IS '还款责任人类型';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.ARLP_AMT IS '还款责任金额';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.WARTY_SIGN IS '联保标志';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.MAX_GUAR_MCC IS '保证合同编号';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_LOAN_RLT_REPYMT_INF_HIST.EXTEND3 IS '预留字段3';
