DROP TABLE I_MLG_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_MLG_INF_HIST
(
  PAG_MLG_INF_SGMT_ID  NCHAR(32)                NOT NULL,
  MAIL_ADDR            NVARCHAR2(100),
  MAIL_PC              NVARCHAR2(6),
  MAIL_DIST            NVARCHAR2(6),
  MLG_INFO_UP_DATE     NCHAR(10),
  PAA_BS_SGMT_ID       NCHAR(32)                NOT NULL,
  RPT_DATE             NCHAR(10),
  EXTEND1              NVARCHAR2(100),
  EXTEND2              NVARCHAR2(100),
  EXTEND3              NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_MLG_INF_HIST IS '110-个人基本信息记录通讯地址段';

COMMENT ON COLUMN I_MLG_INF_HIST.PAG_MLG_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_MLG_INF_HIST.MAIL_ADDR IS '通讯地址';

COMMENT ON COLUMN I_MLG_INF_HIST.MAIL_PC IS '通讯地邮编';

COMMENT ON COLUMN I_MLG_INF_HIST.MAIL_DIST IS '通讯地行政区划';

COMMENT ON COLUMN I_MLG_INF_HIST.MLG_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN I_MLG_INF_HIST.PAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_MLG_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_MLG_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_MLG_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_MLG_INF_HIST.EXTEND3 IS '预留字段3';
