DROP TABLE I_OC_INF CASCADE CONSTRAINTS;

CREATE TABLE I_OC_INF
(
  PBF_OC_INF_SGMT_ID   NCHAR(32)                NOT NULL,
  INIT_CRED_NAME       NVARCHAR2(80),
  INIT_CRED_ORG_NM     NVARCHAR2(18),
  ORIG_DBT_CATE        NVARCHAR2(1),
  INIT_RPY_STS         NVARCHAR2(1),
  PBA_ACCT_BS_SGMT_ID  NCHAR(32)                NOT NULL,
  RPT_DATE             NCHAR(10),
  EXTEND1              NVARCHAR2(100),
  EXTEND2              NVARCHAR2(100),
  EXTEND3              NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_OC_INF IS '210-个人借贷账户信息记录初始债权说明段';

COMMENT ON COLUMN I_OC_INF.PBF_OC_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_OC_INF.INIT_CRED_NAME IS '初始债权人名称';

COMMENT ON COLUMN I_OC_INF.INIT_CRED_ORG_NM IS '初始债权人机构代码';

COMMENT ON COLUMN I_OC_INF.ORIG_DBT_CATE IS '原债务种类';

COMMENT ON COLUMN I_OC_INF.INIT_RPY_STS IS '债权转移时的还款状态';

COMMENT ON COLUMN I_OC_INF.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_OC_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_OC_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_OC_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_OC_INF.EXTEND3 IS '预留字段3';
