DROP TABLE I_OCTPN_INF CASCADE CONSTRAINTS;

CREATE TABLE I_OCTPN_INF
(
  PAE_OCTPN_INF_SGMT_ID  NCHAR(32)              NOT NULL,
  EMP_STATUS             NVARCHAR2(2),
  CPN_NAME               NVARCHAR2(80),
  CPN_TYPE               NVARCHAR2(2),
  INDUSTRY               NVARCHAR2(1),
  CPN_ADDR               NVARCHAR2(100),
  CPN_PC                 NVARCHAR2(6),
  CPN_DIST               NVARCHAR2(6),
  CPN_T_E_L              NVARCHAR2(25),
  OCCUPATION             NVARCHAR2(1),
  TITLE                  NVARCHAR2(1),
  TECH_TITLE             NVARCHAR2(1),
  WORK_START_DATE        NCHAR(4),
  OCTPN_INFO_UP_DATE     NCHAR(10),
  PAA_BS_SGMT_ID         NCHAR(32)              NOT NULL,
  RPT_DATE               NCHAR(10),
  EXTEND1                NVARCHAR2(100),
  EXTEND2                NVARCHAR2(100),
  EXTEND3                NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_OCTPN_INF IS '110-个人基本信息记录职业信息段';

COMMENT ON COLUMN I_OCTPN_INF.PAE_OCTPN_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_OCTPN_INF.EMP_STATUS IS '就业状况';

COMMENT ON COLUMN I_OCTPN_INF.CPN_NAME IS '单位名称';

COMMENT ON COLUMN I_OCTPN_INF.CPN_TYPE IS '单位性质';

COMMENT ON COLUMN I_OCTPN_INF.INDUSTRY IS '单位所属行业';

COMMENT ON COLUMN I_OCTPN_INF.CPN_ADDR IS '单位详细地址';

COMMENT ON COLUMN I_OCTPN_INF.CPN_PC IS '单位所在地邮编';

COMMENT ON COLUMN I_OCTPN_INF.CPN_DIST IS '单位所在地行政区划';

COMMENT ON COLUMN I_OCTPN_INF.CPN_T_E_L IS '单位电话';

COMMENT ON COLUMN I_OCTPN_INF.OCCUPATION IS '职业';

COMMENT ON COLUMN I_OCTPN_INF.TITLE IS '职务';

COMMENT ON COLUMN I_OCTPN_INF.TECH_TITLE IS '职称';

COMMENT ON COLUMN I_OCTPN_INF.WORK_START_DATE IS '本单位工作起始年份';

COMMENT ON COLUMN I_OCTPN_INF.OCTPN_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN I_OCTPN_INF.PAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_OCTPN_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_OCTPN_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_OCTPN_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_OCTPN_INF.EXTEND3 IS '预留字段3';
