ALTER TABLE I_PANEL_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE I_PANEL_DATA CASCADE CONSTRAINTS;

CREATE TABLE I_PANEL_DATA
(
  EXTRACTION_DATE         CHAR(10 BYTE)         DEFAULT to_char(sysdate,'yyyy-mm-dd') NOT NULL,
  TOTAL_COUNT             VARCHAR2(8 BYTE)      NOT NULL,
  CHECK_ERROR_COUNT       VARCHAR2(8 BYTE)      NOT NULL,
  AWAIT_GENERATE_COUNT    VARCHAR2(8 BYTE)      NOT NULL,
  AWAIT_REPORT_COUNT      VARCHAR2(8 BYTE)      NOT NULL,
  AWAIT_FEEDBACK_COUNT    VARCHAR2(8 BYTE)      NOT NULL,
  FEEDBACK_ERROE_PENDING  VARCHAR2(8 BYTE)      NOT NULL,
  REPORTED                NVARCHAR2(8),
  REPORTED_SUCCESS        NVARCHAR2(8),
  EXTEND3                 NVARCHAR2(10)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_PANEL_DATA IS '报送数据统计';

COMMENT ON COLUMN I_PANEL_DATA.EXTRACTION_DATE IS '提取日期';

COMMENT ON COLUMN I_PANEL_DATA.TOTAL_COUNT IS '总记录数';

COMMENT ON COLUMN I_PANEL_DATA.CHECK_ERROR_COUNT IS '校验出错记录数';

COMMENT ON COLUMN I_PANEL_DATA.AWAIT_GENERATE_COUNT IS '待生成报文记录数';

COMMENT ON COLUMN I_PANEL_DATA.AWAIT_REPORT_COUNT IS '待报送记录数';

COMMENT ON COLUMN I_PANEL_DATA.AWAIT_FEEDBACK_COUNT IS '待反馈记录数';

COMMENT ON COLUMN I_PANEL_DATA.FEEDBACK_ERROE_PENDING IS '反馈错误待处理数';

COMMENT ON COLUMN I_PANEL_DATA.REPORTED IS '已上报';

COMMENT ON COLUMN I_PANEL_DATA.REPORTED_SUCCESS IS '上报成功';

COMMENT ON COLUMN I_PANEL_DATA.EXTEND3 IS '预留字段3';



CREATE UNIQUE INDEX I_PANEL_DATA_PK ON I_PANEL_DATA
(EXTRACTION_DATE)
NOPARALLEL;


ALTER TABLE I_PANEL_DATA ADD (
  CONSTRAINT I_PANEL_DATA_PK
  PRIMARY KEY
  (EXTRACTION_DATE)
  USING INDEX I_PANEL_DATA_PK
  ENABLE VALIDATE);
