DROP TABLE I_REDNC_INF_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_REDNC_INF_HIST
(
  PAF_REDNC_INF_SGMT_ID  NCHAR(32)              NOT NULL,
  RESI_STATUS            NVARCHAR2(2),
  RESI_ADDR              NVARCHAR2(100),
  RESI_PC                NVARCHAR2(6),
  RESI_DIST              NVARCHAR2(6),
  HOME_TEL               NVARCHAR2(25),
  RESI_INFO_UP_DATE      NCHAR(10),
  PAA_BS_SGMT_ID         NCHAR(32)              NOT NULL,
  RPT_DATE               NCHAR(10),
  EXTEND1                NVARCHAR2(100),
  EXTEND2                NVARCHAR2(100),
  EXTEND3                NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_REDNC_INF_HIST IS '110-个人基本信息记录居住地址段';

COMMENT ON COLUMN I_REDNC_INF_HIST.PAF_REDNC_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_REDNC_INF_HIST.RESI_STATUS IS '居住状况';

COMMENT ON COLUMN I_REDNC_INF_HIST.RESI_ADDR IS '居住地详细地址';

COMMENT ON COLUMN I_REDNC_INF_HIST.RESI_PC IS '居住地邮编';

COMMENT ON COLUMN I_REDNC_INF_HIST.RESI_DIST IS '居住地行政区划';

COMMENT ON COLUMN I_REDNC_INF_HIST.HOME_TEL IS '住宅电话';

COMMENT ON COLUMN I_REDNC_INF_HIST.RESI_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN I_REDNC_INF_HIST.PAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_REDNC_INF_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_REDNC_INF_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_REDNC_INF_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_REDNC_INF_HIST.EXTEND3 IS '预留字段3';
