DROP TABLE I_SPS_INF CASCADE CONSTRAINTS;

CREATE TABLE I_SPS_INF
(
  PAH_SPS_INF_SGMT_ID  NCHAR(32)                NOT NULL,
  MARI_STATUS          NVARCHAR2(2),
  SPO_NAME             NVARCHAR2(30),
  SPO_ID_TYPE          NVARCHAR2(2),
  SPO_ID_NUM           NVARCHAR2(20),
  SPO_TEL              NVARCHAR2(25),
  SPS_CMPY_NM          NVARCHAR2(80),
  SPS_INFO_UP_DATE     NCHAR(10),
  PAA_BS_SGMT_ID       NCHAR(32)                NOT NULL,
  RPT_DATE             NCHAR(10),
  EXTEND1              NVARCHAR2(100),
  EXTEND2              NVARCHAR2(100),
  EXTEND3              NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_SPS_INF IS '110-个人基本信息记录婚姻信息段';

COMMENT ON COLUMN I_SPS_INF.PAH_SPS_INF_SGMT_ID IS '主键';

COMMENT ON COLUMN I_SPS_INF.MARI_STATUS IS '婚姻状况';

COMMENT ON COLUMN I_SPS_INF.SPO_NAME IS '配偶姓名';

COMMENT ON COLUMN I_SPS_INF.SPO_ID_TYPE IS '配偶证件类型';

COMMENT ON COLUMN I_SPS_INF.SPO_ID_NUM IS '配偶证件号码';

COMMENT ON COLUMN I_SPS_INF.SPO_TEL IS '配偶联系电话';

COMMENT ON COLUMN I_SPS_INF.SPS_CMPY_NM IS '配偶工作单位';

COMMENT ON COLUMN I_SPS_INF.SPS_INFO_UP_DATE IS '信息更新日期';

COMMENT ON COLUMN I_SPS_INF.PAA_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_SPS_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_SPS_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_SPS_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_SPS_INF.EXTEND3 IS '预留字段3';
