DROP TABLE I_SPEC_PRD_HIST CASCADE CONSTRAINTS;

CREATE TABLE I_SPEC_PRD_HIST
(
  PBH_SPEC_PRD_SGMT_ID  NCHAR(32)               NOT NULL,
  SPEC_LINE             NUMBER,
  SPEC_EFCT_DATE        NVARCHAR2(10),
  SPEC_END_DATE         NVARCHAR2(10),
  USED_INST_AMT         NUMBER,
  PBA_ACCT_BS_SGMT_ID   NCHAR(32)               NOT NULL,
  RPT_DATE              NCHAR(10),
  EXTEND1               NVARCHAR2(100),
  EXTEND2               NVARCHAR2(100),
  EXTEND3               NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE I_SPEC_PRD_HIST IS '210-个人借贷账户信息记录大额专项分期信息段';

COMMENT ON COLUMN I_SPEC_PRD_HIST.PBH_SPEC_PRD_SGMT_ID IS '主键';

COMMENT ON COLUMN I_SPEC_PRD_HIST.SPEC_LINE IS '大额专项分期额度';

COMMENT ON COLUMN I_SPEC_PRD_HIST.SPEC_EFCT_DATE IS '分期额度生效日期';

COMMENT ON COLUMN I_SPEC_PRD_HIST.SPEC_END_DATE IS '分期额度到期日期';

COMMENT ON COLUMN I_SPEC_PRD_HIST.USED_INST_AMT IS '已用分期金额';

COMMENT ON COLUMN I_SPEC_PRD_HIST.PBA_ACCT_BS_SGMT_ID IS '数据外键';

COMMENT ON COLUMN I_SPEC_PRD_HIST.RPT_DATE IS '报送日期';

COMMENT ON COLUMN I_SPEC_PRD_HIST.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN I_SPEC_PRD_HIST.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN I_SPEC_PRD_HIST.EXTEND3 IS '预留字段3';
