DROP TABLE KETTLE_REPOSITORY CASCADE CONSTRAINTS;

CREATE TABLE KETTLE_REPOSITORY
(
  REPOSITORY_ID  NVARCHAR2(36)                  NOT NULL,
  NAME           NVARCHAR2(50)                  NOT NULL,
  PATH           NVARCHAR2(255)                 NOT NULL,
  CREATE_TIME    NVARCHAR2(10),
  EXTERNAL_CODE  NVARCHAR2(50)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE KETTLE_REPOSITORY IS 'kettle资源库';

COMMENT ON COLUMN KETTLE_REPOSITORY.NAME IS '资源库名称';

COMMENT ON COLUMN KETTLE_REPOSITORY.PATH IS '路径';

COMMENT ON COLUMN KETTLE_REPOSITORY.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN KETTLE_REPOSITORY.EXTERNAL_CODE IS '外部编号';
