DROP TABLE MOC_ID_CAGS_INF CASCADE CONSTRAINTS;

CREATE TABLE MOC_ID_CAGS_INF
(
  EFW_MOC_ID_CAGS_INF_ID  NCHAR(32)             NOT NULL,
  INF_REC_TYPE            NCHAR(3),
  OD_BNES_CODE            NVARCHAR2(60),
  NW_BNES_CODE            NVARCHAR2(60),
  LAST_UPDATE_TIME        NVARCHAR2(10),
  OPERATOR_USER           NVARCHAR2(50),
  ORG_NAME                NVARCHAR2(100),
  ORG_CODE                NVARCHAR2(100),
  BUSINESS_STATES         NVARCHAR2(50),
  REJECT_REASON           NVARCHAR2(255),
  IS_FILTER               NCHAR(1),
  REPORT_MESSAGE_ID       NVARCHAR2(60),
  RPT_DATE                NCHAR(10),
  INFO_ID_TYPE            NCHAR(1),
  NAME                    NVARCHAR2(80),
  CERT_TYPE               NVARCHAR2(2),
  CERT_NUM                NVARCHAR2(60),
  EXTEND1                 NVARCHAR2(100),
  EXTEND2                 NVARCHAR2(100),
  EXTEND3                 NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOC_ID_CAGS_INF IS '511-抵（质）押合同信息标识变更类请求';

COMMENT ON COLUMN MOC_ID_CAGS_INF.EFW_MOC_ID_CAGS_INF_ID IS '511-抵（质）押合同信息标识变更类请求主键';

COMMENT ON COLUMN MOC_ID_CAGS_INF.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN MOC_ID_CAGS_INF.OD_BNES_CODE IS '原业务标识码';

COMMENT ON COLUMN MOC_ID_CAGS_INF.NW_BNES_CODE IS '新业务标识码';

COMMENT ON COLUMN MOC_ID_CAGS_INF.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN MOC_ID_CAGS_INF.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN MOC_ID_CAGS_INF.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN MOC_ID_CAGS_INF.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN MOC_ID_CAGS_INF.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN MOC_ID_CAGS_INF.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN MOC_ID_CAGS_INF.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN MOC_ID_CAGS_INF.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN MOC_ID_CAGS_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN MOC_ID_CAGS_INF.INFO_ID_TYPE IS '债务人身份类别';

COMMENT ON COLUMN MOC_ID_CAGS_INF.NAME IS '债务人名称';

COMMENT ON COLUMN MOC_ID_CAGS_INF.CERT_TYPE IS '债务人身份标识类型';

COMMENT ON COLUMN MOC_ID_CAGS_INF.CERT_NUM IS '债务人身份标识号码';

COMMENT ON COLUMN MOC_ID_CAGS_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN MOC_ID_CAGS_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN MOC_ID_CAGS_INF.EXTEND3 IS '预留字段3';
