DROP TABLE MOTGA_CLTAL_BS_INF CASCADE CONSTRAINTS;

CREATE TABLE MOTGA_CLTAL_BS_INF
(
  EFB_MOTGA_CLTAL_BS_INF_SGMT_ID  NCHAR(32)     NOT NULL,
  GUAR_TYPE                       NCHAR(1),
  CC_AMT                          NUMBER,
  CY                              NCHAR(3),
  CC_VAL_DATE                     NVARCHAR2(10),
  CC_EXP_DATE                     NVARCHAR2(10),
  MAX_GUAR                        NCHAR(1),
  CC_STATUS                       NCHAR(1),
  EFA_MOTGA_CLTAL_CTRCT_BS_ID     NCHAR(32)     NOT NULL,
  RPT_DATE                        NCHAR(10),
  EXTEND1                         NVARCHAR2(100),
  EXTEND2                         NVARCHAR2(100),
  EXTEND3                         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOTGA_CLTAL_BS_INF IS '510-抵（质）押合同信息基本信息段';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.EFB_MOTGA_CLTAL_BS_INF_SGMT_ID IS '510-抵（质）押合同信息基本信息段主键';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.GUAR_TYPE IS '合同类型';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.CC_AMT IS '抵（质）押合同金额';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.CY IS '币种';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.CC_VAL_DATE IS '抵（质）押合同生效日期';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.CC_EXP_DATE IS '抵（质）押合同到期日期';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.MAX_GUAR IS '最高额担保标志';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.CC_STATUS IS '抵（质）押合同状态';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.EFA_MOTGA_CLTAL_CTRCT_BS_ID IS '数据外键';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN MOTGA_CLTAL_BS_INF.EXTEND3 IS '预留字段3';
