DROP TABLE MOTGA_PROPT_INF CASCADE CONSTRAINTS;

CREATE TABLE MOTGA_PROPT_INF
(
  EFD_MOTGA_PROPT_INF_SGMT_ID  NCHAR(32)        NOT NULL,
  PLE_TYPE                     NCHAR(2),
  MOTGA_PROPT_ID_TYPE          NCHAR(1),
  PLE_CERT_ID                  NVARCHAR2(40),
  PLE_DISTR                    NCHAR(6),
  PLE_VALUE                    NUMBER,
  PLE_CY                       NCHAR(3),
  VAL_ORG_TYPE                 NCHAR(1),
  VAL_DATE                     NVARCHAR2(10),
  PLEDGOR_TYPE                 NCHAR(1),
  PLEDGOR_NAME                 NVARCHAR2(80),
  PLEOR_CERT_TYPE              NVARCHAR2(2),
  PLEOR_CERT_NUM               NVARCHAR2(40),
  PLE_DESC                     NVARCHAR2(200),
  EFA_MOTGA_CLTAL_CTRCT_BS_ID  NCHAR(32)        NOT NULL,
  RPT_DATE                     NCHAR(10),
  EXTEND1                      NVARCHAR2(100),
  EXTEND2                      NVARCHAR2(100),
  EXTEND3                      NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOTGA_PROPT_INF IS '510-抵（质）押合同信息抵押物信息';

COMMENT ON COLUMN MOTGA_PROPT_INF.EFD_MOTGA_PROPT_INF_SGMT_ID IS '510-抵（质）押合同信息抵押物信息主键';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLE_TYPE IS '抵押物种类';

COMMENT ON COLUMN MOTGA_PROPT_INF.MOTGA_PROPT_ID_TYPE IS '抵押物识别号类型';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLE_CERT_ID IS '抵押物唯一识别号';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLE_DISTR IS '抵押物位置所在地行政区划';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLE_VALUE IS '抵押物评估价值';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLE_CY IS '币种';

COMMENT ON COLUMN MOTGA_PROPT_INF.VAL_ORG_TYPE IS '评估机构类型';

COMMENT ON COLUMN MOTGA_PROPT_INF.VAL_DATE IS '抵押物评估日期';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLEDGOR_TYPE IS '抵押人身份类别';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLEDGOR_NAME IS '抵押人名称';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLEOR_CERT_TYPE IS '抵押人身份标识类型';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLEOR_CERT_NUM IS '抵押人身份标识号码';

COMMENT ON COLUMN MOTGA_PROPT_INF.PLE_DESC IS '抵押物说明';

COMMENT ON COLUMN MOTGA_PROPT_INF.EFA_MOTGA_CLTAL_CTRCT_BS_ID IS '数据外键';

COMMENT ON COLUMN MOTGA_PROPT_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN MOTGA_PROPT_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN MOTGA_PROPT_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN MOTGA_PROPT_INF.EXTEND3 IS '预留字段3';
