DROP TABLE MOTGA_CLTAL_CTRCT_BS CASCADE CONSTRAINTS;

CREATE TABLE MOTGA_CLTAL_CTRCT_BS
(
  EFA_MOTGA_CLTAL_CTRCT_BS_ID  NCHAR(32)        NOT NULL,
  INF_REC_TYPE                 NCHAR(3),
  CC_CODE                      NVARCHAR2(60),
  RPT_DATE                     NCHAR(10),
  RPT_DATE_CODE                NCHAR(2),
  INFO_ID_TYPE                 NCHAR(1),
  NAME                         NVARCHAR2(80),
  CERT_TYPE                    NVARCHAR2(2),
  CERT_NUM                     NVARCHAR2(60),
  MNGMT_ORG_CODE               NCHAR(14),
  LAST_UPDATE_TIME             NVARCHAR2(10),
  OPERATOR_USER                NVARCHAR2(50),
  ORG_NAME                     NVARCHAR2(100),
  ORG_CODE                     NVARCHAR2(100),
  BUSINESS_STATES              NVARCHAR2(50),
  REJECT_REASON                NVARCHAR2(255),
  IS_FILTER                    NCHAR(1),
  REPORT_MESSAGE_ID            NVARCHAR2(60),
  EXTEND1                      NVARCHAR2(100),
  EXTEND2                      NVARCHAR2(100),
  EXTEND3                      NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOTGA_CLTAL_CTRCT_BS IS '510-抵（质）押合同信息基础段';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.EFA_MOTGA_CLTAL_CTRCT_BS_ID IS '510-抵（质）押合同信息基础段主键';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.CC_CODE IS '抵（质）押合同标识码';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.RPT_DATE IS '信息报告日期';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.RPT_DATE_CODE IS '报告时点说明代码';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.INFO_ID_TYPE IS '债务人身份类别';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.NAME IS '债务人名称';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.CERT_TYPE IS '债务人身份标识类型';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.CERT_NUM IS '债务人身份标识号码';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.MNGMT_ORG_CODE IS '业务管理机构代码';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.LAST_UPDATE_TIME IS '最后更新时间';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.OPERATOR_USER IS '操作员';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.ORG_NAME IS '数据来源机构名称';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.ORG_CODE IS '数据来源机构编号';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.BUSINESS_STATES IS '数据状态';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.REJECT_REASON IS '驳回原因';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.IS_FILTER IS '是否过滤标识(默认为N-不过滤)';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS.EXTEND3 IS '预留字段3';
