DROP TABLE MOTGA_COM_REC_INF CASCADE CONSTRAINTS;

CREATE TABLE MOTGA_COM_REC_INF
(
  EFC_COM_REC_INF_SGMT_ID      NCHAR(32)        NOT NULL,
  INFO_ID_TYPE                 NCHAR(1),
  GUAR_NAME                    NVARCHAR2(80),
  GUAR_CERT_TYPE               NVARCHAR2(2),
  GUAR_CERT_NUM                NVARCHAR2(40),
  EFA_MOTGA_CLTAL_CTRCT_BS_ID  NCHAR(32)        NOT NULL,
  RPT_DATE                     NCHAR(10),
  EXTEND1                      NVARCHAR2(100),
  EXTEND2                      NVARCHAR2(100),
  EXTEND3                      NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOTGA_COM_REC_INF IS '510-抵（质）押合同信息其他债务人信息';

COMMENT ON COLUMN MOTGA_COM_REC_INF.EFC_COM_REC_INF_SGMT_ID IS '510-抵（质）押合同信息其他债务人信息主键';

COMMENT ON COLUMN MOTGA_COM_REC_INF.INFO_ID_TYPE IS '身份类别';

COMMENT ON COLUMN MOTGA_COM_REC_INF.GUAR_NAME IS '其他债务人名称';

COMMENT ON COLUMN MOTGA_COM_REC_INF.GUAR_CERT_TYPE IS '其他债务人身份标识类型';

COMMENT ON COLUMN MOTGA_COM_REC_INF.GUAR_CERT_NUM IS '其他债务人身份标识号码';

COMMENT ON COLUMN MOTGA_COM_REC_INF.EFA_MOTGA_CLTAL_CTRCT_BS_ID IS '数据外键';

COMMENT ON COLUMN MOTGA_COM_REC_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN MOTGA_COM_REC_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN MOTGA_COM_REC_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN MOTGA_COM_REC_INF.EXTEND3 IS '预留字段3';
