DROP TABLE MOTGA_CLTAL_INF CASCADE CONSTRAINTS;

CREATE TABLE MOTGA_CLTAL_INF
(
  EFE_CLTAL_INF_SGMT_ID        NCHAR(32)        NOT NULL,
  IMP_TYPE                     NCHAR(2),
  IMP_VAL                      NUMBER,
  IMP_CY                       NCHAR(3),
  IPPC                         NCHAR(1),
  PAWN_NAME                    NVARCHAR2(80),
  PAWN_CERT_TYPE               NVARCHAR2(2),
  PAWN_CERT_NUM                NVARCHAR2(40),
  EFA_MOTGA_CLTAL_CTRCT_BS_ID  NCHAR(32)        NOT NULL,
  RPT_DATE                     NCHAR(10),
  EXTEND1                      NVARCHAR2(100),
  EXTEND2                      NVARCHAR2(100),
  EXTEND3                      NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOTGA_CLTAL_INF IS '510-抵（质）押合同信息质押物信息';

COMMENT ON COLUMN MOTGA_CLTAL_INF.EFE_CLTAL_INF_SGMT_ID IS '510-抵（质）押合同信息质押物信息主键';

COMMENT ON COLUMN MOTGA_CLTAL_INF.IMP_TYPE IS '质物种类';

COMMENT ON COLUMN MOTGA_CLTAL_INF.IMP_VAL IS '质物价值';

COMMENT ON COLUMN MOTGA_CLTAL_INF.IMP_CY IS '币种';

COMMENT ON COLUMN MOTGA_CLTAL_INF.IPPC IS '出质人类型';

COMMENT ON COLUMN MOTGA_CLTAL_INF.PAWN_NAME IS '出质人名称';

COMMENT ON COLUMN MOTGA_CLTAL_INF.PAWN_CERT_TYPE IS '出质人身份标识类型';

COMMENT ON COLUMN MOTGA_CLTAL_INF.PAWN_CERT_NUM IS '出质人身份标识号码';

COMMENT ON COLUMN MOTGA_CLTAL_INF.EFA_MOTGA_CLTAL_CTRCT_BS_ID IS '数据外键';

COMMENT ON COLUMN MOTGA_CLTAL_INF.RPT_DATE IS '报送日期';

COMMENT ON COLUMN MOTGA_CLTAL_INF.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN MOTGA_CLTAL_INF.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN MOTGA_CLTAL_INF.EXTEND3 IS '预留字段3';
