DROP TABLE MOTGA_CLTAL_CTRCT_BS_MIDDLE CASCADE CONSTRAINTS;

CREATE TABLE MOTGA_CLTAL_CTRCT_BS_MIDDLE
(
  CC_CODE  NVARCHAR2(60)                        NOT NULL,
  EXTEND1  NVARCHAR2(100),
  EXTEND2  NVARCHAR2(100),
  EXTEND3  NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MOTGA_CLTAL_CTRCT_BS_MIDDLE IS '510-抵（质）押合同信息基础段中间表';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS_MIDDLE.CC_CODE IS '抵（质）押合同标识码';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS_MIDDLE.EXTEND1 IS '预留字段1';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS_MIDDLE.EXTEND2 IS '预留字段2';

COMMENT ON COLUMN MOTGA_CLTAL_CTRCT_BS_MIDDLE.EXTEND3 IS '预留字段3';
