DROP TABLE OPERATION_LOG CASCADE CONSTRAINTS;

CREATE TABLE OPERATION_LOG
(
  ID                 NVARCHAR2(36)              NOT NULL,
  OPERATION_NAME     NVARCHAR2(100),
  IP                 NVARCHAR2(50),
  CREATE_TIME        NVARCHAR2(10),
  ACTION             NVARCHAR2(2000),
  DESCRIPTION        NVARCHAR2(2000),
  RESULT             NVARCHAR2(50),
  SYS_ORG_CODE       NVARCHAR2(200),
  SYS_ORG_NAME       NVARCHAR2(200),
  LEGAL_PERSON_ID    NVARCHAR2(36),
  LEGAL_PERSON_NAME  NVARCHAR2(100),
  BROWSER            NVARCHAR2(255)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE OPERATION_LOG IS '操作日志表';

COMMENT ON COLUMN OPERATION_LOG.ID IS '主键ID';

COMMENT ON COLUMN OPERATION_LOG.OPERATION_NAME IS '操作人';

COMMENT ON COLUMN OPERATION_LOG.IP IS '操作IP地址';

COMMENT ON COLUMN OPERATION_LOG.CREATE_TIME IS '操作时间';

COMMENT ON COLUMN OPERATION_LOG.ACTION IS '动作';

COMMENT ON COLUMN OPERATION_LOG.DESCRIPTION IS '描述信息';

COMMENT ON COLUMN OPERATION_LOG.RESULT IS '操作成功|操作失败';

COMMENT ON COLUMN OPERATION_LOG.SYS_ORG_CODE IS '机构编号';

COMMENT ON COLUMN OPERATION_LOG.SYS_ORG_NAME IS '机构名称';

COMMENT ON COLUMN OPERATION_LOG.LEGAL_PERSON_ID IS '法人ID';

COMMENT ON COLUMN OPERATION_LOG.LEGAL_PERSON_NAME IS '法人名称';

COMMENT ON COLUMN OPERATION_LOG.BROWSER IS '浏览器信息';
