DROP TABLE PC_DISSENTINFO CASCADE CONSTRAINTS;

CREATE TABLE PC_DISSENTINFO
(
  DISSENTTYPE          NVARCHAR2(2)             NOT NULL,
  OBJCHECKID           VARCHAR2(60 BYTE)        NOT NULL,
  OBJCHECKNUM          VARCHAR2(30 BYTE)        NOT NULL,
  CHECKBEGINDATE       DATE,
  CUSTNAME             NVARCHAR2(80)            NOT NULL,
  IDTYPE               VARCHAR2(2 BYTE)         NOT NULL,
  IDCODE               VARCHAR2(40 BYTE)        NOT NULL,
  PHONENUM             VARCHAR2(11 BYTE)        NOT NULL,
  OBJITEMINF           VARCHAR2(20 BYTE)        NOT NULL,
  OBJITEMDESC          NVARCHAR2(200)           NOT NULL,
  DATAPROVIDERORGCODE  VARCHAR2(14 BYTE)        NOT NULL,
  DATAOCCURORGCODE     VARCHAR2(14 BYTE)        NOT NULL,
  BUSINESSCODE         VARCHAR2(60 BYTE)        NOT NULL,
  BUSINESSTYPE         VARCHAR2(4 BYTE)         NOT NULL,
  LOANTRADEID          VARCHAR2(46 BYTE)        NOT NULL,
  CHECKFINALDATE       DATE,
  DATAOCCURDATE        DATE,
  DATAOCCURAMOUNT      NUMBER,
  ENCLOSUREFLAG        VARCHAR2(1 BYTE),
  ENCLOSURENO          VARCHAR2(20 BYTE),
  CHECKRESULT          VARCHAR2(1 BYTE),
  CHECKRESULTDESC      CLOB,
  CORRECTRESULT        VARCHAR2(1 BYTE),
  ENCLOSUREINFNO       VARCHAR2(20 BYTE),
  CORRECTDESC          CLOB,
  STATUS               VARCHAR2(1 BYTE)         NOT NULL,
  SENDFLAG             VARCHAR2(1 BYTE)         NOT NULL,
  CHECKER              NVARCHAR2(20),
  CHECKTIME            DATE,
  CORRECTOR            VARCHAR2(20 BYTE),
  CORRECTTIME          DATE,
  RECVTIME             DATE                     NOT NULL,
  CORRECTACCEPTFLAG    VARCHAR2(1 BYTE),
  CORRECTOPINION       CLOB,
  CLIENT_TYPE          VARCHAR2(100 BYTE)
);

COMMENT ON TABLE PC_DISSENTINFO IS '业务表_异议管理信息表';

COMMENT ON COLUMN PC_DISSENTINFO.DISSENTTYPE IS '异议类别';

COMMENT ON COLUMN PC_DISSENTINFO.OBJCHECKID IS '异议事项号 ';

COMMENT ON COLUMN PC_DISSENTINFO.OBJCHECKNUM IS '异议事项流水号 ';

COMMENT ON COLUMN PC_DISSENTINFO.CHECKBEGINDATE IS '核查开始日期 ';

COMMENT ON COLUMN PC_DISSENTINFO.CUSTNAME IS '客户名称';

COMMENT ON COLUMN PC_DISSENTINFO.IDTYPE IS '证件类型';

COMMENT ON COLUMN PC_DISSENTINFO.IDCODE IS '证件号码';

COMMENT ON COLUMN PC_DISSENTINFO.PHONENUM IS '有效联系电话 ';

COMMENT ON COLUMN PC_DISSENTINFO.OBJITEMINF IS '异议事项信息,存放BASE64内容文件的文件名';

COMMENT ON COLUMN PC_DISSENTINFO.OBJITEMDESC IS '异议说明 ';

COMMENT ON COLUMN PC_DISSENTINFO.DATAPROVIDERORGCODE IS '数据提供机构代码';

COMMENT ON COLUMN PC_DISSENTINFO.DATAOCCURORGCODE IS '数据发生机构代码';

COMMENT ON COLUMN PC_DISSENTINFO.BUSINESSCODE IS '业务标识号 ';

COMMENT ON COLUMN PC_DISSENTINFO.BUSINESSTYPE IS '业务种类 ';

COMMENT ON COLUMN PC_DISSENTINFO.LOANTRADEID IS '报送贷款业务号，截取BusinessCode字段的后46位';

COMMENT ON COLUMN PC_DISSENTINFO.CHECKFINALDATE IS '核查到期日期 ';

COMMENT ON COLUMN PC_DISSENTINFO.DATAOCCURDATE IS '数据发生日期 ';

COMMENT ON COLUMN PC_DISSENTINFO.DATAOCCURAMOUNT IS '数据发生金额 ';

COMMENT ON COLUMN PC_DISSENTINFO.ENCLOSUREFLAG IS '是否存在附件 ';

COMMENT ON COLUMN PC_DISSENTINFO.ENCLOSURENO IS '异议附件编号';

COMMENT ON COLUMN PC_DISSENTINFO.CHECKRESULT IS '核查结果,1--数据有误,2--数据无误,3--数据遗漏,4--数据删除,5--数据删除（欺诈）';

COMMENT ON COLUMN PC_DISSENTINFO.CHECKRESULTDESC IS '异议核查结果描述';

COMMENT ON COLUMN PC_DISSENTINFO.CORRECTRESULT IS '异议更正结果,1--已更正,2--无需更正';

COMMENT ON COLUMN PC_DISSENTINFO.ENCLOSUREINFNO IS '异议更正附件编号';

COMMENT ON COLUMN PC_DISSENTINFO.CORRECTDESC IS '异议更正结果描述';

COMMENT ON COLUMN PC_DISSENTINFO.STATUS IS '状态,0--未处理,1--已核查,2--已更正';

COMMENT ON COLUMN PC_DISSENTINFO.SENDFLAG IS '上报标志,0--未上报,1--已上报';

COMMENT ON COLUMN PC_DISSENTINFO.CHECKER IS '核查操作人OA';

COMMENT ON COLUMN PC_DISSENTINFO.CHECKTIME IS '核查操作时间';

COMMENT ON COLUMN PC_DISSENTINFO.CORRECTOR IS '更正操作人OA';

COMMENT ON COLUMN PC_DISSENTINFO.CORRECTTIME IS '更正操作时间';

COMMENT ON COLUMN PC_DISSENTINFO.RECVTIME IS '接收时间';

COMMENT ON COLUMN PC_DISSENTINFO.CORRECTACCEPTFLAG IS '是否接受更正结果,Y-是,N-否;';

COMMENT ON COLUMN PC_DISSENTINFO.CORRECTOPINION IS '更正处理意见';

COMMENT ON COLUMN PC_DISSENTINFO.CLIENT_TYPE IS '客户类型';
