DROP TABLE PECR_TEXT_MSG_INFORM CASCADE CONSTRAINTS;

CREATE TABLE PECR_TEXT_MSG_INFORM
(
  REPORT_MESSAGE_NAME  NVARCHAR2(50),
  SETT_DATE            NVARCHAR2(10),
  ACCT_CODE            NVARCHAR2(50),
  ID_TYPE              NVARCHAR2(5),
  ID_NUM               NVARCHAR2(20),
  NAME                 NVARCHAR2(30),
  CELL_PHONE           NVARCHAR2(20),
  OVERD_PRD            NUMBER,
  TOT_OVERD            NUMBER,
  SEND_FEEDBACK_STATE  NVARCHAR2(2),
  INFORM_TIME          NVARCHAR2(20),
  GLOBAL_SERIAL_NO     NVARCHAR2(31),
  SEND_TEXT            NVARCHAR2(300)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PECR_TEXT_MSG_INFORM IS '短信通知信息表';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.REPORT_MESSAGE_NAME IS '上报报文名';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.SETT_DATE IS '结算/应还款日';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.ACCT_CODE IS '账户标识码';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.ID_TYPE IS '证件类型';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.ID_NUM IS '证件号码';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.NAME IS '客户姓名';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.CELL_PHONE IS '客户手机号码';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.OVERD_PRD IS '当前逾期期数';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.TOT_OVERD IS '当前逾期总额';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.SEND_FEEDBACK_STATE IS '短信发送状态,S：反馈成功;F：反馈失败;U:  反馈未知;P:  反馈处理中;N: 请求失败;X: 解析响应失败';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.INFORM_TIME IS '短信通知时间';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.GLOBAL_SERIAL_NO IS '全局流水号';

COMMENT ON COLUMN PECR_TEXT_MSG_INFORM.SEND_TEXT IS '短信文本';
