DROP TABLE REPORT_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE REPORT_MESSAGE
(
  REPORT_MESSAGE_ID              NVARCHAR2(60)  NOT NULL,
  REPORT_MESSAGE_FILE_NAME       NVARCHAR2(34),
  REPORT_MESSAGE_TYPE            NVARCHAR2(10),
  REPORT_MESSAGE_STATUS          NVARCHAR2(50),
  TXT_REPORT_MESSAGE_FILE_PATH   NVARCHAR2(2000),
  ZIP_REPORT_MESSAGE_FILE_PATH   NVARCHAR2(2000),
  ENC_REPORT_MESSAGE_FILE_PATH   NVARCHAR2(2000),
  ABNORM_REPORTMESSAGE_FILEPATH  NVARCHAR2(2000),
  RECORD_NUM                     NUMBER,
  CREATE_TIME                    NVARCHAR2(10),
  CREATE_SUCCESS_TIME            NVARCHAR2(10),
  REPORT_TIME                    NVARCHAR2(10),
  OPERATOR_USER                  NVARCHAR2(50),
  ORG_CODE                       NVARCHAR2(100),
  DESCRIPTION                    NVARCHAR2(2000),
  FEEDBACK_MESSAGE_FILE_NAME     NCHAR(34),
  FEEDBACK_MESSAGE_CREATE_TIME   NVARCHAR2(10),
  FEEDBACK_MESSAGE_REC_TIME      NVARCHAR2(10),
  FEEDBACK_MESSAGE_IDENTIFY      NCHAR(1),
  FEEDBACK_MESSAGE_FILE_PATH     NVARCHAR2(2000),
  FK_SUCCESS_NUMBER              NUMBER,
  FK_FAIL_NUMBER                 NUMBER
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE REPORT_MESSAGE IS '报文记录表';

COMMENT ON COLUMN REPORT_MESSAGE.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN REPORT_MESSAGE.REPORT_MESSAGE_FILE_NAME IS '报送报文文件名';

COMMENT ON COLUMN REPORT_MESSAGE.REPORT_MESSAGE_TYPE IS '报送报文类型';

COMMENT ON COLUMN REPORT_MESSAGE.REPORT_MESSAGE_STATUS IS '报文状态:10-报文已生成;20-已报送;30-报送成功;40-反馈全出错;41-反馈全成功;50-反馈部分出错;60-预处理成功;70-预处理全失败;80-预处理部分失败';

COMMENT ON COLUMN REPORT_MESSAGE.TXT_REPORT_MESSAGE_FILE_PATH IS 'TXT报文存储路径';

COMMENT ON COLUMN REPORT_MESSAGE.ZIP_REPORT_MESSAGE_FILE_PATH IS 'ZIP报文存储路径';

COMMENT ON COLUMN REPORT_MESSAGE.ENC_REPORT_MESSAGE_FILE_PATH IS 'ENC报文存储路径';

COMMENT ON COLUMN REPORT_MESSAGE.ABNORM_REPORTMESSAGE_FILEPATH IS '异常报文存储路径';

COMMENT ON COLUMN REPORT_MESSAGE.RECORD_NUM IS '报文记录数';

COMMENT ON COLUMN REPORT_MESSAGE.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN REPORT_MESSAGE.CREATE_SUCCESS_TIME IS '创建完成时间';

COMMENT ON COLUMN REPORT_MESSAGE.REPORT_TIME IS '报送时间';

COMMENT ON COLUMN REPORT_MESSAGE.OPERATOR_USER IS '操作人员';

COMMENT ON COLUMN REPORT_MESSAGE.ORG_CODE IS '所属机构';

COMMENT ON COLUMN REPORT_MESSAGE.DESCRIPTION IS '描述信息';

COMMENT ON COLUMN REPORT_MESSAGE.FEEDBACK_MESSAGE_FILE_NAME IS '反馈报文文件名';

COMMENT ON COLUMN REPORT_MESSAGE.FEEDBACK_MESSAGE_CREATE_TIME IS '反馈报文生成时间';

COMMENT ON COLUMN REPORT_MESSAGE.FEEDBACK_MESSAGE_REC_TIME IS '反馈报文接收时间';

COMMENT ON COLUMN REPORT_MESSAGE.FEEDBACK_MESSAGE_IDENTIFY IS '反馈报文标识';

COMMENT ON COLUMN REPORT_MESSAGE.FEEDBACK_MESSAGE_FILE_PATH IS '反馈报文路径';

COMMENT ON COLUMN REPORT_MESSAGE.FK_SUCCESS_NUMBER IS '入库成功数量';

COMMENT ON COLUMN REPORT_MESSAGE.FK_FAIL_NUMBER IS '入库失败数量';
