DROP TABLE RM_OPERATION_RECORD CASCADE CONSTRAINTS;

CREATE TABLE RM_OPERATION_RECORD
(
  REPORT_MESSAGE_TYPE  NVARCHAR2(10),
  REPORT_MESSAGE_ID    NVARCHAR2(60),
  CREATE_TIME          NVARCHAR2(50),
  OPERATOR_USER        NVARCHAR2(50),
  ORG_CODE             NVARCHAR2(100),
  ORG_NAME             NVARCHAR2(100),
  ACTION               NVARCHAR2(100),
  DESCRIPTION          NVARCHAR2(2000)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RM_OPERATION_RECORD IS '操作记录表';

COMMENT ON COLUMN RM_OPERATION_RECORD.REPORT_MESSAGE_TYPE IS '信息记录类型';

COMMENT ON COLUMN RM_OPERATION_RECORD.REPORT_MESSAGE_ID IS '报文文件ID';

COMMENT ON COLUMN RM_OPERATION_RECORD.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN RM_OPERATION_RECORD.OPERATOR_USER IS '操作用户';

COMMENT ON COLUMN RM_OPERATION_RECORD.ORG_CODE IS '操作用户所在机构';

COMMENT ON COLUMN RM_OPERATION_RECORD.ORG_NAME IS '操作用户所在机构名称';

COMMENT ON COLUMN RM_OPERATION_RECORD.ACTION IS '动作(提交，审核，驳回……)';

COMMENT ON COLUMN RM_OPERATION_RECORD.DESCRIPTION IS '描述';
