DROP TABLE SERIAL_NUMBER_TABLE CASCADE CONSTRAINTS;

CREATE TABLE SERIAL_NUMBER_TABLE
(
  ID             NVARCHAR2(20),
  SERIAL_NUMBER  NVARCHAR2(3),
  INF_REC_TYPE	 NVARCHAR2(3),
  EXTRACT_DATE	 NVARCHAR2(8)
);

COMMENT ON TABLE SERIAL_NUMBER_TABLE IS '报文获取流水记录表';

COMMENT ON COLUMN SERIAL_NUMBER_TABLE.ID IS '主键';

COMMENT ON COLUMN SERIAL_NUMBER_TABLE.SERIAL_NUMBER IS '流水号';

COMMENT ON COLUMN SERIAL_NUMBER_TABLE.INF_REC_TYPE IS '信息记录类型';

COMMENT ON COLUMN SERIAL_NUMBER_TABLE.EXTRACT_DATE IS '当前流水号日期';