DROP TABLE SMS_RECORD CASCADE CONSTRAINTS;

CREATE TABLE SMS_RECORD
(
  RECORD_ID    NVARCHAR2(36)                    NOT NULL,
  MOBILE       NVARCHAR2(15)                    NOT NULL,
  SMS_CONTENT  NVARCHAR2(255)                   NOT NULL,
  CREATE_DATE  NVARCHAR2(10)                    NOT NULL,
  STATUS       NVARCHAR2(10)                    NOT NULL,
  DESCRIPTION  NVARCHAR2(255),
  SMS_CODE     NVARCHAR2(10)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SMS_RECORD.MOBILE IS '手机号';

COMMENT ON COLUMN SMS_RECORD.SMS_CONTENT IS '短信内容';

COMMENT ON COLUMN SMS_RECORD.CREATE_DATE IS '发送时间';

COMMENT ON COLUMN SMS_RECORD.STATUS IS '状态(成功或者失败)';

COMMENT ON COLUMN SMS_RECORD.DESCRIPTION IS '描述信息，失败的描述';

COMMENT ON COLUMN SMS_RECORD.SMS_CODE IS '短信验证码';
