DROP TABLE SYS_ORG_TYPE CASCADE CONSTRAINTS;

CREATE TABLE SYS_ORG_TYPE
(
  ORG_TYPE_ID    NVARCHAR2(36)                  NOT NULL,
  ORG_TYPE_NAME  NVARCHAR2(100)                 NOT NULL,
  ORG_TYPE_CODE  NVARCHAR2(100)                 NOT NULL
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SYS_ORG_TYPE IS '组织机构类型';

COMMENT ON COLUMN SYS_ORG_TYPE.ORG_TYPE_ID IS '类型ID';

COMMENT ON COLUMN SYS_ORG_TYPE.ORG_TYPE_NAME IS '类型名称';

COMMENT ON COLUMN SYS_ORG_TYPE.ORG_TYPE_CODE IS '类型编码';
