DROP TABLE SYSTEM_STATE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_STATE_TYPE
(
  SYSTEM_STATE_TYPE_ID    NCHAR(32)             NOT NULL,
  SYSTEM_STATE_TYPE       NVARCHAR2(50),
  SYSTEM_STATE_TYPE_NAME  NVARCHAR2(200)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SYSTEM_STATE_TYPE IS '系统状态类型表';

COMMENT ON COLUMN SYSTEM_STATE_TYPE.SYSTEM_STATE_TYPE_ID IS '主键';

COMMENT ON COLUMN SYSTEM_STATE_TYPE.SYSTEM_STATE_TYPE IS '系统状态类型';

COMMENT ON COLUMN SYSTEM_STATE_TYPE.SYSTEM_STATE_TYPE_NAME IS '系统状态类型名称';
