DROP TABLE SYSTEM_STATE_VALUE CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_STATE_VALUE
(
  SYSTEM_STATE_VALUE_ID  NCHAR(32)              NOT NULL,
  SYSTEM_STATE_TYPE_ID   NCHAR(32),
  SYSTEM_STATE_VALUE     NVARCHAR2(50),
  SYSTEM_STATE_NAME      NVARCHAR2(200),
  SEQ                    NUMBER
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SYSTEM_STATE_VALUE IS '系统状态码值表';

COMMENT ON COLUMN SYSTEM_STATE_VALUE.SYSTEM_STATE_VALUE_ID IS '主键';

COMMENT ON COLUMN SYSTEM_STATE_VALUE.SYSTEM_STATE_TYPE_ID IS '外键';

COMMENT ON COLUMN SYSTEM_STATE_VALUE.SYSTEM_STATE_VALUE IS '系统状态码值';

COMMENT ON COLUMN SYSTEM_STATE_VALUE.SYSTEM_STATE_NAME IS '系统状态码值名称';

COMMENT ON COLUMN SYSTEM_STATE_VALUE.SEQ IS '系统状态码值序号';
