DROP TABLE SYSTEM_CODE_VALUE CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_CODE_VALUE
(
  SYSTEM_CODE_VALUE_ID  NCHAR(32),
  SYSTEM_CODE_TYPE_ID   NCHAR(32),
  SYSTEM_CODE           NVARCHAR2(50),
  SYSTEM_CODE_NAME      NVARCHAR2(200),
  SEQ                   NUMBER,
  UPER_ID               NCHAR(32)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SYSTEM_CODE_VALUE IS '系统代码码值表';

COMMENT ON COLUMN SYSTEM_CODE_VALUE.SYSTEM_CODE_VALUE_ID IS '主键';

COMMENT ON COLUMN SYSTEM_CODE_VALUE.SYSTEM_CODE_TYPE_ID IS '外键';

COMMENT ON COLUMN SYSTEM_CODE_VALUE.SYSTEM_CODE IS '系统代码';

COMMENT ON COLUMN SYSTEM_CODE_VALUE.SYSTEM_CODE_NAME IS '系统代码名称';

COMMENT ON COLUMN SYSTEM_CODE_VALUE.SEQ IS '系统代码序号';

COMMENT ON COLUMN SYSTEM_CODE_VALUE.UPER_ID IS '上级分类主键';
