ALTER TABLE SYSTEM_CODE_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM_CODE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_CODE_TYPE
(
  SYSTEM_CODE_TYPE_ID    NVARCHAR2(32)          NOT NULL,
  SYSTEM_CODE_TYPE       NVARCHAR2(50)          DEFAULT NULL,
  SYSTEM_CODE_TYPE_NAME  NVARCHAR2(200)         DEFAULT NULL
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SYSTEM_CODE_TYPE IS '系统常量类型表';

COMMENT ON COLUMN SYSTEM_CODE_TYPE.SYSTEM_CODE_TYPE_ID IS '主键';

COMMENT ON COLUMN SYSTEM_CODE_TYPE.SYSTEM_CODE_TYPE IS '系统代码类型';

COMMENT ON COLUMN SYSTEM_CODE_TYPE.SYSTEM_CODE_TYPE_NAME IS '系统代码类型名称';



CREATE UNIQUE INDEX SYSTEM_CODE_TYPE_PK ON SYSTEM_CODE_TYPE
(SYSTEM_CODE_TYPE_ID)
NOPARALLEL;


ALTER TABLE SYSTEM_CODE_TYPE ADD (
  CONSTRAINT SYSTEM_CODE_TYPE_PK
  PRIMARY KEY
  (SYSTEM_CODE_TYPE_ID)
  USING INDEX SYSTEM_CODE_TYPE_PK
  ENABLE VALIDATE);
