DROP TABLE SYSTEM_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM_CONFIG
(
  SYSTEM_CONFIG_ID     NVARCHAR2(36)            NOT NULL,
  SYSTEM_CONFIG_NAME   NVARCHAR2(100)           NOT NULL,
  SYSTEM_CONFIG_VALUE  NVARCHAR2(100)           NOT NULL,
  DESCRIPTION          NVARCHAR2(255),
  UPDATE_TIME          NVARCHAR2(10),
  UPDATE_USER_NAME     NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SYSTEM_CONFIG.SYSTEM_CONFIG_ID IS '系统配置id';

COMMENT ON COLUMN SYSTEM_CONFIG.SYSTEM_CONFIG_NAME IS '系统配置key';

COMMENT ON COLUMN SYSTEM_CONFIG.SYSTEM_CONFIG_VALUE IS '系统配置value';

COMMENT ON COLUMN SYSTEM_CONFIG.DESCRIPTION IS '描述信息';

COMMENT ON COLUMN SYSTEM_CONFIG.UPDATE_TIME IS '更新日期';

COMMENT ON COLUMN SYSTEM_CONFIG.UPDATE_USER_NAME IS '更新人名称';
