DROP TABLE TABLE_EXAMPLE CASCADE CONSTRAINTS;

CREATE TABLE TABLE_EXAMPLE
(
  USERID    NVARCHAR2(100),
  USERNAME  NVARCHAR2(100),
  SEX       NVARCHAR2(100),
  EMAIL     NVARCHAR2(100),
  ADDRESS   NVARCHAR2(100),
  BIRTHDAY  NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE TABLE_EXAMPLE IS '≤‚ ‘';
