DROP TABLE TASK_LOCKS CASCADE CONSTRAINTS;

CREATE TABLE TASK_LOCKS
(
  TASK_ID      NVARCHAR2(36)                    NOT NULL,
  CREATE_TIME  NVARCHAR2(10),
  EXPIRE_TIME  NVARCHAR2(10)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TASK_LOCKS.CREATE_TIME IS '锁创建时间';

COMMENT ON COLUMN TASK_LOCKS.EXPIRE_TIME IS '锁过期时间';
