DROP TABLE TASK_LOG CASCADE CONSTRAINTS;

CREATE TABLE TASK_LOG
(
  ID             NVARCHAR2(36)                  NOT NULL,
  TASK_ID        NVARCHAR2(36)                  NOT NULL,
  TASK_NAME      NVARCHAR2(255)                 NOT NULL,
  START_TIME     NVARCHAR2(10),
  END_TIME       NVARCHAR2(10),
  EXCUTE_RESULT  NVARCHAR2(10),
  RUN_MODE       NVARCHAR2(10),
  RUN_LOG_PATH   NVARCHAR2(2000),
  EXTERNAL_CODE  NVARCHAR2(50)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE TASK_LOG IS '任务记录表';

COMMENT ON COLUMN TASK_LOG.ID IS '主键';

COMMENT ON COLUMN TASK_LOG.TASK_ID IS '任务编号';

COMMENT ON COLUMN TASK_LOG.TASK_NAME IS '任务名称';

COMMENT ON COLUMN TASK_LOG.START_TIME IS '开始时间';

COMMENT ON COLUMN TASK_LOG.END_TIME IS '结束时间';

COMMENT ON COLUMN TASK_LOG.EXCUTE_RESULT IS '执行结果';

COMMENT ON COLUMN TASK_LOG.RUN_MODE IS '运行方式';

COMMENT ON COLUMN TASK_LOG.RUN_LOG_PATH IS '日志文件路径';

COMMENT ON COLUMN TASK_LOG.EXTERNAL_CODE IS '外部编号';
