DROP TABLE TASK_MANAGEMENT CASCADE CONSTRAINTS;

CREATE TABLE TASK_MANAGEMENT
(
  ID                NVARCHAR2(36)               NOT NULL,
  TASK_ID           NVARCHAR2(36),
  TASK_NAME         NVARCHAR2(255),
  TASK_EXCUTE_PLAN  NVARCHAR2(255),
  EXCUTE_TARGET     NVARCHAR2(255),
  TASK_STATUS       NVARCHAR2(10),
  TASK_TYPE         NVARCHAR2(50),
  EXTERNAL_CODE     NVARCHAR2(50),
  TIMEOUT_SECOND    NUMBER,
  REPOSITORY_ID     NVARCHAR2(36),
  EXCUTE_RESULT     NVARCHAR2(10)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE TASK_MANAGEMENT IS '任务管理表';

COMMENT ON COLUMN TASK_MANAGEMENT.TASK_ID IS '任务编号';

COMMENT ON COLUMN TASK_MANAGEMENT.TASK_NAME IS '任务名称';

COMMENT ON COLUMN TASK_MANAGEMENT.TASK_EXCUTE_PLAN IS '任务执行计划';

COMMENT ON COLUMN TASK_MANAGEMENT.EXCUTE_TARGET IS '执行目标';

COMMENT ON COLUMN TASK_MANAGEMENT.EXTERNAL_CODE IS '外部编号';

COMMENT ON COLUMN TASK_MANAGEMENT.TIMEOUT_SECOND IS '超时时间(秒)';

COMMENT ON COLUMN TASK_MANAGEMENT.REPOSITORY_ID IS '资源库ID';

COMMENT ON COLUMN TASK_MANAGEMENT.EXCUTE_RESULT IS '执行结果 0成功1失败2运行中';
