DROP TABLE USER_PWD_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE USER_PWD_HISTORY
(
  USER_PWD_HISTORY_ID  NVARCHAR2(36)            NOT NULL,
  USER_ID              NVARCHAR2(36)            NOT NULL,
  PWD                  NVARCHAR2(100)           NOT NULL,
  CREATE_TIME          NVARCHAR2(10)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE USER_PWD_HISTORY IS '用户密码历史表';

COMMENT ON COLUMN USER_PWD_HISTORY.PWD IS '密码';

COMMENT ON COLUMN USER_PWD_HISTORY.CREATE_TIME IS '每次修改都需要插入，修改时间';
