DROP TABLE VALIDATE_ERROR_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_ERROR_MESSAGE
(
  ID                 NVARCHAR2(50)              NOT NULL,
  TABLE_PK           NVARCHAR2(255),
  TABLE_NAME         NVARCHAR2(255),
  TABLE_FIELD        NVARCHAR2(255),
  ERROR_MSG          NVARCHAR2(2000),
  CUR_DATE           NVARCHAR2(50),
  VALIDATE_RULES_ID  NVARCHAR2(36),
  V_COMMENT          NVARCHAR2(255),
  BUSINESS_PK        NVARCHAR2(255),
  TABLE_NAME_CN      NVARCHAR2(100),
  SUBJECT            NVARCHAR2(100),
  IS_FORCE           NVARCHAR2(10),
  IS_MULTI_TABLE     NVARCHAR2(10),
  MASTER_TABLE_ID    NVARCHAR2(32)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_ERROR_MESSAGE IS '错误信息表';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.ID IS '主键';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.TABLE_NAME IS '表名称';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.TABLE_FIELD IS '表字段';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.ERROR_MSG IS '错误信息';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.CUR_DATE IS '日期';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.VALIDATE_RULES_ID IS '校验规则id';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.V_COMMENT IS '描述';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.BUSINESS_PK IS '业务联合主键';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.TABLE_NAME_CN IS '业务表中文名';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.SUBJECT IS '主题';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.IS_FORCE IS '是否强制性校验';

COMMENT ON COLUMN VALIDATE_ERROR_MESSAGE.IS_MULTI_TABLE IS '是否是多表';
