DROP TABLE VALIDATE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_MAPPING
(
  ID                        NVARCHAR2(36)       NOT NULL,
  VALIDATE_RULES_ID         NVARCHAR2(36),
  VALIDATE_PARAMETER_NAME   NVARCHAR2(100),
  TEMPLATE_MAPPING_NAME     NVARCHAR2(100),
  VALIDATE_MAPPING_COMMENT  NVARCHAR2(255),
  VALIDATE_MAPPING_TYPE     NVARCHAR2(50),
  SEQ                       NUMBER
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_MAPPING IS '校验映射表';

COMMENT ON COLUMN VALIDATE_MAPPING.ID IS '主键id';

COMMENT ON COLUMN VALIDATE_MAPPING.VALIDATE_RULES_ID IS '校验规则id';

COMMENT ON COLUMN VALIDATE_MAPPING.VALIDATE_PARAMETER_NAME IS '校验参数名称';

COMMENT ON COLUMN VALIDATE_MAPPING.TEMPLATE_MAPPING_NAME IS '检验映射名称';

COMMENT ON COLUMN VALIDATE_MAPPING.VALIDATE_MAPPING_COMMENT IS '描述';

COMMENT ON COLUMN VALIDATE_MAPPING.VALIDATE_MAPPING_TYPE IS '类型';

COMMENT ON COLUMN VALIDATE_MAPPING.SEQ IS '排序';
