DROP TABLE VALIDATE_RULES_MANAGEMENT CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_RULES_MANAGEMENT
(
  ERRNO            NVARCHAR2(8)                 NOT NULL,
  BUSINESSTYPE     NVARCHAR2(2)                 NOT NULL,
  ERRDESCRIBE      NVARCHAR2(600),
  VALIDTYPE        NVARCHAR2(10),
  VALIDEXPRESSION  NVARCHAR2(2000),
  ISINUSE          NVARCHAR2(2),
  CHECKTANLENAME   NVARCHAR2(50),
  CHECKCOLNAME     NVARCHAR2(50),
  CHTABLENAME      NVARCHAR2(100),
  INTERNALKEY      NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_RULES_MANAGEMENT IS '校验规则表';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.ERRNO IS '规则编号';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.BUSINESSTYPE IS '规则所属模块 0-个人  1-企业';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.ERRDESCRIBE IS '规则描述';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.VALIDTYPE IS '校验方式（sql数据库规则，viewPage前台规则）';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.VALIDEXPRESSION IS '校验表达式sql';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.ISINUSE IS '是否启用';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.CHECKTANLENAME IS '校验表名（英文）';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.CHECKCOLNAME IS '校验字段列';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.CHTABLENAME IS '校验表名（中文）';

COMMENT ON COLUMN VALIDATE_RULES_MANAGEMENT.INTERNALKEY IS '校验对应字段';
