DROP TABLE VALIDATE_DB_TYPE CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_DB_TYPE
(
  DB_NAME     NVARCHAR2(50)                     NOT NULL,
  IS_CURRENT  NCHAR(1)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_DB_TYPE IS '数据库类型表';

COMMENT ON COLUMN VALIDATE_DB_TYPE.DB_NAME IS '数据库名称';

COMMENT ON COLUMN VALIDATE_DB_TYPE.IS_CURRENT IS 'Y当前系统正在使用N表示不是';
