DROP TABLE VALIDATE_RULES CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_RULES
(
  ID              NVARCHAR2(36)                 NOT NULL,
  RULE_NAME       NVARCHAR2(20),
  RULE_TYPE       NVARCHAR2(10),
  TABLE_NAME      NVARCHAR2(50),
  TABLE_FIELD     NVARCHAR2(255),
  TEMPLATE_NAME   NVARCHAR2(50),
  RULE_COMMENT    NVARCHAR2(255),
  SUBJECT         NVARCHAR2(30),
  IS_FORCE        NVARCHAR2(5),
  IS_MULTI_TABLE  NVARCHAR2(2),
  TABLE_PK        NVARCHAR2(50)                 NOT NULL,
  ACTION          NVARCHAR2(100),
  SEQ             NUMBER
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_RULES IS '校验规则表';

COMMENT ON COLUMN VALIDATE_RULES.ID IS '唯一ID';

COMMENT ON COLUMN VALIDATE_RULES.RULE_NAME IS '规则名称';

COMMENT ON COLUMN VALIDATE_RULES.RULE_TYPE IS '规则类型（sql数据库规则，viewPage前台规则）';

COMMENT ON COLUMN VALIDATE_RULES.TABLE_NAME IS '表名';

COMMENT ON COLUMN VALIDATE_RULES.TABLE_FIELD IS '字段';

COMMENT ON COLUMN VALIDATE_RULES.TEMPLATE_NAME IS '模板名称';

COMMENT ON COLUMN VALIDATE_RULES.RULE_COMMENT IS '描述备注';

COMMENT ON COLUMN VALIDATE_RULES.SUBJECT IS '主题';

COMMENT ON COLUMN VALIDATE_RULES.IS_FORCE IS '是否强制校验(Y/必须通过，N可以忽略)';

COMMENT ON COLUMN VALIDATE_RULES.IS_MULTI_TABLE IS '是否多表校验(Y/是，N不是)';

COMMENT ON COLUMN VALIDATE_RULES.TABLE_PK IS '表主键';

COMMENT ON COLUMN VALIDATE_RULES.ACTION IS '动作标识一般为新增修改';

COMMENT ON COLUMN VALIDATE_RULES.SEQ IS '排序';
