DROP TABLE VALIDATE_FIELD CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_FIELD
(
  FIELD_ID       NVARCHAR2(36)                  NOT NULL,
  TABLE_ID       NVARCHAR2(36),
  FIELD_NAME_EN  NVARCHAR2(255),
  FIELD_NAME_CN  NVARCHAR2(255)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_FIELD IS '检验字段表';

COMMENT ON COLUMN VALIDATE_FIELD.FIELD_ID IS '主键id';

COMMENT ON COLUMN VALIDATE_FIELD.TABLE_ID IS '表主键id';

COMMENT ON COLUMN VALIDATE_FIELD.FIELD_NAME_EN IS '字段英文名';

COMMENT ON COLUMN VALIDATE_FIELD.FIELD_NAME_CN IS '字段中文名';
