DROP TABLE VALIDATE_PARAMETER CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_PARAMETER
(
  PARAMETER_NAME     NVARCHAR2(50)              NOT NULL,
  PARAMETER_TYPE     NVARCHAR2(10),
  PARAMETER_VALUE    NVARCHAR2(255),
  PARAMETER_COMMENT  NVARCHAR2(255),
  SERVICE_NAME       NVARCHAR2(50)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_PARAMETER IS '检验参数表';

COMMENT ON COLUMN VALIDATE_PARAMETER.PARAMETER_NAME IS '参数名称';

COMMENT ON COLUMN VALIDATE_PARAMETER.PARAMETER_TYPE IS '参数类型';

COMMENT ON COLUMN VALIDATE_PARAMETER.PARAMETER_VALUE IS '参数的值';

COMMENT ON COLUMN VALIDATE_PARAMETER.PARAMETER_COMMENT IS '参数描述';

COMMENT ON COLUMN VALIDATE_PARAMETER.SERVICE_NAME IS 'service类名';
