DROP TABLE VALIDATE_TABLE CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_TABLE
(
  TABLE_ID         NVARCHAR2(36)                NOT NULL,
  TABLE_NAME_EN    NVARCHAR2(255),
  TABLE_NAME_CN    NVARCHAR2(255),
  MASTER_TABLE_EN  NVARCHAR2(255),
  MASTER_TABLE_PK  NVARCHAR2(255),
  TBALE_PK         NVARCHAR2(100)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_TABLE IS '校验表';

COMMENT ON COLUMN VALIDATE_TABLE.TABLE_ID IS '主键id';

COMMENT ON COLUMN VALIDATE_TABLE.TABLE_NAME_EN IS '表中英文名';

COMMENT ON COLUMN VALIDATE_TABLE.TABLE_NAME_CN IS '表中文名';

COMMENT ON COLUMN VALIDATE_TABLE.MASTER_TABLE_EN IS '对应的主表名称';

COMMENT ON COLUMN VALIDATE_TABLE.MASTER_TABLE_PK IS '主键的主键字段';

COMMENT ON COLUMN VALIDATE_TABLE.TBALE_PK IS '表主键信息';
