DROP TABLE VALIDATE_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE VALIDATE_TEMPLATE
(
  TEMPLATE_NAME     NVARCHAR2(50)               NOT NULL,
  TEMPLATE_TYPE     NVARCHAR2(255),
  TEMPLATE_COMMENT  NVARCHAR2(255),
  ERROR_MSG         NVARCHAR2(2000),
  DATABASE_TYPE     NVARCHAR2(50),
  TEMPLATE_TPL      NVARCHAR2(2000),
  SERVICE_NAME      NVARCHAR2(2000)
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE VALIDATE_TEMPLATE IS '校验模板表';

COMMENT ON COLUMN VALIDATE_TEMPLATE.TEMPLATE_NAME IS '模板名称';

COMMENT ON COLUMN VALIDATE_TEMPLATE.TEMPLATE_TYPE IS '模板类型';

COMMENT ON COLUMN VALIDATE_TEMPLATE.TEMPLATE_COMMENT IS '模板描述';

COMMENT ON COLUMN VALIDATE_TEMPLATE.ERROR_MSG IS '错误信息提示';

COMMENT ON COLUMN VALIDATE_TEMPLATE.DATABASE_TYPE IS '数据库类型 (null表示通用,mysql,oracle,sqlserver,oracle,db2)';

COMMENT ON COLUMN VALIDATE_TEMPLATE.TEMPLATE_TPL IS '模板内容';

COMMENT ON COLUMN VALIDATE_TEMPLATE.SERVICE_NAME IS 'service名称';
