DELETE FROM VALIDATE_TABLE;

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('1', 'E_BS', '企业基本信息', 'E_BS', 'EAA_BS_SGMT_ID', 'EAA_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('10', 'E_CTRCT_INF_ENT_DEL', '企业授信协议信息-整笔删除请求', 'E_CTRCT_INF_ENT_DEL', 'EGZ_EN_CTRCT_INF_ENT_DEL_ID', 'EGZ_EN_CTRCT_INF_ENT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('10000', 'E_INCOME_STATEMENT', '企业利润及利润分配表', 'E_INCOME_STATEMENT', 'EIA_INCOME_STATEMENT_PROFIT_ID', 'EIA_INCOME_STATEMENT_PROFIT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('11', 'MOC_ENT_DEL', '抵（质）押合同整笔删除请求记录', 'MOC_ENT_DEL', 'EFZ_MOC_ENT_DEL_ID', 'EFZ_MOC_ENT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('110', 'I_BS', '个人基本信息', 'I_BS', 'PAA_BS_SGMT_ID', 'PAA_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('111', 'I_ID', '个人基本信息记录其他标识段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAB_ID_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('112', 'I_FCS_INF', '个人基本信息记录基本概况信息段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAC_FCS_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('113', 'I_EDU_INF', '个人基本信息记录教育信息段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAD_EDU_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('114', 'I_OCTPN_INF', '个人基本信息记录职业信息段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAE_OCTPN_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('115', 'I_REDNC_INF', '个人基本信息记录居住地址段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAF_REDNC_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('116', 'I_MLG_INF', '个人基本信息记录通讯地址段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAG_MLG_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('117', 'I_SPS_INF', '个人基本信息记录婚姻信息段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAH_SPS_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('118', 'I_INC_INF', '个人基本信息记录收入信息段', 'I_BS', 'PAA_BS_SGMT_ID', 'PAI_INC_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('12', 'E_BALANCE_SHEET_DLT', '企业财报基础信息-整笔删除类请求', 'E_BALANCE_SHEET_DLT', 'EMZ_BALANCE_SHEET_DLT_ID', 'EMZ_BALANCE_SHEET_DLT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('120', 'I_IN_FAL_MMBS_INF', '家族关系信息记录', 'I_IN_FAL_MMBS_INF', 'PAJ_IN_FAL_MMBS_INF_ID', 'PAJ_IN_FAL_MMBS_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('13', 'E_SEC_ACCT_ID_CAGS_INF', '企业担保账户信息-标识变更', 'E_SEC_ACCT_ID_CAGS_INF', 'EEW_EN_SEC_ACCT_ID_CAGS_INF_ID', 'EEW_EN_SEC_ACCT_ID_CAGS_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('130', 'I_IN_ID_EFCT_INF', '个人证件有效期信息记录', 'I_IN_ID_EFCT_INF', 'PAK_IN_ID_EFCT_INF_ID', 'PAK_IN_ID_EFCT_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('14', 'E_CR_ACCT_ID_CAGS_INF', '企业授信协议信息-标识变更类请求', 'E_CR_ACCT_ID_CAGS_INF', 'EGW_EN_ACCT_INF_ID_CAGS_INF_ID', 'EGW_EN_ACCT_INF_ID_CAGS_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('15', 'MOC_ID_CAGS_INF', '抵（质）押合同标识变更请求记录', 'MOC_ID_CAGS_INF', 'EFW_MOC_ID_CAGS_INF_ID', 'EFW_MOC_ID_CAGS_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('16', 'E_ACCT_BS', '企业借贷信息', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDA_ACCT_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('17', 'E_RLT_REPYMT_INF', '企业借贷-相关还款责任人段', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDC_RLT_REPYMT_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('18', 'E_GUAR_ACCT_BS', '企业担保账户信息', 'E_GUAR_ACCT_BS', 'EEA_GUAR_ACCT_BS_SGMT_ID', 'EEA_GUAR_ACCT_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('19', 'E_SEC_RLT_REPYMT_INF', '企业担保-相关还款责任人段', 'E_GUAR_ACCT_BS', 'EEA_GUAR_ACCT_BS_SGMT_ID', 'EEC_RLT_REPYMT_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('2', 'E_FCS_INF', '基本概况信息', 'E_BS', 'EAA_BS_SGMT_ID', 'EAC_FCS_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('20', 'E_CTRCT_BS', '企业授信协议信息', 'E_CTRCT_BS', 'EGA_CTRCT_BS_SGMT_ID', 'EGA_CTRCT_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('21', 'E_CTRCT_CERT_REL', '企业授信协议信息-共同授信人段', 'E_CTRCT_BS', 'EGA_CTRCT_BS_SGMT_ID', 'EGB_CTRCT_CERT_REL_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('211', 'I_ACCT_BS_INF', '个人借贷账户信息记录基本信息段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBB_ACCT_BS_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('212', 'I_LOAN_RLT_REPYMT_INF', '个人借贷账户信息记录相关还款责任人段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBC_RLT_REPYMT_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('213', 'I_MCC_INF', '个人借贷账户信息记录抵质押物信息段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBD_MCC_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('214', 'I_ACCT_CRED', '个人借贷账户信息记录授信额度信息段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBE_ACCT_CRED_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('215', 'I_OC_INF', '个人借贷账户信息记录初始债权说明段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBF_OC_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('217', 'I_SPEC_PRD', '个人借贷账户信息记录大额专项分期信息段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBH_SPEC_PRD_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('219', 'I_AS_TRST_DSPN', '个人借贷账户信息记录特殊交易说明段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBJ_AS_TRST_DSPN_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('22', 'E_CTRCT_INF_DEL', '企业授信协议按段删除请求记录', 'E_CTRCT_INF_DEL', 'EGY_EN_CTRCT_INF_DEL_ID', 'EGY_EN_CTRCT_INF_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('221', 'I_CTRCT_CERT_REL', '个人授信协议信息记录共同受信人信息段', 'I_CTRCT_BS', 'PCA_CTRCT_BS_SGMT_ID', 'PCB_CTRCT_CERT_REL_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('223', 'I_IN_SPC_EVT_DSC_INF', '个人借贷账户特殊事件说明记录', 'I_IN_SPC_EVT_DSC_INF', 'PBK_IN_SPC_EVT_DSC_INF_ID', 'PBK_IN_SPC_EVT_DSC_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('23', 'E_SEC_ACCT_DEL', '企业担保账户按段删除请求记录', 'E_SEC_ACCT_DEL', 'EEY_EN_SEC_ACCT_DEL_ID', 'EEY_EN_SEC_ACCT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('231', 'I_GUAR_ACCT_INF', '个人担保账户信息记录基本信息段', 'I_GUAR_ACCT_BS', 'PDA_GUAR_ACCT_BS_SGMT_ID', 'PDB_GUAR_ACCT_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('24', 'E_ACCT_INF_DEL', '企业借贷账户按段删除请求记录', 'E_ACCT_INF_DEL', 'EDY_EN_ACCT_INF_DEL_ID', 'EDY_EN_ACCT_INF_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('25', 'E_ICDN_RLTP_INF', '企业间关联关系信息记录', 'E_ICDN_RLTP_INF', 'ECA_EN_ICDN_RLTP_INF_ID', 'ECA_EN_ICDN_RLTP_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('26', 'E_INCOME_EXPENSE_BS', '事业单位收入支出表', 'E_INCOME_EXPENSE_BS', 'ELA_INCOME_AND_EXPENSE_STAT_ID', 'ELA_INCOME_AND_EXPENSE_STAT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('27', 'E_INSTITU_BALANCE_BS', '事业单位资产负债表', 'E_INSTITU_BALANCE_BS', 'EKA_INSTITUTION_BALANCE_SHT_ID', 'EKA_INSTITUTION_BALANCE_SHT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('28', 'E_INCOME_EXPENSE', '事业单位收入支出表事业单位收入支出表段', 'E_INCOME_EXPENSE_BS', 'ELA_INCOME_AND_EXPENSE_STAT_ID', 'ELB_INCOME_AND_EXPENSE_STAT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('29', 'E_INSTITU_BALANCE', '事业单位资产负债表事业单位资产负债表段', 'E_INSTITU_BALANCE_BS', 'EKA_INSTITUTION_BALANCE_SHT_ID', 'EKB_INSTITUTION_BALANCE_SHT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('3', 'E_MN_SHA_HOD_INF', '注册资本及主要出资人信息段', 'E_BS', 'EAA_BS_SGMT_ID', 'EAE_MN_SHA_HOD_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('30', 'E_BALANCE_SHEET02', '企业资产负债表-2002资产负债表段', 'E_BALANCE_SHEET_BS', 'EHA_BALANCE_SHEET_BS_SGMT_ID', 'EHB_BALANCE_SHEET2002_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('31', 'E_BALANCE_SHEET07', '企业资产负债表-2007资产负债表段', 'E_BALANCE_SHEET_BS', 'EHA_BALANCE_SHEET_BS_SGMT_ID', 'EHC_BALANCE_SHEET2007_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('32', 'E_CASH_FLOWS2002', '企业现金流量表-2002现金流量表段', 'E_CASH_FLOWS_BS', 'EJA_CASH_FLOWS_BS_SGMT_ID', 'EJB_CASH_FLOWS2002_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('33', 'E_CASH_FLOWS2007', '企业现金流量表-2007现金流量表段', 'E_CASH_FLOWS_BS', 'EJA_CASH_FLOWS_BS_SGMT_ID', 'EJC_CASH_FLOWS2007_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('34', 'E_CREDIT_LIM', '企业授信协议-额度信息段', 'E_CTRCT_BS', 'EGA_CTRCT_BS_SGMT_ID', 'EGC_CREDIT_LIM_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('35', 'E_ACCT_BS_INF', '企业借贷信息-基本信息段', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDB_ACCT_BS_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('36', 'MOTGA_CLTAL_CTRCT_BS', '抵质押合同', 'MOTGA_CLTAL_CTRCT_BS', 'EFA_MOTGA_CLTAL_CTRCT_BS_ID', 'EFA_MOTGA_CLTAL_CTRCT_BS_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('37', 'MOTGA_CLTAL_BS_INF', '抵（质）押合同信息基本信息段', 'MOTGA_CLTAL_CTRCT_BS', 'EFA_MOTGA_CLTAL_CTRCT_BS_ID', 'EFB_MOTGA_CLTAL_BS_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('38', 'MOTGA_COM_REC_INF', '抵（质）押合同信息其他债务人段', 'MOTGA_CLTAL_CTRCT_BS', 'EFA_MOTGA_CLTAL_CTRCT_BS_ID', 'EFC_COM_REC_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('39', 'E_ORIG_CREDITOR_INF  ', '企业借贷信息-初始债权说明段', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDF_ORIG_CREDITOR_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('4', 'E_ID', '其他标识信息段', 'E_BS', 'EAA_BS_SGMT_ID', 'EAB_ID_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('40', 'E_ACCT_CRED', '企业借贷信息-授信额度信息段', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDE_ACCT_CRED_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('41', 'E_MOTGA_CLTAL_CTRCT_INF', '企业借贷信息-抵质押物段', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDD_MOTGA_CLTAL_CTRCT_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('43', 'I_IN_ACCT_ENT_DEL', '个人借贷账户整笔删除', 'I_IN_ACCT_ENT_DEL', 'PBZ_IN_ACCT_ENT_DEL_ID', 'PBZ_IN_ACCT_ENT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('44', 'I_IN_CTRCT_ENT_DEL', '个人授信协议整笔删除', 'I_IN_CTRCT_ENT_DEL', 'PCZ_IN_CTRCT_ENT_DEL_ID', 'PCZ_IN_CTRCT_ENT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('45', 'I_IN_SEC_ACCT_ENT_DEL', '个人担保账户整笔删除', 'I_IN_SEC_ACCT_ENT_DEL', 'PDZ_IN_SEC_ACCT_ENT_DEL_ID', 'PDZ_IN_SEC_ACCT_ENT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('46', 'I_IN_ACCT_ID_CAGS_INF', '个人借贷账户标识变更', 'I_IN_ACCT_ID_CAGS_INF', 'PBW_IN_ACCT_ID_CAGS_INF_ID', 'PBW_IN_ACCT_ID_CAGS_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('47', 'I_IN_CTRCTID_CAGS_INF', '个人授信协议标识变更', 'I_IN_CTRCTID_CAGS_INF', 'PCW_IN_CTRCTID_CAGS_INF_ID', 'PCW_IN_CTRCTID_CAGS_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('48', 'I_INSECACCTID_CAGSINF', '个人担保账户标识变更', 'I_INSECACCTID_CAGSINF', 'PDW_INSECACCTID_CAGSINF_ID', 'PDW_INSECACCTID_CAGSINF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('49', 'I_IN_BS_INF_DLT', '个人基本信息整笔删除请求记录', 'I_IN_BS_INF_DLT', 'PAY_IN_BS_INF_DLT_ID', 'PAY_IN_BS_INF_DLT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('5', 'E_MN_MMB_INF', '主要组成人员信息段', 'E_BS', 'EAA_BS_SGMT_ID', 'EAD_MN_MMB_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('50', 'I_IN_ID_EFCT_INF_DLT', '人证件有效期信息整笔删除请求记录', 'I_IN_ID_EFCT_INF_DLT', 'PAZ_IN_ID_EFCT_INF_DLT_ID', 'PAZ_IN_ID_EFCT_INF_DLT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('51', 'I_IN_CTRCT_DEL', '个人授信协议按段删除', 'I_IN_CTRCT_DEL', 'PCY_IN_CTRCT_DEL_ID', 'PCY_IN_CTRCT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('52', 'I_IN_SEC_ACCT_DEL', '个人担保账户按段删除', 'I_IN_SEC_ACCT_DEL', 'PDY_IN_SEC_ACCT_DEL_ID', 'PDY_IN_SEC_ACCT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('53', 'I_IN_ACCT_DEL', '个人借贷账户按段删除', 'I_IN_ACCT_DEL', 'PBY_IN_ACCT_DEL_ID', 'PBY_IN_ACCT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('6', 'E_BS_INF_DLT', '企业基本信息整笔删除请求记录', 'E_BS_INF_DLT', 'EAZ_EN_BS_INF_DLT_ID', 'EAZ_EN_BS_INF_DLT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('7', 'E_ACCT_INF_ENT_DEL', '企业借贷账户整笔删除请求记录', 'E_ACCT_INF_ENT_DEL', 'EDZ_EN_ACCT_INF_ENT_DEL_ID', 'EDZ_EN_ACCT_INF_ENT_DEL_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('702', 'E_GUAR_ACCT_BS_INF', '企业担保账户基本信息段', 'E_GUAR_ACCT_BS', 'EEA_GUAR_ACCT_BS_SGMT_ID', 'EEB_GUAR_ACCT_BS_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('703', 'E_GUAR_INSURANCE_INF', '企业担保账户在保责任信息段', 'E_GUAR_ACCT_BS', 'EEA_GUAR_ACCT_BS_SGMT_ID', 'EEF_GUAR_RLT_REPYMT_INF_SG_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('708', 'E_ACCT_SPEC_TRST', '企业借贷特定交易说明段', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDH_ACCT_SPEC_TRST_DSPN_SG_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('709', 'E_ACT_LBLTY_INF', '企业借贷还款表现信息段', 'E_ACCT_BS', 'EDA_ACCT_BS_SGMT_ID', 'EDG_ACT_LBLTY_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('711', 'I_CTRCT_BS', '基础段/个人授信协议按段更正类请求记录', 'I_CTRCT_BS', 'PCA_CTRCT_BS_SGMT_ID', 'PCA_CTRCT_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('712', 'I_ACCT_BS', '基础段/个人借贷按段更正请求记录信息', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBA_ACCT_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('713', 'I_GUAR_ACCT_BS', '基础段/个人担保账户按段更正类请求记录', 'I_GUAR_ACCT_BS', 'PDA_GUAR_ACCT_BS_SGMT_ID', 'PDA_GUAR_ACCT_BS_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('714', 'I_GUAR_RLT_REPYMT_INF', '个人担保账户相关还款责任人段', 'I_GUAR_ACCT_BS', 'PDA_GUAR_ACCT_BS_SGMT_ID', 'PDC_RLT_REPYMT_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('715', 'I_GR_REPYMT_INF', '个人担保账户在保责任信息段', 'I_GUAR_ACCT_BS', 'PDA_GUAR_ACCT_BS_SGMT_ID', 'PDE_GR_REPYMT_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('716', 'I_GUAR_MCC_INF', '个人担保账户抵质押物信息段', 'I_GUAR_ACCT_BS', 'PDA_GUAR_ACCT_BS_SGMT_ID', 'PDD_GUAR_MCC_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('717', 'I_AMBLG_INF', '个人借贷月度表现信息段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBG_AMBLG_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('718', 'I_ACCT_DBT_INF', '个人借贷非月度表现信息段', 'I_ACCT_BS', 'PBA_ACCT_BS_SGMT_ID', 'PBI_ACCT_DBT_INF_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('719', 'I_CREDIT_LIM', '个人授信额度信息段', 'I_CTRCT_BS', 'PCA_CTRCT_BS_SGMT_ID', 'PCC_CREDIT_LIM_SGMT_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('8', 'E_ACCT_INF_ID_CAGS_INF', '企业借贷账户标识变更类请求记录', 'E_ACCT_INF_ID_CAGS_INF', 'EDW_EN_ACCT_INF_ID_CAGS_INF_ID', 'EDW_EN_ACCT_INF_ID_CAGS_INF_ID');

insert into VALIDATE_TABLE (TABLE_ID, TABLE_NAME_EN, TABLE_NAME_CN, MASTER_TABLE_EN, MASTER_TABLE_PK, TBALE_PK)
values ('9', 'E_SEC_ACCT_ENT_DEL', '企业担保账户整笔删除请求记录', 'E_SEC_ACCT_ENT_DEL', 'EEZ_EN_SEC_ACCT_ENT_DEL_SG_ID', 'EEZ_EN_SEC_ACCT_ENT_DEL_SG_ID');

COMMIT;
