DELETE FROM VALIDATE_RULES_MANAGEMENT;
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I4100H06', '0', '若“账户状态”为“21-关闭”时，“当前逾期总额”、“当前逾期本金”和“当前逾期天数”必须为0', 'SQL', 'SELECT TRIM(B.ACCTCODE)
  FROM EC_TMP_DT_LOAN_ACTLBLTYINF A, EC_TMP_DT_LOAN_ACCTBS B
 WHERE A.SERINO = B.SERINO
   AND ((A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.TOTOVERD) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDPRINC) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDDY) <> 0))', 
    '1', 'EC_TMP_DT_LOAN_ACTLBLTYINF', 'TOTOVERD，OVERDPRINC，OVERDDY', '企业借贷账户-还款表现信息段', 'ACCT_CODE');
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I4100H07', '1', '若“账户状态”为“21-关闭”时，“当前逾期总额”、“当前逾期本金”和“当前逾期天数”必须为0', 'SQL', 'SELECT TRIM(B.ACCTCODE)
  FROM EC_TMP_DT_LOAN_ACTLBLTYINF A, EC_TMP_DT_LOAN_ACCTBS B
 WHERE A.SERINO = B.SERINO
   AND ((A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.TOTOVERD) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDPRINC) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDDY) <> 0))', 
    '1', 'EC_TMP_DT_LOAN_ACTLBLTYINF', 'TOTOVERD，OVERDPRINC，OVERDDY', '企业借贷账户-还款表现信息段', 'ACCTCODE');
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I4100H08', '1', '若“账户状态”为“21-关闭”时，“当前逾期总额”、“当前逾期本金”和“当前逾期天数”必须为0', 'SQL', 'SELECT TRIM(B.ACCTCODE)
  FROM EC_TMP_DT_LOAN_ACTLBLTYINF A, EC_TMP_DT_LOAN_ACCTBS B
 WHERE A.SERINO = B.SERINO
   AND ((A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.TOTOVERD) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDPRINC) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDDY) <> 0))', 
    '1', 'EC_TMP_DT_LOAN_ACTLBLTYINF', 'TOTOVERD，OVERDPRINC，OVERDDY', '企业借贷账户-还款表现信息段', 'ACCTCODE');
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I4100H04', '1', '若“账户状态”为“21-关闭”时，“当前逾期总额”、“当前逾期本金”和“当前逾期天数”必须为0', 'SQL', 'SELECT TRIM(B.ACCTCODE)
  FROM EC_TMP_DT_LOAN_ACTLBLTYINF A, EC_TMP_DT_LOAN_ACCTBS B
 WHERE A.SERINO = B.SERINO
   AND ((A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.TOTOVERD) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDPRINC) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDDY) <> 0))', 
    '1', 'EC_TMP_DT_LOAN_ACTLBLTYINF', 'TOTOVERD，OVERDPRINC，OVERDDY', '企业借贷账户-还款表现信息段', 'ACCTCODE');
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I4100H09', '1', '若“账户状态”为“21-关闭”时，“当前逾期总额”、“当前逾期本金”和“当前逾期天数”必须为0', 'SQL', 'SELECT TRIM(B.ACCTCODE)
  FROM EC_TMP_DT_LOAN_ACTLBLTYINF A, EC_TMP_DT_LOAN_ACCTBS B
 WHERE A.SERINO = B.SERINO
   AND ((A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.TOTOVERD) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDPRINC) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDDY) <> 0))', 
    '1', 'EC_TMP_DT_LOAN_ACTLBLTYINF', 'TOTOVERD，OVERDPRINC，OVERDDY', '企业借贷账户-还款表现信息段', 'ACCTCODE');
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I4100H10', '1', '若“账户状态”为“21-关闭”时，“当前逾期总额”、“当前逾期本金”和“当前逾期天数”必须为0', 'SQL', 'SELECT TRIM(B.ACCTCODE)
  FROM EC_TMP_DT_LOAN_ACTLBLTYINF A, EC_TMP_DT_LOAN_ACCTBS B
 WHERE A.SERINO = B.SERINO
   AND ((A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.TOTOVERD) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDPRINC) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDDY) <> 0))', 
    '1', 'EC_TMP_DT_LOAN_ACTLBLTYINF', 'TOTOVERD，OVERDPRINC，OVERDDY', '企业借贷账户-还款表现信息段', 'ACCTCODE');
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I4100H11', '1', '若“账户状态”为“21-关闭”时，“当前逾期总额”、“当前逾期本金”和“当前逾期天数”必须为0', 'SQL', 'SELECT TRIM(B.ACCTCODE)
  FROM EC_TMP_DT_LOAN_ACTLBLTYINF A, EC_TMP_DT_LOAN_ACCTBS B
 WHERE A.SERINO = B.SERINO
   AND ((A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.TOTOVERD) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDPRINC) <> 0) OR
       (A.ACCTSTATUS = ''21'' AND TO_NUMBER(A.OVERDDY) <> 0))', 
    '1', 'EC_TMP_DT_LOAN_ACTLBLTYINF', 'TOTOVERD，OVERDPRINC，OVERDDY', '企业借贷账户-还款表现信息段', 'ACCTCODE');
Insert into VALIDATE_RULES_MANAGEMENT
   (ERRNO, BUSINESSTYPE, ERRDESCRIBE, VALIDTYPE, VALIDEXPRESSION, 
    ISINUSE, CHECKTANLENAME, CHECKCOLNAME, CHTABLENAME, INTERNALKEY)
 Values
   ('I3400B01', '0', '企业身份标识整合信息记录中两组的“企业身份标识类型”、“企业身份标识号码”不能完全相同', 'PROCEDURE', 'SELECT ENTCERTNUM FROM EC_DT_CERTMERGE WHERE ENTCERTTYPE=OTHENTCERTTYPE AND ENTCERTNUM=OTHENTCERTNUM', 
    '1', 'EC_DT_CERTMERGE', 'ENTCERT_NUM', '企业身份标识整合信息文件校验规则', 'ENTCERTNUM');
COMMIT;
