CREATE TABLESPACE TS_SENSE_DATA_BS DATAFILE  'TS_ZXBS_DATA.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 300M;
CREATE TEMPORARY TABLESPACE TS_SENSE_TMP_BS TEMPFILE  'TS_ZXBS_TEMP.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 300M;
exit;
