CREATE USER ZXSENSE
  IDENTIFIED BY ZXSENSE
  DEFAULT TABLESPACE TS_SENSE_DATA_BS
  TEMPORARY TABLESPACE TS_SENSE_TMP_BS
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ZXSENSE
  GRANT CONNECT TO ZXSENSE;
  GRANT RESOURCE TO ZXSENSE;
  ALTER USER ZXSENSE DEFAULT ROLE ALL;
  -- 5 System Privileges for ZXSENSE
  GRANT CREATE ANY VIEW TO ZXSENSE;
  GRANT DROP ANY VIEW TO ZXSENSE;
  GRANT UNLIMITED TABLESPACE TO ZXSENSE;
  GRANT DEBUG ANY PROCEDURE TO ZXSENSE;
  GRANT SELECT ANY TABLE TO ZXSENSE;
  GRANT DEBUG CONNECT SESSION TO ZXSENSE;

/
exit
