CREATE TABLESPACE TS_ZXBS_DATA DATAFILE  'TS_ZXBS_DATA.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 300M;
CREATE TEMPORARY TABLESPACE TS_ZXBS_TMP TEMPFILE  'TS_ZXBS_TEMP.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 300M;
exit;
