CREATE USER ZXBS
  IDENTIFIED BY ZXBS
  DEFAULT TABLESPACE TS_ZXBS_DATA
  TEMPORARY TABLESPACE TS_ZXBS_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ZXBS
  GRANT CONNECT TO ZXBS;
  GRANT RESOURCE TO ZXBS;
  ALTER USER ZXBS DEFAULT ROLE ALL;
  -- 5 System Privileges for ZXBS
  GRANT CREATE ANY VIEW TO ZXBS;
  GRANT DROP ANY VIEW TO ZXBS;
  GRANT UNLIMITED TABLESPACE TO ZXBS;
  GRANT DEBUG ANY PROCEDURE TO ZXBS;
  GRANT SELECT ANY TABLE TO ZXBS;
  GRANT DEBUG CONNECT SESSION TO ZXBS;

/
exit
